--------------------------------------------------------
--  DDL for Trigger AP_PRODUCT_SETUP_AT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."AP_PRODUCT_SETUP_AT" BEFORE UPDATE OF RECORD_NUMBER,ALWAYS_TAKE_DISC_FLAG,AUTO_CALCULATE_INTEREST_FLAG,BANK_CHARGE_BEARER,CREATED_BY,CREATION_DATE,HOLD_UNMATCHED_INVOICES_FLAG,INVOICE_CURRENCY_CODE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,MATCH_OPTION,NEXT_AUTO_SUPPLIER_NUM,PAYMENT_METHOD_LOOKUP_CODE,PAY_DATE_BASIS_LOOKUP_CODE,SUPPLIER_NUMBERING_METHOD,SUPPLIER_NUM_TYPE,SUPPLIER_PAY_GROUP_LOOKUP_CODE,TERMS_DATE_BASIS,TERMS_ID,USE_BANK_CHARGE_FLAG ON "AP"."AP_PRODUCT_SETUP" BEGIN IF fnd_global.audit_active THEN fnd_audit_pkg.audit_on := TRUE;ELSE fnd_audit_pkg.audit_on := FALSE;END IF;END;

/
ALTER TRIGGER "APPS"."AP_PRODUCT_SETUP_AT" ENABLE;
