--------------------------------------------------------
--  DDL for Trigger AP_PRODUCT_SETUP_AD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."AP_PRODUCT_SETUP_AD" AFTER DELETE ON "AP"."AP_PRODUCT_SETUP" FOR EACH ROW BEGIN IF fnd_audit_pkg.audit_on THEN AP_PRODUCT_SETUP_ADP(:old.RECORD_NUMBER,:old.ALWAYS_TAKE_DISC_FLAG,:old.AUTO_CALCULATE_INTEREST_FLAG,:old.BANK_CHARGE_BEARER,:old.CREATED_BY,:old.CREATION_DATE,:old.HOLD_UNMATCHED_INVOICES_FLAG,:old.INVOICE_CURRENCY_CODE,:old.LAST_UPDATED_BY,:old.LAST_UPDATE_DATE,:old.LAST_UPDATE_LOGIN,:old.MATCH_OPTION,:old.NEXT_AUTO_SUPPLIER_NUM,:old.PAYMENT_METHOD_LOOKUP_CODE,:old.PAY_DATE_BASIS_LOOKUP_CODE,:old.SUPPLIER_NUMBERING_METHOD,:old.SUPPLIER_NUM_TYPE,:old.SUPPLIER_PAY_GROUP_LOOKUP_CODE,:old.TERMS_DATE_BASIS,:old.TERMS_ID,:old.USE_BANK_CHARGE_FLAG,:new.RECORD_NUMBER,:new.ALWAYS_TAKE_DISC_FLAG,:new.AUTO_CALCULATE_INTEREST_FLAG,:new.BANK_CHARGE_BEARER,:new.CREATED_BY,:new.CREATION_DATE,:new.HOLD_UNMATCHED_INVOICES_FLAG,:new.INVOICE_CURRENCY_CODE,:new.LAST_UPDATED_BY,:new.LAST_UPDATE_DATE,:new.LAST_UPDATE_LOGIN,:new.MATCH_OPTION,:new.NEXT_AUTO_SUPPLIER_NUM,:new.PAYMENT_METHOD_LOOKUP_CODE,:new.PAY_DATE_BASIS_LOOKUP_CODE,:new.SUPPLIER_NUMBERING_METHOD,:new.SUPPLIER_NUM_TYPE,:new.SUPPLIER_PAY_GROUP_LOOKUP_CODE,:new.TERMS_DATE_BASIS,:new.TERMS_ID,:new.USE_BANK_CHARGE_FLAG);END IF;END;

/
ALTER TRIGGER "APPS"."AP_PRODUCT_SETUP_AD" ENABLE;
