--------------------------------------------------------
--  DDL for Trigger CE_SYSTEM_PARAMETERS_AT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CE_SYSTEM_PARAMETERS_AT" BEFORE UPDATE OF LEGAL_ENTITY_ID,SET_OF_BOOKS_ID,ATTRIBUTE1,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE_CATEGORY,AUTHORIZATION_BAT,BAT_EXCHANGE_DATE_TYPE,BSC_EXCHANGE_DATE_TYPE,CASHBOOK_BEGIN_DATE,CASHFLOW_EXCHANGE_RATE_TYPE,CREATED_BY,CREATION_DATE,INTERFACE_ARCHIVE_FLAG,INTERFACE_PURGE_FLAG,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,LINES_PER_COMMIT,LINE_AUTOCREATION_FLAG,SHOW_CLEARED_FLAG,SHOW_VOID_PAYMENT_FLAG,SIGNING_AUTHORITY_APPR_FLAG ON "CE"."CE_SYSTEM_PARAMETERS" BEGIN IF fnd_global.audit_active THEN fnd_audit_pkg.audit_on := TRUE;ELSE fnd_audit_pkg.audit_on := FALSE;END IF;END;

/
ALTER TRIGGER "APPS"."CE_SYSTEM_PARAMETERS_AT" ENABLE;
