--------------------------------------------------------
--  DDL for Trigger CM_CLDR_HDR_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CM_CLDR_HDR_IL" 
/* $Header: gmfclitg.sql 120.2 2005/10/05 07:53:30 anthiyag noship $ */
INSTEAD OF INSERT ON CM_CLDR_HDR_VL
REFERENCING NEW AS CM_CLDR_HDR
FOR EACH ROW
DECLARE
  row_id ROWID;
BEGIN
  CM_CLDR_HDR_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_CALENDAR_CODE => :CM_CLDR_HDR.CALENDAR_CODE,
    X_START_DATE => :CM_CLDR_HDR.START_DATE,
    X_IN_USE => :CM_CLDR_HDR.IN_USE,
    X_TEXT_CODE => :CM_CLDR_HDR.TEXT_CODE,
    X_DELETE_MARK => :CM_CLDR_HDR.DELETE_MARK,
    X_ATTRIBUTE1 => :CM_CLDR_HDR.ATTRIBUTE1,
    X_ATTRIBUTE2 => :CM_CLDR_HDR.ATTRIBUTE2,
    X_ATTRIBUTE3 => :CM_CLDR_HDR.ATTRIBUTE3,
    X_ATTRIBUTE4 => :CM_CLDR_HDR.ATTRIBUTE4,
    X_ATTRIBUTE5 => :CM_CLDR_HDR.ATTRIBUTE5,
    X_ATTRIBUTE6 => :CM_CLDR_HDR.ATTRIBUTE6,
    X_ATTRIBUTE7 => :CM_CLDR_HDR.ATTRIBUTE7,
    X_ATTRIBUTE8 => :CM_CLDR_HDR.ATTRIBUTE8,
    X_ATTRIBUTE9 => :CM_CLDR_HDR.ATTRIBUTE9,
    X_ATTRIBUTE10 => :CM_CLDR_HDR.ATTRIBUTE10,
    X_ATTRIBUTE11 => :CM_CLDR_HDR.ATTRIBUTE11,
    X_ATTRIBUTE12 => :CM_CLDR_HDR.ATTRIBUTE12,
    X_ATTRIBUTE13 => :CM_CLDR_HDR.ATTRIBUTE13,
    X_ATTRIBUTE14 => :CM_CLDR_HDR.ATTRIBUTE14,
    X_ATTRIBUTE15 => :CM_CLDR_HDR.ATTRIBUTE15,
    X_ATTRIBUTE16 => :CM_CLDR_HDR.ATTRIBUTE16,
    X_ATTRIBUTE17 => :CM_CLDR_HDR.ATTRIBUTE17,
    X_ATTRIBUTE18 => :CM_CLDR_HDR.ATTRIBUTE18,
    X_ATTRIBUTE19 => :CM_CLDR_HDR.ATTRIBUTE19,
    X_ATTRIBUTE20 => :CM_CLDR_HDR.ATTRIBUTE20,
    X_ATTRIBUTE21 => :CM_CLDR_HDR.ATTRIBUTE21,
    X_ATTRIBUTE22 => :CM_CLDR_HDR.ATTRIBUTE22,
    X_ATTRIBUTE23 => :CM_CLDR_HDR.ATTRIBUTE23,
    X_ATTRIBUTE24 => :CM_CLDR_HDR.ATTRIBUTE24,
    X_ATTRIBUTE25 => :CM_CLDR_HDR.ATTRIBUTE25,
    X_ATTRIBUTE26 => :CM_CLDR_HDR.ATTRIBUTE26,
    X_ATTRIBUTE27 => :CM_CLDR_HDR.ATTRIBUTE27,
    X_ATTRIBUTE28 => :CM_CLDR_HDR.ATTRIBUTE28,
    X_ATTRIBUTE29 => :CM_CLDR_HDR.ATTRIBUTE29,
    X_ATTRIBUTE30 => :CM_CLDR_HDR.ATTRIBUTE30,
    X_CALENDAR_DESC => :CM_CLDR_HDR.CALENDAR_DESC,
    X_CREATION_DATE => :CM_CLDR_HDR.CREATION_DATE,
    X_CREATED_BY => :CM_CLDR_HDR.CREATED_BY,
    X_LAST_UPDATE_DATE => :CM_CLDR_HDR.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :CM_CLDR_HDR.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :CM_CLDR_HDR.LAST_UPDATE_LOGIN);
END INSERT_ROW;


/
ALTER TRIGGER "APPS"."CM_CLDR_HDR_IL" ENABLE;
