--------------------------------------------------------
--  DDL for Trigger CM_CMPT_MST_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CM_CMPT_MST_IL" 
/* $Header: gmfccitg.sql 120.1 2005/06/17 13:42:51 appldev  $ */
INSTEAD OF INSERT ON CM_CMPT_MST_VL
REFERENCING NEW AS CM_CMPT_MST
FOR EACH ROW
DECLARE
  row_id ROWID;
BEGIN
  CM_CMPT_MST_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_COST_CMPNTCLS_ID => :CM_CMPT_MST.COST_CMPNTCLS_ID,
    X_COST_CMPNTCLS_CODE => :CM_CMPT_MST.COST_CMPNTCLS_CODE,
    X_SORT_SEQUENCE => :CM_CMPT_MST.SORT_SEQUENCE,
    X_USAGE_IND => :CM_CMPT_MST.USAGE_IND,
    X_PRIMARY_CMPNTCLS_ID => :CM_CMPT_MST.PRIMARY_CMPNTCLS_ID,
    X_PRODUCT_COST_IND => :CM_CMPT_MST.PRODUCT_COST_IND,
    X_UPDATE_COST_IND => :CM_CMPT_MST.UPDATE_COST_IND,
    X_CMPNT_GROUP => :CM_CMPT_MST.CMPNT_GROUP,
    X_TEXT_CODE => :CM_CMPT_MST.TEXT_CODE,
    X_TRANS_CNT => :CM_CMPT_MST.TRANS_CNT,
    X_DELETE_MARK => :CM_CMPT_MST.DELETE_MARK,
    X_PPV_IND => :CM_CMPT_MST.PPV_IND,
    X_ATTRIBUTE1 => :CM_CMPT_MST.ATTRIBUTE1,
    X_ATTRIBUTE2 => :CM_CMPT_MST.ATTRIBUTE2,
    X_ATTRIBUTE3 => :CM_CMPT_MST.ATTRIBUTE3,
    X_ATTRIBUTE4 => :CM_CMPT_MST.ATTRIBUTE4,
    X_ATTRIBUTE5 => :CM_CMPT_MST.ATTRIBUTE5,
    X_ATTRIBUTE6 => :CM_CMPT_MST.ATTRIBUTE6,
    X_ATTRIBUTE7 => :CM_CMPT_MST.ATTRIBUTE7,
    X_ATTRIBUTE8 => :CM_CMPT_MST.ATTRIBUTE8,
    X_ATTRIBUTE9 => :CM_CMPT_MST.ATTRIBUTE9,
    X_ATTRIBUTE10 => :CM_CMPT_MST.ATTRIBUTE10,
    X_ATTRIBUTE11 => :CM_CMPT_MST.ATTRIBUTE11,
    X_ATTRIBUTE12 => :CM_CMPT_MST.ATTRIBUTE12,
    X_ATTRIBUTE13 => :CM_CMPT_MST.ATTRIBUTE13,
    X_ATTRIBUTE14 => :CM_CMPT_MST.ATTRIBUTE14,
    X_ATTRIBUTE15 => :CM_CMPT_MST.ATTRIBUTE15,
    X_ATTRIBUTE16 => :CM_CMPT_MST.ATTRIBUTE16,
    X_ATTRIBUTE17 => :CM_CMPT_MST.ATTRIBUTE17,
    X_ATTRIBUTE18 => :CM_CMPT_MST.ATTRIBUTE18,
    X_ATTRIBUTE19 => :CM_CMPT_MST.ATTRIBUTE19,
    X_ATTRIBUTE20 => :CM_CMPT_MST.ATTRIBUTE20,
    X_ATTRIBUTE21 => :CM_CMPT_MST.ATTRIBUTE21,
    X_ATTRIBUTE22 => :CM_CMPT_MST.ATTRIBUTE22,
    X_ATTRIBUTE23 => :CM_CMPT_MST.ATTRIBUTE23,
    X_ATTRIBUTE24 => :CM_CMPT_MST.ATTRIBUTE24,
    X_ATTRIBUTE25 => :CM_CMPT_MST.ATTRIBUTE25,
    X_ATTRIBUTE26 => :CM_CMPT_MST.ATTRIBUTE26,
    X_ATTRIBUTE27 => :CM_CMPT_MST.ATTRIBUTE27,
    X_ATTRIBUTE28 => :CM_CMPT_MST.ATTRIBUTE28,
    X_ATTRIBUTE29 => :CM_CMPT_MST.ATTRIBUTE29,
    X_ATTRIBUTE30 => :CM_CMPT_MST.ATTRIBUTE30,
    X_ATTRIBUTE_CATEGORY => :CM_CMPT_MST.ATTRIBUTE_CATEGORY,
    X_COST_CMPNTCLS_DESC => :CM_CMPT_MST.COST_CMPNTCLS_DESC,
    X_CREATION_DATE => :CM_CMPT_MST.CREATION_DATE,
    X_CREATED_BY => :CM_CMPT_MST.CREATED_BY,
    X_LAST_UPDATE_DATE => :CM_CMPT_MST.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :CM_CMPT_MST.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :CM_CMPT_MST.LAST_UPDATE_LOGIN);
end INSERT_ROW;


/
ALTER TRIGGER "APPS"."CM_CMPT_MST_IL" ENABLE;
