--------------------------------------------------------
--  DDL for Trigger CS_FORUM_CATEGORIES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CS_FORUM_CATEGORIES_UL" 
/* $Header: csfcvu.sql 115.0 2000/11/17 11:18:48 pkm ship     $ */
instead of update on CS_FORUM_CATEGORIES_VL
referencing old as CATEGORIES
for each row

begin
  CS_FORUM_CATEGORIES_PKG.UPDATE_ROW(
    X_CATEGORY_ID => :CATEGORIES.CATEGORY_ID,
    X_CATEGORY_TYPE => :CATEGORIES.CATEGORY_TYPE,
    X_CATEGORY_NAME => :CATEGORIES.CATEGORY_NAME,
    X_NAME => :CATEGORIES.NAME,
    X_DESCRIPTION => :CATEGORIES.DESCRIPTION,
    X_STATUS => :CATEGORIES.STATUS,
    X_LAST_UPDATE_DATE => :CATEGORIES.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :CATEGORIES.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :CATEGORIES.LAST_UPDATE_LOGIN,
    X_ATTRIBUTE_CATEGORY => :CATEGORIES.ATTRIBUTE_CATEGORY,
    X_ATTRIBUTE1 => :CATEGORIES.ATTRIBUTE1,
    X_ATTRIBUTE2 => :CATEGORIES.ATTRIBUTE2,
    X_ATTRIBUTE3 => :CATEGORIES.ATTRIBUTE3,
    X_ATTRIBUTE4 => :CATEGORIES.ATTRIBUTE4,
    X_ATTRIBUTE5 => :CATEGORIES.ATTRIBUTE5,
    X_ATTRIBUTE6 => :CATEGORIES.ATTRIBUTE6,
    X_ATTRIBUTE7 => :CATEGORIES.ATTRIBUTE7,
    X_ATTRIBUTE8 => :CATEGORIES.ATTRIBUTE8,
    X_ATTRIBUTE9 => :CATEGORIES.ATTRIBUTE9,
    X_ATTRIBUTE10 => :CATEGORIES.ATTRIBUTE10,
    X_ATTRIBUTE11 => :CATEGORIES.ATTRIBUTE11,
    X_ATTRIBUTE12 => :CATEGORIES.ATTRIBUTE12,
    X_ATTRIBUTE13 => :CATEGORIES.ATTRIBUTE13,
    X_ATTRIBUTE14 => :CATEGORIES.ATTRIBUTE14,
    X_ATTRIBUTE15 => :CATEGORIES.ATTRIBUTE15
  );
end UPDATE_ROW;



/
ALTER TRIGGER "APPS"."CS_FORUM_CATEGORIES_UL" ENABLE;
