--------------------------------------------------------
--  DDL for Trigger CZ_DEVL_PROJECTS_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CZ_DEVL_PROJECTS_T1" 
  BEFORE INSERT OR UPDATE OF
  NAME,
  DESC_TEXT,
  PRODUCT_KEY,
  BOM_CAPTION_RULE_ID,
  NONBOM_CAPTION_RULE_ID,
  LAST_STRUCT_UPDATE,
  LAST_LOGIC_UPDATE,
  DELETED_FLAG,
  BOM_CAPTION_TEXT_ID,
  NONBOM_CAPTION_TEXT_ID,
  MODEL_TYPE
ON "CZ"."CZ_DEVL_PROJECTS"
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
VAR_USER_ID INTEGER;
l_profile_value VARCHAR2(100);
BEGIN
VAR_USER_ID:=CZ_UTILS.SPX_UID;
IF INSERTING THEN
   :new.CREATED_BY:=VAR_USER_ID;
   :new.LAST_UPDATED_BY:=VAR_USER_ID;
   :new.CREATION_DATE:=SYSDATE;
   :new.LAST_UPDATE_DATE:=SYSDATE;
   :new.LAST_STRUCT_UPDATE:=SYSDATE;
   :new.LAST_LOGIC_UPDATE:=SYSDATE;
   l_profile_value := FND_PROFILE.value('CZ_EDIT_MODELS_NO_LOCK');
   IF (l_profile_value = 'N') THEN
     :new.checkout_user := FND_GLOBAL.user_name;
   END IF;
END IF;
IF UPDATING AND
    ((
      (((:old.name IS NULL)<>(:new.name IS NULL))OR(:old.name<>:new.name)) OR
      (((:old.desc_text IS NULL)<>(:new.desc_text IS NULL))OR(:old.desc_text<>:new.desc_text)) OR
      (((:old.PRODUCT_KEY IS NULL)<>(:new.PRODUCT_KEY IS NULL))OR(:old.PRODUCT_KEY<>:new.PRODUCT_KEY)) OR
      (((:old.BOM_CAPTION_RULE_ID IS NULL)<>(:new.BOM_CAPTION_RULE_ID IS NULL))OR(:old.BOM_CAPTION_RULE_ID<>:new.BOM_CAPTION_RULE_ID)) OR
      (((:old.NONBOM_CAPTION_RULE_ID IS NULL)<>(:new.NONBOM_CAPTION_RULE_ID IS NULL))OR(:old.NONBOM_CAPTION_RULE_ID<>:new.NONBOM_CAPTION_RULE_ID)) OR
      (((:old.BOM_CAPTION_TEXT_ID IS NULL)<>(:new.BOM_CAPTION_TEXT_ID IS NULL))OR(:old.BOM_CAPTION_TEXT_ID<>:new.BOM_CAPTION_TEXT_ID)) OR
      (((:old.NONBOM_CAPTION_TEXT_ID IS NULL)<>(:new.NONBOM_CAPTION_TEXT_ID IS NULL))OR(:old.NONBOM_CAPTION_TEXT_ID<>:new.NONBOM_CAPTION_TEXT_ID)) OR
      (((:old.MODEL_TYPE IS NULL)<>(:new.MODEL_TYPE IS NULL))OR(:old.MODEL_TYPE<>:new.MODEL_TYPE)) OR
      (((:old.LAST_STRUCT_UPDATE IS NULL)<>(:new.LAST_STRUCT_UPDATE IS NULL))OR(:old.LAST_STRUCT_UPDATE<>:new.LAST_STRUCT_UPDATE)) OR
      (((:old.LAST_LOGIC_UPDATE IS NULL)<>(:new.LAST_LOGIC_UPDATE IS NULL))OR(:old.LAST_LOGIC_UPDATE<>:new.LAST_LOGIC_UPDATE))
     )) THEN
       :new.LAST_UPDATED_BY:=VAR_USER_ID;
       :new.LAST_UPDATE_DATE:=SYSDATE;
END IF;
END;

/
ALTER TRIGGER "APPS"."CZ_DEVL_PROJECTS_T1" ENABLE;
