--------------------------------------------------------
--  DDL for Trigger CZ_DEVL_PROJECTS_T2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CZ_DEVL_PROJECTS_T2" 
  BEFORE DELETE
 ON "CZ"."CZ_DEVL_PROJECTS"
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
 DELETE FROM CZ_RP_ENTRIES
 WHERE OBJECT_TYPE = 'PRJ' AND OBJECT_ID = :OLD.DEVL_PROJECT_ID;

 DELETE FROM CZ_PERSISTENT_REC_IDS
 WHERE devl_project_id = :OLD.DEVL_PROJECT_ID;


--Re: bug #2131259.

 DELETE FROM CZ_XFR_PROJECT_BILLS
 WHERE MODEL_PS_NODE_ID = :OLD.DEVL_PROJECT_ID;
END;

/
ALTER TRIGGER "APPS"."CZ_DEVL_PROJECTS_T2" ENABLE;
