--------------------------------------------------------
--  DDL for Trigger CZ_DEVL_PROJECTS_TP1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CZ_DEVL_PROJECTS_TP1" 
BEFORE INSERT
ON "CZ"."CZ_DEVL_PROJECTS"
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
	IF :NEW.PERSISTENT_PROJECT_ID IS NULL THEN
   		:new.PERSISTENT_PROJECT_ID:=:NEW.DEVL_PROJECT_ID;
	END IF;
	IF :NEW.VERSION IS NULL THEN
   		:new.VERSION:=1; --kdande; Bug 6885757; 17-Mar-2008
	END IF;
END;

/
ALTER TRIGGER "APPS"."CZ_DEVL_PROJECTS_TP1" ENABLE;
