--------------------------------------------------------
--  DDL for Trigger CZ_EXPRESSIONS_TP1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CZ_EXPRESSIONS_TP1" 
BEFORE INSERT
ON "CZ"."CZ_EXPRESSIONS"
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
	IF :NEW.PERSISTENT_EXPRESSION_ID IS NULL THEN
   :new.PERSISTENT_EXPRESSION_ID:=:NEW.EXPRESS_ID;
END IF;
END;

/
ALTER TRIGGER "APPS"."CZ_EXPRESSIONS_TP1" ENABLE;
