--------------------------------------------------------
--  DDL for Trigger CZ_EFFECTIVITY_SETS_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CZ_EFFECTIVITY_SETS_T1" 
 BEFORE DELETE
 ON "CZ"."CZ_EFFECTIVITY_SETS"
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
 DELETE FROM CZ_RP_ENTRIES
 WHERE OBJECT_TYPE = 'EFF' AND OBJECT_ID = :OLD.EFFECTIVITY_SET_ID;
END;

/
ALTER TRIGGER "APPS"."CZ_EFFECTIVITY_SETS_T1" ENABLE;
