--------------------------------------------------------
--  DDL for Trigger CZ_EFFECTIVITY_SETS_T2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CZ_EFFECTIVITY_SETS_T2" 
 BEFORE UPDATE OR INSERT
 ON "CZ"."CZ_EFFECTIVITY_SETS"
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
DECLARE
 VAR_USER_ID INTEGER;
BEGIN
VAR_USER_ID:=CZ_UTILS.SPX_UID;
IF INSERTING THEN
   :NEW.CREATED_BY:=VAR_USER_ID;
   :NEW.LAST_UPDATED_BY:=VAR_USER_ID;
   :NEW.CREATION_DATE:=SYSDATE;
   :NEW.LAST_UPDATE_DATE:=SYSDATE;
END IF;
IF UPDATING THEN
   :NEW.LAST_UPDATED_BY:=VAR_USER_ID;
   :NEW.LAST_UPDATE_DATE:=SYSDATE;
END IF;
END;

/
ALTER TRIGGER "APPS"."CZ_EFFECTIVITY_SETS_T2" ENABLE;
