--------------------------------------------------------
--  DDL for Trigger CZ_MODEL_USAGES_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CZ_MODEL_USAGES_T1" 
  BEFORE DELETE
 ON "CZ"."CZ_MODEL_USAGES"
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
 DELETE FROM CZ_RP_ENTRIES
 WHERE OBJECT_TYPE = 'USG' AND OBJECT_ID = :OLD.MODEL_USAGE_ID;
END;

/
ALTER TRIGGER "APPS"."CZ_MODEL_USAGES_T1" ENABLE;
