--------------------------------------------------------
--  DDL for Trigger CZ_POPULATORS_TP1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."CZ_POPULATORS_TP1" 
BEFORE INSERT
ON "CZ"."CZ_POPULATORS"
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
	IF :NEW.PERSISTENT_POPULATOR_ID IS NULL THEN
   :new.PERSISTENT_POPULATOR_ID:=:NEW.POPULATOR_ID;
END IF;
END;

/
ALTER TRIGGER "APPS"."CZ_POPULATORS_TP1" ENABLE;
