--------------------------------------------------------
--  DDL for Trigger EDR_FWK_TEST_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."EDR_FWK_TEST_IL" 
/* $Header: EDRFTITG.sql 120.0.12000000.1 2007/01/18 05:52:57 appldev ship $ */
instead of insert on EDR_FWK_TEST_VL
referencing new as EDR_FWK_TEST
for each row
declare
  row_id rowid;
begin
/************************************************
 ***  Instead of Trigger to indert a row into  **
 ***  EDR_FWK_TEST_VL this intern inserts rows **
 ***  into EDR_FWK_TEST_B and EDR_FWK_TEST_TL  **
 ************************************************/
  EDR_FWK_TEST_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_FWK_TEST_ID => :EDR_FWK_TEST.FWK_TEST_ID,
    X_FWK_TEST_NO => :EDR_FWK_TEST.FWK_TEST_NO,
    X_NUMBER_VALUE => :EDR_FWK_TEST.NUMBER_VALUE,
    X_DATE_VALUE => :EDR_FWK_TEST.DATE_VALUE,
    X_STATUS => :EDR_FWK_TEST.STATUS,
    X_ATTRIBUTE1 => :EDR_FWK_TEST.ATTRIBUTE1,
    X_ATTRIBUTE2 => :EDR_FWK_TEST.ATTRIBUTE2,
    X_ATTRIBUTE3 => :EDR_FWK_TEST.ATTRIBUTE3,
    X_ATTRIBUTE4 => :EDR_FWK_TEST.ATTRIBUTE4,
    X_ATTRIBUTE5 => :EDR_FWK_TEST.ATTRIBUTE5,
    X_ATTRIBUTE6 => :EDR_FWK_TEST.ATTRIBUTE6,
    X_ATTRIBUTE7 => :EDR_FWK_TEST.ATTRIBUTE7,
    X_ATTRIBUTE8 => :EDR_FWK_TEST.ATTRIBUTE8,
    X_ATTRIBUTE9 => :EDR_FWK_TEST.ATTRIBUTE9,
    X_ATTRIBUTE10 => :EDR_FWK_TEST.ATTRIBUTE10,
    X_ATTRIBUTE11 => :EDR_FWK_TEST.ATTRIBUTE11,
    X_ATTRIBUTE12 => :EDR_FWK_TEST.ATTRIBUTE12,
    X_ATTRIBUTE13 => :EDR_FWK_TEST.ATTRIBUTE13,
    X_ATTRIBUTE14 => :EDR_FWK_TEST.ATTRIBUTE14,
    X_ATTRIBUTE15 => :EDR_FWK_TEST.ATTRIBUTE15,
    X_ATTRIBUTE16 => :EDR_FWK_TEST.ATTRIBUTE16,
    X_ATTRIBUTE17 => :EDR_FWK_TEST.ATTRIBUTE17,
    X_ATTRIBUTE18 => :EDR_FWK_TEST.ATTRIBUTE18,
    X_ATTRIBUTE19 => :EDR_FWK_TEST.ATTRIBUTE19,
    X_ATTRIBUTE20 => :EDR_FWK_TEST.ATTRIBUTE20,
    X_ATTRIBUTE21 => :EDR_FWK_TEST.ATTRIBUTE21,
    X_ATTRIBUTE22 => :EDR_FWK_TEST.ATTRIBUTE22,
    X_ATTRIBUTE23 => :EDR_FWK_TEST.ATTRIBUTE23,
    X_ATTRIBUTE24 => :EDR_FWK_TEST.ATTRIBUTE24,
    X_ATTRIBUTE25 => :EDR_FWK_TEST.ATTRIBUTE25,
    X_ATTRIBUTE26 => :EDR_FWK_TEST.ATTRIBUTE26,
    X_ATTRIBUTE27 => :EDR_FWK_TEST.ATTRIBUTE27,
    X_ATTRIBUTE28 => :EDR_FWK_TEST.ATTRIBUTE28,
    X_ATTRIBUTE29 => :EDR_FWK_TEST.ATTRIBUTE29,
    X_ATTRIBUTE30 => :EDR_FWK_TEST.ATTRIBUTE30,
    X_ATTRIBUTE_CATEGORY => :EDR_FWK_TEST.ATTRIBUTE_CATEGORY,
    X_FWK_TEST_DESCRIPTION => :EDR_FWK_TEST.FWK_TEST_DESCRIPTION,
    X_CREATION_DATE => :EDR_FWK_TEST.CREATION_DATE,
    X_CREATED_BY => :EDR_FWK_TEST.CREATED_BY,
    X_LAST_UPDATE_DATE => :EDR_FWK_TEST.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :EDR_FWK_TEST.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :EDR_FWK_TEST.LAST_UPDATE_LOGIN);
end INSERT_ROW;


/
ALTER TRIGGER "APPS"."EDR_FWK_TEST_IL" ENABLE;
