--------------------------------------------------------
--  DDL for Trigger FA_SYSTEM_CONTROLS_AT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FA_SYSTEM_CONTROLS_AT" BEFORE UPDATE OF COMPANY_NAME,ASSET_KEY_FLEX_STRUCTURE,ATTRIBUTE1,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE_CATEGORY_CODE,CATEGORY_FLEX_STRUCTURE,CREATED_BY,CREATION_DATE,CUA_INHERITANCE_FLAG,DATE_PLACED_IN_SERVICE,FA_APPLICATION_ID,GL_APPLICATION_ID,GROUP_FLEX_STRUCTURE,INITIAL_ASSET_ID,LAST_MASS_ADDITIONS,LAST_MASS_ADDITIONS_POST,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,LOCATION_FLEX_STRUCTURE,SUPER_GROUP_FLEX_STRUCTURE,USE_CUSTOM_ASSET_NUMBERS_FLAG ON "FA"."FA_SYSTEM_CONTROLS" BEGIN IF fnd_global.audit_active THEN fnd_audit_pkg.audit_on := TRUE;ELSE fnd_audit_pkg.audit_on := FALSE;END IF;END;

/
ALTER TRIGGER "APPS"."FA_SYSTEM_CONTROLS_AT" ENABLE;
