--------------------------------------------------------
--  DDL for Trigger FEM_EXCEPTIONS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_EXCEPTIONS_UL" 
instead of update on FEM_EXCEPTIONS_VL
referencing new as FEM_EXCEPTIONS_B
for each row
begin
  FEM_EXCEPTIONS_PKG.UPDATE_ROW(
    X_EXCEPTION_CODE => :FEM_EXCEPTIONS_B.EXCEPTION_CODE,
    X_ENABLED_FLAG => :FEM_EXCEPTIONS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_EXCEPTIONS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_EXCEPTIONS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_EXCEPTIONS_B.OBJECT_VERSION_NUMBER,
    X_EXCEPTION_NAME => :FEM_EXCEPTIONS_B.EXCEPTION_NAME,
    X_DESCRIPTION => :FEM_EXCEPTIONS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_EXCEPTIONS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_EXCEPTIONS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_EXCEPTIONS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_EXCEPTIONS_UL" ENABLE;
