--------------------------------------------------------
--  DDL for Trigger FEM_OBJECT_TYPES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_OBJECT_TYPES_UL" 
instead of update on FEM_OBJECT_TYPES_VL
referencing new as FEM_OBJECT_TYPES_B
for each row
begin
  FEM_OBJECT_TYPES_PKG.UPDATE_ROW(
    X_OBJECT_TYPE_CODE => :FEM_OBJECT_TYPES_B.OBJECT_TYPE_CODE,
    X_OBJECT_PLSQL_PKG_NAME => :FEM_OBJECT_TYPES_B.OBJECT_PLSQL_PKG_NAME,
    X_VIEW_ONLY_OA_FUNCTION_NAME => :FEM_OBJECT_TYPES_B.VIEW_ONLY_OA_FUNCTION_NAME,
    X_ALWAYS_RERUNNABLE_FLAG => :FEM_OBJECT_TYPES_B.ALWAYS_RERUNNABLE_FLAG,
    X_CONCURRENT_PROGRAM_NAME => :FEM_OBJECT_TYPES_B.CONCURRENT_PROGRAM_NAME,
    X_CONCURRENT_PROGRAM_APP_ID => :FEM_OBJECT_TYPES_B.CONCURRENT_PROGRAM_APP_ID,
    X_AVAILABLE_IN_RULESETS_FLAG => :FEM_OBJECT_TYPES_B.AVAILABLE_IN_RULESETS_FLAG,
    X_PROCESS_ENGINE_CD => :FEM_OBJECT_TYPES_B.PROCESS_ENGINE_CD,
    X_USAGE_CODE => :FEM_OBJECT_TYPES_B.USAGE_CODE,
    X_CONCURRENT_MGR_ENABLED_FLAG => :FEM_OBJECT_TYPES_B.CONCURRENT_MGR_ENABLED_FLAG,
    X_MULTIPLE_DEFINITIONS_FLAG => :FEM_OBJECT_TYPES_B.MULTIPLE_DEFINITIONS_FLAG,
    X_WORKFLOW_ENABLED_FLAG => :FEM_OBJECT_TYPES_B.WORKFLOW_ENABLED_FLAG,
    X_DATA_EDIT_LOCK_FLAG => :FEM_OBJECT_TYPES_B.DATA_EDIT_LOCK_FLAG,
    X_VISUAL_TRACE_FLAG => :FEM_OBJECT_TYPES_B.VISUAL_TRACE_FLAG,
    X_UNDO_FLAG => :FEM_OBJECT_TYPES_B.UNDO_FLAG,
    X_EXECUTABLE_FLAG => :FEM_OBJECT_TYPES_B.EXECUTABLE_FLAG,
    X_EXECUTABLE_LOCK_FLAG => :FEM_OBJECT_TYPES_B.EXECUTABLE_LOCK_FLAG,
    X_ISETUP_IMPORT_EXPORT_FLAG => :FEM_OBJECT_TYPES_B.ISETUP_IMPORT_EXPORT_FLAG,
    X_CUSTOM_IMPORT_EXPORT_FLAG => :FEM_OBJECT_TYPES_B.CUSTOM_IMPORT_EXPORT_FLAG,
    X_OBJECT_TYPE_NAME => :FEM_OBJECT_TYPES_B.OBJECT_TYPE_NAME,
    X_DESCRIPTION => :FEM_OBJECT_TYPES_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_OBJECT_TYPES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_OBJECT_TYPES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_OBJECT_TYPES_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_OBJECT_TYPES_UL" ENABLE;
