--------------------------------------------------------
--  DDL for Trigger FEM_FIDAGRMNTS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_FIDAGRMNTS_UL" 
instead of update on FEM_FIDAGRMNTS_VL
referencing new as FEM_FIDAGRMNTS_B
for each row
begin
  FEM_FIDAGRMNTS_PKG.UPDATE_ROW(
    X_FIDUCIARY_AGREEMENT_CODE => :FEM_FIDAGRMNTS_B.FIDUCIARY_AGREEMENT_CODE,
    X_ENABLED_FLAG => :FEM_FIDAGRMNTS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_FIDAGRMNTS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_FIDAGRMNTS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_FIDAGRMNTS_B.OBJECT_VERSION_NUMBER,
    X_FIDUCIARY_AGREEMENT_NAME => :FEM_FIDAGRMNTS_B.FIDUCIARY_AGREEMENT_NAME,
    X_DESCRIPTION => :FEM_FIDAGRMNTS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_FIDAGRMNTS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_FIDAGRMNTS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_FIDAGRMNTS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_FIDAGRMNTS_UL" ENABLE;
