--------------------------------------------------------
--  DDL for Trigger FEM_CURRTYPES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CURRTYPES_UL" 
instead of update on FEM_CURRTYPES_VL
referencing new as FEM_CURRTYPES_B
for each row
begin
  FEM_CURRTYPES_PKG.UPDATE_ROW(
    X_CURRENCY_TYPE_CODE => :FEM_CURRTYPES_B.CURRENCY_TYPE_CODE,
    X_ENABLED_FLAG => :FEM_CURRTYPES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_CURRTYPES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_CURRTYPES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_CURRTYPES_B.OBJECT_VERSION_NUMBER,
    X_CURRENCY_TYPE_NAME => :FEM_CURRTYPES_B.CURRENCY_TYPE_NAME,
    X_DESCRIPTION => :FEM_CURRTYPES_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_CURRTYPES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_CURRTYPES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_CURRTYPES_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CURRTYPES_UL" ENABLE;
