--------------------------------------------------------
--  DDL for Trigger FEM_BAL_SHEET_MODELS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_BAL_SHEET_MODELS_UL" 
instead of update on FEM_BAL_SHEET_MODELS_VL
referencing new as FEM_BAL_SHEET_MODELS_B
for each row
begin
  FEM_BAL_SHEET_MODELS_PKG.UPDATE_ROW(
    X_BAL_SHEET_MODEL_CODE => :FEM_BAL_SHEET_MODELS_B.BAL_SHEET_MODEL_CODE,
    X_BAL_SHEET_CALC_TYPE_CODE => :FEM_BAL_SHEET_MODELS_B.BAL_SHEET_CALC_TYPE_CODE,
    X_BAL_SHEET_DEF_TYPE_CODE => :FEM_BAL_SHEET_MODELS_B.BAL_SHEET_DEF_TYPE_CODE,
    X_ENABLED_FLAG => :FEM_BAL_SHEET_MODELS_B.ENABLED_FLAG,
    X_READ_ONLY_FLAG => :FEM_BAL_SHEET_MODELS_B.READ_ONLY_FLAG,
    X_PERSONAL_FLAG => :FEM_BAL_SHEET_MODELS_B.PERSONAL_FLAG,
    X_BAL_SHEET_MODEL_NAME => :FEM_BAL_SHEET_MODELS_B.BAL_SHEET_MODEL_NAME,
    X_DESCRIPTION => :FEM_BAL_SHEET_MODELS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_BAL_SHEET_MODELS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_BAL_SHEET_MODELS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_BAL_SHEET_MODELS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_BAL_SHEET_MODELS_UL" ENABLE;
