--------------------------------------------------------
--  DDL for Trigger FEM_ACCDH_INSCO_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_ACCDH_INSCO_IL" 
instead of insert on FEM_ACCDH_INSCO_VL
referencing new as FEM_ACCDH_INSCO_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_ACCDH_INSCO_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_ACCID_HEALTH_INS_CO_CODE => :FEM_ACCDH_INSCO_B.ACCID_HEALTH_INS_CO_CODE,
    X_ENABLED_FLAG => :FEM_ACCDH_INSCO_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_ACCDH_INSCO_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_ACCDH_INSCO_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_ACCDH_INSCO_B.OBJECT_VERSION_NUMBER,
    X_ACCID_HEALTH_INS_CO_NAME => :FEM_ACCDH_INSCO_B.ACCID_HEALTH_INS_CO_NAME,
    X_DESCRIPTION => :FEM_ACCDH_INSCO_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_ACCDH_INSCO_B.CREATION_DATE,
    X_CREATED_BY => :FEM_ACCDH_INSCO_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_ACCDH_INSCO_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_ACCDH_INSCO_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_ACCDH_INSCO_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_ACCDH_INSCO_IL" ENABLE;
