--------------------------------------------------------
--  DDL for Trigger FEM_PRTFBAL_TYP_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PRTFBAL_TYP_UL" 
instead of update on FEM_PRTFBAL_TYP_VL
referencing new as FEM_PRTFBAL_TYP_B
for each row
begin
  FEM_PRTFBAL_TYP_PKG.UPDATE_ROW(
    X_PORTF_BAL_TYPE_CODE => :FEM_PRTFBAL_TYP_B.PORTF_BAL_TYPE_CODE,
    X_ENABLED_FLAG => :FEM_PRTFBAL_TYP_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PRTFBAL_TYP_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PRTFBAL_TYP_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PRTFBAL_TYP_B.OBJECT_VERSION_NUMBER,
    X_PORTF_BAL_TYPE_NAME => :FEM_PRTFBAL_TYP_B.PORTF_BAL_TYPE_NAME,
    X_DESCRIPTION => :FEM_PRTFBAL_TYP_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_PRTFBAL_TYP_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PRTFBAL_TYP_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PRTFBAL_TYP_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PRTFBAL_TYP_UL" ENABLE;
