--------------------------------------------------------
--  DDL for Trigger FEM_FIN_ELEM_GROUPS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_FIN_ELEM_GROUPS_UL" 
instead of update on FEM_FIN_ELEM_GROUPS_VL
referencing new as FEM_FIN_ELEM_GROUPS_B
for each row
begin
  FEM_FIN_ELEM_GROUPS_PKG.UPDATE_ROW(
    X_FIN_ELEM_GROUP_CODE => :FEM_FIN_ELEM_GROUPS_B.FIN_ELEM_GROUP_CODE,
    X_READ_ONLY_FLAG => :FEM_FIN_ELEM_GROUPS_B.READ_ONLY_FLAG,
    X_ENABLED_FLAG => :FEM_FIN_ELEM_GROUPS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_FIN_ELEM_GROUPS_B.PERSONAL_FLAG,
    X_FIN_ELEM_GROUP_NAME => :FEM_FIN_ELEM_GROUPS_B.FIN_ELEM_GROUP_NAME,
    X_DESCRIPTION => :FEM_FIN_ELEM_GROUPS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_FIN_ELEM_GROUPS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_FIN_ELEM_GROUPS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_FIN_ELEM_GROUPS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_FIN_ELEM_GROUPS_UL" ENABLE;
