--------------------------------------------------------
--  DDL for Trigger FEM_EDUC_LEVELS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_EDUC_LEVELS_IL" 
instead of insert on FEM_EDUC_LEVELS_VL
referencing new as FEM_EDUC_LEVELS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_EDUC_LEVELS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_EDUCATION_LEVEL_CODE => :FEM_EDUC_LEVELS_B.EDUCATION_LEVEL_CODE,
    X_ENABLED_FLAG => :FEM_EDUC_LEVELS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_EDUC_LEVELS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_EDUC_LEVELS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_EDUC_LEVELS_B.OBJECT_VERSION_NUMBER,
    X_EDUCATION_LEVEL_NAME => :FEM_EDUC_LEVELS_B.EDUCATION_LEVEL_NAME,
    X_DESCRIPTION => :FEM_EDUC_LEVELS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_EDUC_LEVELS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_EDUC_LEVELS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_EDUC_LEVELS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_EDUC_LEVELS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_EDUC_LEVELS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_EDUC_LEVELS_IL" ENABLE;
