--------------------------------------------------------
--  DDL for Trigger FEM_EXCEPTIONS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_EXCEPTIONS_IL" 
instead of insert on FEM_EXCEPTIONS_VL
referencing new as FEM_EXCEPTIONS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_EXCEPTIONS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_EXCEPTION_CODE => :FEM_EXCEPTIONS_B.EXCEPTION_CODE,
    X_ENABLED_FLAG => :FEM_EXCEPTIONS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_EXCEPTIONS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_EXCEPTIONS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_EXCEPTIONS_B.OBJECT_VERSION_NUMBER,
    X_EXCEPTION_NAME => :FEM_EXCEPTIONS_B.EXCEPTION_NAME,
    X_DESCRIPTION => :FEM_EXCEPTIONS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_EXCEPTIONS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_EXCEPTIONS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_EXCEPTIONS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_EXCEPTIONS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_EXCEPTIONS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_EXCEPTIONS_IL" ENABLE;
