--------------------------------------------------------
--  DDL for Trigger FEM_HELD_SALE_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_HELD_SALE_UL" 
instead of update on FEM_HELD_SALE_VL
referencing new as FEM_HELD_SALE_B
for each row
begin
  FEM_HELD_SALE_PKG.UPDATE_ROW(
    X_HELD_FOR_SALE_ID => :FEM_HELD_SALE_B.HELD_FOR_SALE_ID,
    X_HELD_FOR_SALE_DISPLAY_CODE => :FEM_HELD_SALE_B.HELD_FOR_SALE_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_HELD_SALE_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_HELD_SALE_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_HELD_SALE_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_HELD_SALE_B.OBJECT_VERSION_NUMBER,
    X_HELD_FOR_SALE_NAME => :FEM_HELD_SALE_B.HELD_FOR_SALE_NAME,
    X_DESCRIPTION => :FEM_HELD_SALE_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_HELD_SALE_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_HELD_SALE_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_HELD_SALE_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_HELD_SALE_UL" ENABLE;
