--------------------------------------------------------
--  DDL for Trigger FEM_ROLLOVER_FAC_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_ROLLOVER_FAC_IL" 
instead of insert on FEM_ROLLOVER_FAC_VL
referencing new as FEM_ROLLOVER_FAC_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_ROLLOVER_FAC_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_ROLL_FACILITY_ID => :FEM_ROLLOVER_FAC_B.ROLL_FACILITY_ID,
    X_ROLL_FACILITY_DISPLAY_CODE => :FEM_ROLLOVER_FAC_B.ROLL_FACILITY_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_ROLLOVER_FAC_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_ROLLOVER_FAC_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_ROLLOVER_FAC_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_ROLLOVER_FAC_B.OBJECT_VERSION_NUMBER,
    X_ROLL_FACILITY_NAME => :FEM_ROLLOVER_FAC_B.ROLL_FACILITY_NAME,
    X_DESCRIPTION => :FEM_ROLLOVER_FAC_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_ROLLOVER_FAC_B.CREATION_DATE,
    X_CREATED_BY => :FEM_ROLLOVER_FAC_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_ROLLOVER_FAC_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_ROLLOVER_FAC_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_ROLLOVER_FAC_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_ROLLOVER_FAC_IL" ENABLE;
