--------------------------------------------------------
--  DDL for Trigger FEM_APPLICATION_GROUPS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_APPLICATION_GROUPS_IL" 
instead of insert on FEM_APPLICATION_GROUPS_VL
referencing new as APPLICATION_GROUP
for each row
declare
  row_id rowid;
 ---
begin
  FEM_APPLICATION_GROUPS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_APPLICATION_GROUP_ID => :APPLICATION_GROUP.APPLICATION_GROUP_ID,
    X_APPLICATION_GROUP_NAME => :APPLICATION_GROUP.APPLICATION_GROUP_NAME,
    X_DESCRIPTION => :APPLICATION_GROUP.DESCRIPTION,
    X_CREATION_DATE => :APPLICATION_GROUP.CREATION_DATE,
    X_CREATED_BY => :APPLICATION_GROUP.CREATED_BY,
    X_LAST_UPDATE_DATE => :APPLICATION_GROUP.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :APPLICATION_GROUP.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :APPLICATION_GROUP.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_APPLICATION_GROUPS_IL" ENABLE;
