--------------------------------------------------------
--  DDL for Trigger FEM_FUNDSTATUS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_FUNDSTATUS_UL" 
instead of update on FEM_FUNDSTATUS_VL
referencing new as FEM_FUNDSTATUS_B
for each row
begin
  FEM_FUNDSTATUS_PKG.UPDATE_ROW(
    X_FUNDING_STATUS_CODE => :FEM_FUNDSTATUS_B.FUNDING_STATUS_CODE,
    X_ENABLED_FLAG => :FEM_FUNDSTATUS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_FUNDSTATUS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_FUNDSTATUS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_FUNDSTATUS_B.OBJECT_VERSION_NUMBER,
    X_FUNDING_STATUS_NAME => :FEM_FUNDSTATUS_B.FUNDING_STATUS_NAME,
    X_DESCRIPTION => :FEM_FUNDSTATUS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_FUNDSTATUS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_FUNDSTATUS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_FUNDSTATUS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_FUNDSTATUS_UL" ENABLE;
