--------------------------------------------------------
--  DDL for Trigger FEM_ABVISBCODES_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_ABVISBCODES_IL" 
instead of insert on FEM_ABVISBCODES_VL
referencing new as FEM_ABVISBCODES_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_ABVISBCODES_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_AB_VISIBILITY_CODE => :FEM_ABVISBCODES_B.AB_VISIBILITY_CODE,
    X_ENABLED_FLAG => :FEM_ABVISBCODES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_ABVISBCODES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_ABVISBCODES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_ABVISBCODES_B.OBJECT_VERSION_NUMBER,
    X_AB_VISIBILITY_NAME => :FEM_ABVISBCODES_B.AB_VISIBILITY_NAME,
    X_DESCRIPTION => :FEM_ABVISBCODES_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_ABVISBCODES_B.CREATION_DATE,
    X_CREATED_BY => :FEM_ABVISBCODES_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_ABVISBCODES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_ABVISBCODES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_ABVISBCODES_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_ABVISBCODES_IL" ENABLE;
