--------------------------------------------------------
--  DDL for Trigger FEM_PLANS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PLANS_UL" 
instead of update on FEM_PLANS_VL
referencing new as FEM_PLANS_B
for each row
begin
  FEM_PLANS_PKG.UPDATE_ROW(
    X_PLAN_CODE => :FEM_PLANS_B.PLAN_CODE,
    X_ENABLED_FLAG => :FEM_PLANS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PLANS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PLANS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PLANS_B.OBJECT_VERSION_NUMBER,
    X_PLAN_NAME => :FEM_PLANS_B.PLAN_NAME,
    X_DESCRIPTION => :FEM_PLANS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_PLANS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PLANS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PLANS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PLANS_UL" ENABLE;
