--------------------------------------------------------
--  DDL for Trigger FEM_BRANCHES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_BRANCHES_UL" 
instead of update on FEM_BRANCHES_VL
referencing new as FEM_BRANCHES_B
for each row
begin
  FEM_BRANCHES_PKG.UPDATE_ROW(
    X_BRANCH_CODE => :FEM_BRANCHES_B.BRANCH_CODE,
    X_ENABLED_FLAG => :FEM_BRANCHES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_BRANCHES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_BRANCHES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_BRANCHES_B.OBJECT_VERSION_NUMBER,
    X_BRANCH_NAME => :FEM_BRANCHES_B.BRANCH_NAME,
    X_DESCRIPTION => :FEM_BRANCHES_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_BRANCHES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_BRANCHES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_BRANCHES_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_BRANCHES_UL" ENABLE;
