--------------------------------------------------------
--  DDL for Trigger FEM_LIEN_POS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_LIEN_POS_IL" 
instead of insert on FEM_LIEN_POS_VL
referencing new as FEM_LIEN_POS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_LIEN_POS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_LIEN_POSITION_ID => :FEM_LIEN_POS_B.LIEN_POSITION_ID,
    X_LIEN_POSITION_DISPLAY_CODE => :FEM_LIEN_POS_B.LIEN_POSITION_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_LIEN_POS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_LIEN_POS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_LIEN_POS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_LIEN_POS_B.OBJECT_VERSION_NUMBER,
    X_LIEN_POSITION_NAME => :FEM_LIEN_POS_B.LIEN_POSITION_NAME,
    X_DESCRIPTION => :FEM_LIEN_POS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_LIEN_POS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_LIEN_POS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_LIEN_POS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_LIEN_POS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_LIEN_POS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_LIEN_POS_IL" ENABLE;
