--------------------------------------------------------
--  DDL for Trigger FEM_OCCUPATIONS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_OCCUPATIONS_IL" 
instead of insert on FEM_OCCUPATIONS_VL
referencing new as FEM_OCCUPATIONS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_OCCUPATIONS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_OCCUPATION_CODE => :FEM_OCCUPATIONS_B.OCCUPATION_CODE,
    X_ENABLED_FLAG => :FEM_OCCUPATIONS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_OCCUPATIONS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_OCCUPATIONS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_OCCUPATIONS_B.OBJECT_VERSION_NUMBER,
    X_OCCUPATION_NAME => :FEM_OCCUPATIONS_B.OCCUPATION_NAME,
    X_DESCRIPTION => :FEM_OCCUPATIONS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_OCCUPATIONS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_OCCUPATIONS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_OCCUPATIONS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_OCCUPATIONS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_OCCUPATIONS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_OCCUPATIONS_IL" ENABLE;
