--------------------------------------------------------
--  DDL for Trigger FEM_MAP_RULE_TYPES_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_MAP_RULE_TYPES_IL" 
instead of insert on FEM_MAP_RULE_TYPES_VL
referencing new as FEM_MAP_RULE_TYPES_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_MAP_RULE_TYPES_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_MAP_RULE_TYPE_CODE => :FEM_MAP_RULE_TYPES_B.MAP_RULE_TYPE_CODE,
    X_ENABLED_FLAG => :FEM_MAP_RULE_TYPES_B.ENABLED_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_MAP_RULE_TYPES_B.OBJECT_VERSION_NUMBER,
    X_MAP_RULE_TYPE_NAME => :FEM_MAP_RULE_TYPES_B.MAP_RULE_TYPE_NAME,
    X_DESCRIPTION => :FEM_MAP_RULE_TYPES_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_MAP_RULE_TYPES_B.CREATION_DATE,
    X_CREATED_BY => :FEM_MAP_RULE_TYPES_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_MAP_RULE_TYPES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_MAP_RULE_TYPES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_MAP_RULE_TYPES_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---

/
ALTER TRIGGER "APPS"."FEM_MAP_RULE_TYPES_IL" ENABLE;
