--------------------------------------------------------
--  DDL for Trigger FEM_UOM_CODES_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_UOM_CODES_IL" 
instead of insert on FEM_UOM_CODES_VL
referencing new as FEM_UOM_CODES_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_UOM_CODES_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_UOM_CODE => :FEM_UOM_CODES_B.UOM_CODE,
    X_READ_ONLY_FLAG => :FEM_UOM_CODES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_UOM_CODES_B.OBJECT_VERSION_NUMBER,
    X_ENABLED_FLAG => :FEM_UOM_CODES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_UOM_CODES_B.PERSONAL_FLAG,
    X_UOM_NAME => :FEM_UOM_CODES_B.UOM_NAME,
    X_DESCRIPTION => :FEM_UOM_CODES_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_UOM_CODES_B.CREATION_DATE,
    X_CREATED_BY => :FEM_UOM_CODES_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_UOM_CODES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_UOM_CODES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_UOM_CODES_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_UOM_CODES_IL" ENABLE;
