--------------------------------------------------------
--  DDL for Trigger FEM_OCCUPANCIES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_OCCUPANCIES_UL" 
instead of update on FEM_OCCUPANCIES_VL
referencing new as FEM_OCCUPANCIES_B
for each row
begin
  FEM_OCCUPANCIES_PKG.UPDATE_ROW(
    X_OCCUPANCY_ID => :FEM_OCCUPANCIES_B.OCCUPANCY_ID,
    X_OCCUPANCY_DISPLAY_CODE => :FEM_OCCUPANCIES_B.OCCUPANCY_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_OCCUPANCIES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_OCCUPANCIES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_OCCUPANCIES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_OCCUPANCIES_B.OBJECT_VERSION_NUMBER,
    X_OCCUPANCY_NAME => :FEM_OCCUPANCIES_B.OCCUPANCY_NAME,
    X_DESCRIPTION => :FEM_OCCUPANCIES_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_OCCUPANCIES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_OCCUPANCIES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_OCCUPANCIES_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_OCCUPANCIES_UL" ENABLE;
