--------------------------------------------------------
--  DDL for Trigger FEM_TP_METHODS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_TP_METHODS_IL" 
instead of insert on FEM_TP_METHODS_VL
referencing new as FEM_TP_METHODS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_TP_METHODS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_TP_METHOD_CODE => :FEM_TP_METHODS_B.TP_METHOD_CODE,
    X_ENABLED_FLAG => :FEM_TP_METHODS_B.ENABLED_FLAG,
    X_READ_ONLY_FLAG => :FEM_TP_METHODS_B.READ_ONLY_FLAG,
    X_PERSONAL_FLAG => :FEM_TP_METHODS_B.PERSONAL_FLAG,
    X_TP_METHOD_NAME => :FEM_TP_METHODS_B.TP_METHOD_NAME,
    X_DESCRIPTION => :FEM_TP_METHODS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_TP_METHODS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_TP_METHODS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_TP_METHODS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_TP_METHODS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_TP_METHODS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_TP_METHODS_IL" ENABLE;
