--------------------------------------------------------
--  DDL for Trigger FEM_OVRDRFT_PRT_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_OVRDRFT_PRT_IL" 
instead of insert on FEM_OVRDRFT_PRT_VL
referencing new as FEM_OVRDRFT_PRT_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_OVRDRFT_PRT_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_OD_PROTECTION_ID => :FEM_OVRDRFT_PRT_B.OD_PROTECTION_ID,
    X_OD_PROTECTION_DISPLAY_CODE => :FEM_OVRDRFT_PRT_B.OD_PROTECTION_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_OVRDRFT_PRT_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_OVRDRFT_PRT_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_OVRDRFT_PRT_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_OVRDRFT_PRT_B.OBJECT_VERSION_NUMBER,
    X_OD_PROTECTION_NAME => :FEM_OVRDRFT_PRT_B.OD_PROTECTION_NAME,
    X_DESCRIPTION => :FEM_OVRDRFT_PRT_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_OVRDRFT_PRT_B.CREATION_DATE,
    X_CREATED_BY => :FEM_OVRDRFT_PRT_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_OVRDRFT_PRT_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_OVRDRFT_PRT_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_OVRDRFT_PRT_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_OVRDRFT_PRT_IL" ENABLE;
