--------------------------------------------------------
--  DDL for Trigger FEM_MRGN_AGRMNTS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_MRGN_AGRMNTS_UL" 
instead of update on FEM_MRGN_AGRMNTS_VL
referencing new as FEM_MRGN_AGRMNTS_B
for each row
begin
  FEM_MRGN_AGRMNTS_PKG.UPDATE_ROW(
    X_MARGIN_AGREEMENT_CODE => :FEM_MRGN_AGRMNTS_B.MARGIN_AGREEMENT_CODE,
    X_ENABLED_FLAG => :FEM_MRGN_AGRMNTS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_MRGN_AGRMNTS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_MRGN_AGRMNTS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_MRGN_AGRMNTS_B.OBJECT_VERSION_NUMBER,
    X_MARGIN_AGREEMENT_NAME => :FEM_MRGN_AGRMNTS_B.MARGIN_AGREEMENT_NAME,
    X_DESCRIPTION => :FEM_MRGN_AGRMNTS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_MRGN_AGRMNTS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_MRGN_AGRMNTS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_MRGN_AGRMNTS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_MRGN_AGRMNTS_UL" ENABLE;
