--------------------------------------------------------
--  DDL for Trigger FEM_ANNUAL_FEES_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_ANNUAL_FEES_IL" 
instead of insert on FEM_ANNUAL_FEES_VL
referencing new as FEM_ANNUAL_FEES_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_ANNUAL_FEES_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_ANNUAL_FEE_CODE => :FEM_ANNUAL_FEES_B.ANNUAL_FEE_CODE,
    X_OBJECT_VERSION_NUMBER => :FEM_ANNUAL_FEES_B.OBJECT_VERSION_NUMBER,
    X_ENABLED_FLAG => :FEM_ANNUAL_FEES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_ANNUAL_FEES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_ANNUAL_FEES_B.READ_ONLY_FLAG,
    X_ANNUAL_FEE_NAME => :FEM_ANNUAL_FEES_B.ANNUAL_FEE_NAME,
    X_DESCRIPTION => :FEM_ANNUAL_FEES_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_ANNUAL_FEES_B.CREATION_DATE,
    X_CREATED_BY => :FEM_ANNUAL_FEES_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_ANNUAL_FEES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_ANNUAL_FEES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_ANNUAL_FEES_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_ANNUAL_FEES_IL" ENABLE;
