--------------------------------------------------------
--  DDL for Trigger FEM_AGENCY_BNKS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_AGENCY_BNKS_IL" 
instead of insert on FEM_AGENCY_BNKS_VL
referencing new as FEM_AGENCY_BNKS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_AGENCY_BNKS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_AGENT_BANK_CODE => :FEM_AGENCY_BNKS_B.AGENT_BANK_CODE,
    X_ENABLED_FLAG => :FEM_AGENCY_BNKS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_AGENCY_BNKS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_AGENCY_BNKS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_AGENCY_BNKS_B.OBJECT_VERSION_NUMBER,
    X_AGENT_BANK_NAME => :FEM_AGENCY_BNKS_B.AGENT_BANK_NAME,
    X_DESCRIPTION => :FEM_AGENCY_BNKS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_AGENCY_BNKS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_AGENCY_BNKS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_AGENCY_BNKS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_AGENCY_BNKS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_AGENCY_BNKS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_AGENCY_BNKS_IL" ENABLE;
