--------------------------------------------------------
--  DDL for Trigger FEM_TAB_COLUMNS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_TAB_COLUMNS_UL" 
instead of update on FEM_TAB_COLUMNS_VL
referencing new as FEM_TAB_COLUMNS_B
for each row
begin
  FEM_TAB_COLUMNS_PKG.UPDATE_ROW(
    X_TABLE_NAME => :FEM_TAB_COLUMNS_B.TABLE_NAME,
    X_COLUMN_NAME => :FEM_TAB_COLUMNS_B.COLUMN_NAME,
    X_ENABLED_FLAG => :FEM_TAB_COLUMNS_B.ENABLED_FLAG,
    X_INTERFACE_COLUMN_NAME => :FEM_TAB_COLUMNS_B.INTERFACE_COLUMN_NAME,
    X_FEM_DATA_TYPE_CODE => :FEM_TAB_COLUMNS_B.FEM_DATA_TYPE_CODE,
    X_DIMENSION_ID => :FEM_TAB_COLUMNS_B.DIMENSION_ID,
    X_UOM_COLUMN_NAME => :FEM_TAB_COLUMNS_B.UOM_COLUMN_NAME,
    X_OBJECT_VERSION_NUMBER => :FEM_TAB_COLUMNS_B.OBJECT_VERSION_NUMBER,
    X_DISPLAY_NAME => :FEM_TAB_COLUMNS_B.DISPLAY_NAME,
    X_DESCRIPTION => :FEM_TAB_COLUMNS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_TAB_COLUMNS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_TAB_COLUMNS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_TAB_COLUMNS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_TAB_COLUMNS_UL" ENABLE;
