--------------------------------------------------------
--  DDL for Trigger FEM_ACCRUAL_BASIS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_ACCRUAL_BASIS_UL" 
instead of update on FEM_ACCRUAL_BASIS_VL
referencing new as FEM_ACCRUAL_BASIS_B
for each row
begin
  FEM_ACCRUAL_BASIS_PKG.UPDATE_ROW(
    X_ACCRUAL_BASIS_ID => :FEM_ACCRUAL_BASIS_B.ACCRUAL_BASIS_ID,
    X_ACCRUAL_BASIS_DISPLAY_CODE => :FEM_ACCRUAL_BASIS_B.ACCRUAL_BASIS_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_ACCRUAL_BASIS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_ACCRUAL_BASIS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_ACCRUAL_BASIS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_ACCRUAL_BASIS_B.OBJECT_VERSION_NUMBER,
    X_ACCRUAL_BASIS_NAME => :FEM_ACCRUAL_BASIS_B.ACCRUAL_BASIS_NAME,
    X_DESCRIPTION => :FEM_ACCRUAL_BASIS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_ACCRUAL_BASIS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_ACCRUAL_BASIS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_ACCRUAL_BASIS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_ACCRUAL_BASIS_UL" ENABLE;
