--------------------------------------------------------
--  DDL for Trigger FEM_CUSTOMERS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CUSTOMERS_IL" 
instead of insert on FEM_CUSTOMERS_VL
referencing new as FEM_CUSTOMERS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_CUSTOMERS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_CUSTOMER_ID => :FEM_CUSTOMERS_B.CUSTOMER_ID,
    X_VALUE_SET_ID => :FEM_CUSTOMERS_B.VALUE_SET_ID,
    X_OBJECT_VERSION_NUMBER => :FEM_CUSTOMERS_B.OBJECT_VERSION_NUMBER,
    X_READ_ONLY_FLAG => :FEM_CUSTOMERS_B.READ_ONLY_FLAG,
    X_DIMENSION_GROUP_ID => :FEM_CUSTOMERS_B.DIMENSION_GROUP_ID,
    X_CUSTOMER_DISPLAY_CODE => :FEM_CUSTOMERS_B.CUSTOMER_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_CUSTOMERS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_CUSTOMERS_B.PERSONAL_FLAG,
    X_CUSTOMER_NAME => :FEM_CUSTOMERS_B.CUSTOMER_NAME,
    X_DESCRIPTION => :FEM_CUSTOMERS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_CUSTOMERS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_CUSTOMERS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_CUSTOMERS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_CUSTOMERS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_CUSTOMERS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CUSTOMERS_IL" ENABLE;
