--------------------------------------------------------
--  DDL for Trigger FEM_PURPOSES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PURPOSES_UL" 
instead of update on FEM_PURPOSES_VL
referencing new as FEM_PURPOSES_B
for each row
begin
  FEM_PURPOSES_PKG.UPDATE_ROW(
    X_PURPOSE_ID => :FEM_PURPOSES_B.PURPOSE_ID,
    X_PURPOSE_DISPLAY_CODE => :FEM_PURPOSES_B.PURPOSE_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_PURPOSES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PURPOSES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PURPOSES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PURPOSES_B.OBJECT_VERSION_NUMBER,
    X_PURPOSE_NAME => :FEM_PURPOSES_B.PURPOSE_NAME,
    X_DESCRIPTION => :FEM_PURPOSES_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_PURPOSES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PURPOSES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PURPOSES_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PURPOSES_UL" ENABLE;
