--------------------------------------------------------
--  DDL for Trigger FEM_COST_CENTERS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_COST_CENTERS_IL" 
instead of insert on FEM_COST_CENTERS_VL
referencing new as FEM_COST_CENTERS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_COST_CENTERS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_COST_CENTER_ID => :FEM_COST_CENTERS_B.COST_CENTER_ID,
    X_VALUE_SET_ID => :FEM_COST_CENTERS_B.VALUE_SET_ID,
    X_DIMENSION_GROUP_ID => :FEM_COST_CENTERS_B.DIMENSION_GROUP_ID,
    X_COST_CENTER_DISPLAY_CODE => :FEM_COST_CENTERS_B.COST_CENTER_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_COST_CENTERS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_COST_CENTERS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_COST_CENTERS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_COST_CENTERS_B.OBJECT_VERSION_NUMBER,
    X_COST_CENTER_NAME => :FEM_COST_CENTERS_B.COST_CENTER_NAME,
    X_DESCRIPTION => :FEM_COST_CENTERS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_COST_CENTERS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_COST_CENTERS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_COST_CENTERS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_COST_CENTERS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_COST_CENTERS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_COST_CENTERS_IL" ENABLE;
