--------------------------------------------------------
--  DDL for Trigger FEM_CENSUS_CNTY_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CENSUS_CNTY_IL" 
instead of insert on FEM_CENSUS_CNTY_VL
referencing new as FEM_CENSUS_CNTY_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_CENSUS_CNTY_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_CENSUS_COUNTY_CODE => :FEM_CENSUS_CNTY_B.CENSUS_COUNTY_CODE,
    X_ENABLED_FLAG => :FEM_CENSUS_CNTY_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_CENSUS_CNTY_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_CENSUS_CNTY_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_CENSUS_CNTY_B.OBJECT_VERSION_NUMBER,
    X_CENSUS_COUNTY_NAME => :FEM_CENSUS_CNTY_B.CENSUS_COUNTY_NAME,
    X_DESCRIPTION => :FEM_CENSUS_CNTY_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_CENSUS_CNTY_B.CREATION_DATE,
    X_CREATED_BY => :FEM_CENSUS_CNTY_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_CENSUS_CNTY_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_CENSUS_CNTY_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_CENSUS_CNTY_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CENSUS_CNTY_IL" ENABLE;
