--------------------------------------------------------
--  DDL for Trigger FEM_RECMETHODS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_RECMETHODS_UL" 
instead of update on FEM_RECMETHODS_VL
referencing new as FEM_RECMETHODS_B
for each row
begin
  FEM_RECMETHODS_PKG.UPDATE_ROW(
    X_RECOVERY_METHOD_CODE => :FEM_RECMETHODS_B.RECOVERY_METHOD_CODE,
    X_ENABLED_FLAG => :FEM_RECMETHODS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_RECMETHODS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_RECMETHODS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_RECMETHODS_B.OBJECT_VERSION_NUMBER,
    X_RECOVERY_METHOD_NAME => :FEM_RECMETHODS_B.RECOVERY_METHOD_NAME,
    X_DESCRIPTION => :FEM_RECMETHODS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_RECMETHODS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_RECMETHODS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_RECMETHODS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_RECMETHODS_UL" ENABLE;
