--------------------------------------------------------
--  DDL for Trigger FEM_APPOVR_RSN_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_APPOVR_RSN_UL" 
instead of update on FEM_APPOVR_RSN_VL
referencing new as FEM_APPOVR_RSN_B
for each row
begin
  FEM_APPOVR_RSN_PKG.UPDATE_ROW(
    X_APPL_OVERRIDE_REASON_CODE => :FEM_APPOVR_RSN_B.APPL_OVERRIDE_REASON_CODE,
    X_ENABLED_FLAG => :FEM_APPOVR_RSN_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_APPOVR_RSN_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_APPOVR_RSN_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_APPOVR_RSN_B.OBJECT_VERSION_NUMBER,
    X_APPL_OVERRIDE_REASON_NAME => :FEM_APPOVR_RSN_B.APPL_OVERRIDE_REASON_NAME,
    X_DESCRIPTION => :FEM_APPOVR_RSN_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_APPOVR_RSN_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_APPOVR_RSN_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_APPOVR_RSN_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_APPOVR_RSN_UL" ENABLE;
