--------------------------------------------------------
--  DDL for Trigger FEM_BRANCHES_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_BRANCHES_IL" 
instead of insert on FEM_BRANCHES_VL
referencing new as FEM_BRANCHES_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_BRANCHES_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_BRANCH_CODE => :FEM_BRANCHES_B.BRANCH_CODE,
    X_ENABLED_FLAG => :FEM_BRANCHES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_BRANCHES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_BRANCHES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_BRANCHES_B.OBJECT_VERSION_NUMBER,
    X_BRANCH_NAME => :FEM_BRANCHES_B.BRANCH_NAME,
    X_DESCRIPTION => :FEM_BRANCHES_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_BRANCHES_B.CREATION_DATE,
    X_CREATED_BY => :FEM_BRANCHES_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_BRANCHES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_BRANCHES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_BRANCHES_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_BRANCHES_IL" ENABLE;
