--------------------------------------------------------
--  DDL for Trigger FEM_SOURCE_SYSTEMS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_SOURCE_SYSTEMS_IL" 
instead of insert on FEM_SOURCE_SYSTEMS_VL
referencing new as FEM_SOURCE_SYSTEMS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_SOURCE_SYSTEMS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_SOURCE_SYSTEM_CODE => :FEM_SOURCE_SYSTEMS_B.SOURCE_SYSTEM_CODE,
    X_SOURCE_SYSTEM_DISPLAY_CODE => :FEM_SOURCE_SYSTEMS_B.SOURCE_SYSTEM_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_SOURCE_SYSTEMS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_SOURCE_SYSTEMS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_SOURCE_SYSTEMS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_SOURCE_SYSTEMS_B.OBJECT_VERSION_NUMBER,
    X_SOURCE_SYSTEM_NAME => :FEM_SOURCE_SYSTEMS_B.SOURCE_SYSTEM_NAME,
    X_DESCRIPTION => :FEM_SOURCE_SYSTEMS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_SOURCE_SYSTEMS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_SOURCE_SYSTEMS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_SOURCE_SYSTEMS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_SOURCE_SYSTEMS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_SOURCE_SYSTEMS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_SOURCE_SYSTEMS_IL" ENABLE;
