--------------------------------------------------------
--  DDL for Trigger FEM_DIMENSION_GRPS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_DIMENSION_GRPS_IL" 
instead of insert on FEM_DIMENSION_GRPS_VL
referencing new as DIMENSION_GROUP
for each row
declare
  row_id rowid;
 ---
begin
  FEM_DIMENSION_GRPS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_DIMENSION_GROUP_ID => :DIMENSION_GROUP.DIMENSION_GROUP_ID,
    X_TIME_DIMENSION_GROUP_KEY => :DIMENSION_GROUP.TIME_DIMENSION_GROUP_KEY,
    X_DIMENSION_ID => :DIMENSION_GROUP.DIMENSION_ID,
    X_DIMENSION_GROUP_SEQ => :DIMENSION_GROUP.DIMENSION_GROUP_SEQ,
    X_TIME_GROUP_TYPE_CODE => :DIMENSION_GROUP.TIME_GROUP_TYPE_CODE,
    X_READ_ONLY_FLAG => :DIMENSION_GROUP.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :DIMENSION_GROUP.OBJECT_VERSION_NUMBER,
    X_PERSONAL_FLAG => :DIMENSION_GROUP.PERSONAL_FLAG,
    X_ENABLED_FLAG => :DIMENSION_GROUP.ENABLED_FLAG,
    X_DIMENSION_GROUP_DISPLAY_CODE => :DIMENSION_GROUP.DIMENSION_GROUP_DISPLAY_CODE,
    X_DIMENSION_GROUP_NAME => :DIMENSION_GROUP.DIMENSION_GROUP_NAME,
    X_DESCRIPTION => :DIMENSION_GROUP.DESCRIPTION,
    X_CREATION_DATE => :DIMENSION_GROUP.CREATION_DATE,
    X_CREATED_BY => :DIMENSION_GROUP.CREATED_BY,
    X_LAST_UPDATE_DATE => :DIMENSION_GROUP.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :DIMENSION_GROUP.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :DIMENSION_GROUP.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_DIMENSION_GRPS_IL" ENABLE;
