--------------------------------------------------------
--  DDL for Trigger FEM_BUDG_STATUS_CODES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_BUDG_STATUS_CODES_UL" 
instead of update on FEM_BUDG_STATUS_CODES_VL
referencing new as FEM_BUDG_STATUS_CODES_B
for each row
begin
  FEM_BUDG_STATUS_CODES_PKG.UPDATE_ROW(
    X_BUDGET_STATUS_CODE => :FEM_BUDG_STATUS_CODES_B.BUDGET_STATUS_CODE,
    X_PERSONAL_FLAG => :FEM_BUDG_STATUS_CODES_B.PERSONAL_FLAG,
    X_ENABLED_FLAG => :FEM_BUDG_STATUS_CODES_B.ENABLED_FLAG,
    X_READ_ONLY_FLAG => :FEM_BUDG_STATUS_CODES_B.READ_ONLY_FLAG,
    X_BUDGET_STATUS_NAME => :FEM_BUDG_STATUS_CODES_B.BUDGET_STATUS_NAME,
    X_DESCRIPTION => :FEM_BUDG_STATUS_CODES_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_BUDG_STATUS_CODES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_BUDG_STATUS_CODES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_BUDG_STATUS_CODES_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_BUDG_STATUS_CODES_UL" ENABLE;
