--------------------------------------------------------
--  DDL for Trigger FEM_GEOGRAPHY_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_GEOGRAPHY_IL" 
instead of insert on FEM_GEOGRAPHY_VL
referencing new as FEM_GEOGRAPHY_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_GEOGRAPHY_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_GEOGRAPHY_ID => :FEM_GEOGRAPHY_B.GEOGRAPHY_ID,
    X_VALUE_SET_ID => :FEM_GEOGRAPHY_B.VALUE_SET_ID,
    X_DIMENSION_GROUP_ID => :FEM_GEOGRAPHY_B.DIMENSION_GROUP_ID,
    X_GEOGRAPHY_DISPLAY_CODE => :FEM_GEOGRAPHY_B.GEOGRAPHY_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_GEOGRAPHY_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_GEOGRAPHY_B.PERSONAL_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_GEOGRAPHY_B.OBJECT_VERSION_NUMBER,
    X_READ_ONLY_FLAG => :FEM_GEOGRAPHY_B.READ_ONLY_FLAG,
    X_GEOGRAPHY_NAME => :FEM_GEOGRAPHY_B.GEOGRAPHY_NAME,
    X_DESCRIPTION => :FEM_GEOGRAPHY_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_GEOGRAPHY_B.CREATION_DATE,
    X_CREATED_BY => :FEM_GEOGRAPHY_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_GEOGRAPHY_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_GEOGRAPHY_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_GEOGRAPHY_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_GEOGRAPHY_IL" ENABLE;
