--------------------------------------------------------
--  DDL for Trigger FEM_COLUMN_REQUIREMNT_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_COLUMN_REQUIREMNT_IL" 
instead of insert on FEM_COLUMN_REQUIREMNT_VL
referencing new as FEM_COLUMN_REQUIREMNT_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_COLUMN_REQUIREMNT_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_COLUMN_NAME => :FEM_COLUMN_REQUIREMNT_B.COLUMN_NAME,
    X_OBJECT_VERSION_NUMBER => :FEM_COLUMN_REQUIREMNT_B.OBJECT_VERSION_NUMBER,
    X_ACTIVITY_DIM_COMPONENT_FLAG => :FEM_COLUMN_REQUIREMNT_B.ACTIVITY_DIM_COMPONENT_FLAG,
    X_COST_OBJ_DIM_REQUIREMENT_COD => :FEM_COLUMN_REQUIREMNT_B.COST_OBJ_DIM_REQUIREMENT_CODE,
    X_COST_OBJ_DIM_COMPONENT_FLAG => :FEM_COLUMN_REQUIREMNT_B.COST_OBJ_DIM_COMPONENT_FLAG,
    X_DATA_LENGTH => :FEM_COLUMN_REQUIREMNT_B.DATA_LENGTH,
    X_DATA_SCALE => :FEM_COLUMN_REQUIREMNT_B.DATA_SCALE,
    X_DATA_PRECISION => :FEM_COLUMN_REQUIREMNT_B.DATA_PRECISION,
    X_UOM_COLUMN_NAME => :FEM_COLUMN_REQUIREMNT_B.UOM_COLUMN_NAME,
    X_DIMENSION_ID => :FEM_COLUMN_REQUIREMNT_B.DIMENSION_ID,
    X_FEM_DATA_TYPE_CODE => :FEM_COLUMN_REQUIREMNT_B.FEM_DATA_TYPE_CODE,
    X_DATA_TYPE => :FEM_COLUMN_REQUIREMNT_B.DATA_TYPE,
    X_PROCESS_KEY_CANDIDATE_FLG => :FEM_COLUMN_REQUIREMNT_B.PROCESS_KEY_CANDIDATE_FLG,
    X_PROCESS_KEY_COL_ID => :FEM_COLUMN_REQUIREMNT_B.PROCESS_KEY_COL_ID,
    X_DISPLAY_SEQ => :FEM_COLUMN_REQUIREMNT_B.DISPLAY_SEQ,
    X_RESTRICTED_FLAG => :FEM_COLUMN_REQUIREMNT_B.RESTRICTED_FLAG,
    X_ACTIVITY_DIM_REQUIREMENT_COD => :FEM_COLUMN_REQUIREMNT_B.ACTIVITY_DIM_REQUIREMENT_CODE,
    X_DISPLAY_NAME => :FEM_COLUMN_REQUIREMNT_B.DISPLAY_NAME,
    X_DESCRIPTION => :FEM_COLUMN_REQUIREMNT_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_COLUMN_REQUIREMNT_B.CREATION_DATE,
    X_CREATED_BY => :FEM_COLUMN_REQUIREMNT_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_COLUMN_REQUIREMNT_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_COLUMN_REQUIREMNT_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_COLUMN_REQUIREMNT_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_COLUMN_REQUIREMNT_IL" ENABLE;
