--------------------------------------------------------
--  DDL for Trigger FEM_CREDIT_RATINGS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CREDIT_RATINGS_IL" 
instead of insert on FEM_CREDIT_RATINGS_VL
referencing new as FEM_CREDIT_RATINGS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_CREDIT_RATINGS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_CREDIT_RATING_ID => :FEM_CREDIT_RATINGS_B.CREDIT_RATING_ID,
    X_CREDIT_RATING_DISPLAY_CODE => :FEM_CREDIT_RATINGS_B.CREDIT_RATING_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_CREDIT_RATINGS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_CREDIT_RATINGS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_CREDIT_RATINGS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_CREDIT_RATINGS_B.OBJECT_VERSION_NUMBER,
    X_CREDIT_RATING_NAME => :FEM_CREDIT_RATINGS_B.CREDIT_RATING_NAME,
    X_DESCRIPTION => :FEM_CREDIT_RATINGS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_CREDIT_RATINGS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_CREDIT_RATINGS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_CREDIT_RATINGS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_CREDIT_RATINGS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_CREDIT_RATINGS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CREDIT_RATINGS_IL" ENABLE;
