--------------------------------------------------------
--  DDL for Trigger FEM_PAYMNT_HIST_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PAYMNT_HIST_IL" 
instead of insert on FEM_PAYMNT_HIST_VL
referencing new as FEM_PAYMNT_HIST_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_PAYMNT_HIST_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_PAYMENT_HISTORY_CODE => :FEM_PAYMNT_HIST_B.PAYMENT_HISTORY_CODE,
    X_ENABLED_FLAG => :FEM_PAYMNT_HIST_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PAYMNT_HIST_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PAYMNT_HIST_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PAYMNT_HIST_B.OBJECT_VERSION_NUMBER,
    X_PAYMENT_HISTORY_NAME => :FEM_PAYMNT_HIST_B.PAYMENT_HISTORY_NAME,
    X_DESCRIPTION => :FEM_PAYMNT_HIST_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_PAYMNT_HIST_B.CREATION_DATE,
    X_CREATED_BY => :FEM_PAYMNT_HIST_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_PAYMNT_HIST_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PAYMNT_HIST_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PAYMNT_HIST_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PAYMNT_HIST_IL" ENABLE;
