--------------------------------------------------------
--  DDL for Trigger FEM_DIR_INDIRECT_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_DIR_INDIRECT_UL" 
instead of update on FEM_DIR_INDIRECT_VL
referencing new as FEM_DIR_INDIRECT_B
for each row
begin
  FEM_DIR_INDIRECT_PKG.UPDATE_ROW(
    X_DIRECT_IND_ID => :FEM_DIR_INDIRECT_B.DIRECT_IND_ID,
    X_DIRECT_IND_DISPLAY_CODE => :FEM_DIR_INDIRECT_B.DIRECT_IND_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_DIR_INDIRECT_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_DIR_INDIRECT_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_DIR_INDIRECT_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_DIR_INDIRECT_B.OBJECT_VERSION_NUMBER,
    X_DIRECT_IND_NAME => :FEM_DIR_INDIRECT_B.DIRECT_IND_NAME,
    X_DESCRIPTION => :FEM_DIR_INDIRECT_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_DIR_INDIRECT_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_DIR_INDIRECT_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_DIR_INDIRECT_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_DIR_INDIRECT_UL" ENABLE;
