--------------------------------------------------------
--  DDL for Trigger FEM_CHANNELS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CHANNELS_IL" 
instead of insert on FEM_CHANNELS_VL
referencing new as FEM_CHANNELS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_CHANNELS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_CHANNEL_ID => :FEM_CHANNELS_B.CHANNEL_ID,
    X_VALUE_SET_ID => :FEM_CHANNELS_B.VALUE_SET_ID,
    X_DIMENSION_GROUP_ID => :FEM_CHANNELS_B.DIMENSION_GROUP_ID,
    X_CHANNEL_DISPLAY_CODE => :FEM_CHANNELS_B.CHANNEL_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_CHANNELS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_CHANNELS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_CHANNELS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_CHANNELS_B.OBJECT_VERSION_NUMBER,
    X_CHANNEL_NAME => :FEM_CHANNELS_B.CHANNEL_NAME,
    X_DESCRIPTION => :FEM_CHANNELS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_CHANNELS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_CHANNELS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_CHANNELS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_CHANNELS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_CHANNELS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CHANNELS_IL" ENABLE;
