--------------------------------------------------------
--  DDL for Trigger FEM_OBJECT_CATALOG_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_OBJECT_CATALOG_IL" 
instead of insert on FEM_OBJECT_CATALOG_VL
referencing new as FEM_OBJECT_CATALOG_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_OBJECT_CATALOG_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_OBJECT_ID => :FEM_OBJECT_CATALOG_B.OBJECT_ID,
    X_OBJECT_TYPE_CODE => :FEM_OBJECT_CATALOG_B.OBJECT_TYPE_CODE,
    X_FOLDER_ID => :FEM_OBJECT_CATALOG_B.FOLDER_ID,
    X_LOCAL_VS_COMBO_ID => :FEM_OBJECT_CATALOG_B.LOCAL_VS_COMBO_ID,
    X_OBJECT_ACCESS_CODE => :FEM_OBJECT_CATALOG_B.OBJECT_ACCESS_CODE,
    X_OBJECT_ORIGIN_CODE => :FEM_OBJECT_CATALOG_B.OBJECT_ORIGIN_CODE,
    X_OBJECT_VERSION_NUMBER => :FEM_OBJECT_CATALOG_B.OBJECT_VERSION_NUMBER,
    X_OBJECT_NAME => :FEM_OBJECT_CATALOG_B.OBJECT_NAME,
    X_DESCRIPTION => :FEM_OBJECT_CATALOG_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_OBJECT_CATALOG_B.CREATION_DATE,
    X_CREATED_BY => :FEM_OBJECT_CATALOG_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_OBJECT_CATALOG_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_OBJECT_CATALOG_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_OBJECT_CATALOG_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_OBJECT_CATALOG_IL" ENABLE;
