--------------------------------------------------------
--  DDL for Trigger FEM_COST_CENTERS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_COST_CENTERS_UL" 
instead of update on FEM_COST_CENTERS_VL
referencing new as FEM_COST_CENTERS_B
for each row
begin
  FEM_COST_CENTERS_PKG.UPDATE_ROW(
    X_COST_CENTER_ID => :FEM_COST_CENTERS_B.COST_CENTER_ID,
    X_VALUE_SET_ID => :FEM_COST_CENTERS_B.VALUE_SET_ID,
    X_DIMENSION_GROUP_ID => :FEM_COST_CENTERS_B.DIMENSION_GROUP_ID,
    X_COST_CENTER_DISPLAY_CODE => :FEM_COST_CENTERS_B.COST_CENTER_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_COST_CENTERS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_COST_CENTERS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_COST_CENTERS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_COST_CENTERS_B.OBJECT_VERSION_NUMBER,
    X_COST_CENTER_NAME => :FEM_COST_CENTERS_B.COST_CENTER_NAME,
    X_DESCRIPTION => :FEM_COST_CENTERS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_COST_CENTERS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_COST_CENTERS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_COST_CENTERS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_COST_CENTERS_UL" ENABLE;
