--------------------------------------------------------
--  DDL for Trigger FEM_DATA_AGGS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_DATA_AGGS_UL" 
instead of update on FEM_DATA_AGGS_VL
referencing new as FEM_DATA_AGGS_B
for each row
begin
  FEM_DATA_AGGS_PKG.UPDATE_ROW(
    X_DATA_AGGREG_TYPE_CODE => :FEM_DATA_AGGS_B.DATA_AGGREG_TYPE_CODE,
    X_ENABLED_FLAG => :FEM_DATA_AGGS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_DATA_AGGS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_DATA_AGGS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_DATA_AGGS_B.OBJECT_VERSION_NUMBER,
    X_DATA_AGGREG_TYPE_NAME => :FEM_DATA_AGGS_B.DATA_AGGREG_TYPE_NAME,
    X_DESCRIPTION => :FEM_DATA_AGGS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_DATA_AGGS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_DATA_AGGS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_DATA_AGGS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_DATA_AGGS_UL" ENABLE;
