--------------------------------------------------------
--  DDL for Trigger FEM_MARITAL_STS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_MARITAL_STS_UL" 
instead of update on FEM_MARITAL_STS_VL
referencing new as FEM_MARITAL_STS_B
for each row
begin
  FEM_MARITAL_STS_PKG.UPDATE_ROW(
    X_MARITAL_STATUS_CODE => :FEM_MARITAL_STS_B.MARITAL_STATUS_CODE,
    X_ENABLED_FLAG => :FEM_MARITAL_STS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_MARITAL_STS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_MARITAL_STS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_MARITAL_STS_B.OBJECT_VERSION_NUMBER,
    X_MARITAL_STATUS_NAME => :FEM_MARITAL_STS_B.MARITAL_STATUS_NAME,
    X_DESCRIPTION => :FEM_MARITAL_STS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_MARITAL_STS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_MARITAL_STS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_MARITAL_STS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_MARITAL_STS_UL" ENABLE;
