--------------------------------------------------------
--  DDL for Trigger FEM_CENSUS_BLK_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CENSUS_BLK_UL" 
instead of update on FEM_CENSUS_BLK_VL
referencing new as FEM_CENSUS_BLK_B
for each row
begin
  FEM_CENSUS_BLK_PKG.UPDATE_ROW(
    X_CENSUS_BLOCK_CODE => :FEM_CENSUS_BLK_B.CENSUS_BLOCK_CODE,
    X_OBJECT_VERSION_NUMBER => :FEM_CENSUS_BLK_B.OBJECT_VERSION_NUMBER,
    X_ENABLED_FLAG => :FEM_CENSUS_BLK_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_CENSUS_BLK_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_CENSUS_BLK_B.READ_ONLY_FLAG,
    X_CENSUS_BLOCK_NAME => :FEM_CENSUS_BLK_B.CENSUS_BLOCK_NAME,
    X_DESCRIPTION => :FEM_CENSUS_BLK_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_CENSUS_BLK_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_CENSUS_BLK_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_CENSUS_BLK_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CENSUS_BLK_UL" ENABLE;
