--------------------------------------------------------
--  DDL for Trigger FEM_SCHOOLS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_SCHOOLS_IL" 
instead of insert on FEM_SCHOOLS_VL
referencing new as FEM_SCHOOLS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_SCHOOLS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_SCHOOL_ID_CODE => :FEM_SCHOOLS_B.SCHOOL_ID_CODE,
    X_ENABLED_FLAG => :FEM_SCHOOLS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_SCHOOLS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_SCHOOLS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_SCHOOLS_B.OBJECT_VERSION_NUMBER,
    X_SCHOOL_ID_NAME => :FEM_SCHOOLS_B.SCHOOL_ID_NAME,
    X_DESCRIPTION => :FEM_SCHOOLS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_SCHOOLS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_SCHOOLS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_SCHOOLS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_SCHOOLS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_SCHOOLS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_SCHOOLS_IL" ENABLE;
