--------------------------------------------------------
--  DDL for Trigger FEM_LIQ_CLASSES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_LIQ_CLASSES_UL" 
instead of update on FEM_LIQ_CLASSES_VL
referencing new as FEM_LIQ_CLASSES_B
for each row
begin
  FEM_LIQ_CLASSES_PKG.UPDATE_ROW(
    X_LIQUIDITY_CLASS_ID => :FEM_LIQ_CLASSES_B.LIQUIDITY_CLASS_ID,
    X_LIQUIDITY_CLASS_DISPLAY_CODE => :FEM_LIQ_CLASSES_B.LIQUIDITY_CLASS_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_LIQ_CLASSES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_LIQ_CLASSES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_LIQ_CLASSES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_LIQ_CLASSES_B.OBJECT_VERSION_NUMBER,
    X_LIQUIDITY_CLASS_NAME => :FEM_LIQ_CLASSES_B.LIQUIDITY_CLASS_NAME,
    X_DESCRIPTION => :FEM_LIQ_CLASSES_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_LIQ_CLASSES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_LIQ_CLASSES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_LIQ_CLASSES_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_LIQ_CLASSES_UL" ENABLE;
