--------------------------------------------------------
--  DDL for Trigger FEM_MKT_SEGMNTS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_MKT_SEGMNTS_IL" 
instead of insert on FEM_MKT_SEGMNTS_VL
referencing new as FEM_MKT_SEGMNTS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_MKT_SEGMNTS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_MARKET_SEGMENT_ID => :FEM_MKT_SEGMNTS_B.MARKET_SEGMENT_ID,
    X_MARKET_SEGMENT_DISPLAY_CODE => :FEM_MKT_SEGMNTS_B.MARKET_SEGMENT_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_MKT_SEGMNTS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_MKT_SEGMNTS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_MKT_SEGMNTS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_MKT_SEGMNTS_B.OBJECT_VERSION_NUMBER,
    X_MARKET_SEGMENT_NAME => :FEM_MKT_SEGMNTS_B.MARKET_SEGMENT_NAME,
    X_DESCRIPTION => :FEM_MKT_SEGMNTS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_MKT_SEGMNTS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_MKT_SEGMNTS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_MKT_SEGMNTS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_MKT_SEGMNTS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_MKT_SEGMNTS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_MKT_SEGMNTS_IL" ENABLE;
