--------------------------------------------------------
--  DDL for Trigger FEM_DIM_ATTR_VERSIONS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_DIM_ATTR_VERSIONS_IL" 
instead of insert on FEM_DIM_ATTR_VERSIONS_VL
referencing new as DIM_ATTR_VERSION
for each row
declare
  row_id rowid;
 ---
begin
  FEM_DIM_ATTR_VERSIONS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_VERSION_ID => :DIM_ATTR_VERSION.VERSION_ID,
    X_ATTRIBUTE_ID => :DIM_ATTR_VERSION.ATTRIBUTE_ID,
    X_AW_SNAPSHOT_FLAG => :DIM_ATTR_VERSION.AW_SNAPSHOT_FLAG,
    X_VERSION_DISPLAY_CODE => :DIM_ATTR_VERSION.VERSION_DISPLAY_CODE,
    X_OBJECT_VERSION_NUMBER => :DIM_ATTR_VERSION.OBJECT_VERSION_NUMBER,
    X_DEFAULT_VERSION_FLAG => :DIM_ATTR_VERSION.DEFAULT_VERSION_FLAG,
    X_PERSONAL_FLAG => :DIM_ATTR_VERSION.PERSONAL_FLAG,
    X_VERSION_NAME => :DIM_ATTR_VERSION.VERSION_NAME,
    X_DESCRIPTION => :DIM_ATTR_VERSION.DESCRIPTION,
    X_CREATION_DATE => :DIM_ATTR_VERSION.CREATION_DATE,
    X_CREATED_BY => :DIM_ATTR_VERSION.CREATED_BY,
    X_LAST_UPDATE_DATE => :DIM_ATTR_VERSION.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :DIM_ATTR_VERSION.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :DIM_ATTR_VERSION.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_DIM_ATTR_VERSIONS_IL" ENABLE;
