--------------------------------------------------------
--  DDL for Trigger FEM_MAP_RULE_TYPES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_MAP_RULE_TYPES_UL" 
instead of update on FEM_MAP_RULE_TYPES_VL
referencing new as FEM_MAP_RULE_TYPES_B
for each row
begin
  FEM_MAP_RULE_TYPES_PKG.UPDATE_ROW(
    X_MAP_RULE_TYPE_CODE => :FEM_MAP_RULE_TYPES_B.MAP_RULE_TYPE_CODE,
    X_ENABLED_FLAG => :FEM_MAP_RULE_TYPES_B.ENABLED_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_MAP_RULE_TYPES_B.OBJECT_VERSION_NUMBER,
    X_MAP_RULE_TYPE_NAME => :FEM_MAP_RULE_TYPES_B.MAP_RULE_TYPE_NAME,
    X_DESCRIPTION => :FEM_MAP_RULE_TYPES_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_MAP_RULE_TYPES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_MAP_RULE_TYPES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_MAP_RULE_TYPES_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---

/
ALTER TRIGGER "APPS"."FEM_MAP_RULE_TYPES_UL" ENABLE;
