--------------------------------------------------------
--  DDL for Trigger FEM_SCHOOLS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_SCHOOLS_UL" 
instead of update on FEM_SCHOOLS_VL
referencing new as FEM_SCHOOLS_B
for each row
begin
  FEM_SCHOOLS_PKG.UPDATE_ROW(
    X_SCHOOL_ID_CODE => :FEM_SCHOOLS_B.SCHOOL_ID_CODE,
    X_ENABLED_FLAG => :FEM_SCHOOLS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_SCHOOLS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_SCHOOLS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_SCHOOLS_B.OBJECT_VERSION_NUMBER,
    X_SCHOOL_ID_NAME => :FEM_SCHOOLS_B.SCHOOL_ID_NAME,
    X_DESCRIPTION => :FEM_SCHOOLS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_SCHOOLS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_SCHOOLS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_SCHOOLS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_SCHOOLS_UL" ENABLE;
