--------------------------------------------------------
--  DDL for Trigger FEM_APP_ANALYSTS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_APP_ANALYSTS_IL" 
instead of insert on FEM_APP_ANALYSTS_VL
referencing new as FEM_APP_ANALYSTS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_APP_ANALYSTS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_APPL_ANALYST_CODE => :FEM_APP_ANALYSTS_B.APPL_ANALYST_CODE,
    X_ENABLED_FLAG => :FEM_APP_ANALYSTS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_APP_ANALYSTS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_APP_ANALYSTS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_APP_ANALYSTS_B.OBJECT_VERSION_NUMBER,
    X_APPL_ANALYST_NAME => :FEM_APP_ANALYSTS_B.APPL_ANALYST_NAME,
    X_DESCRIPTION => :FEM_APP_ANALYSTS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_APP_ANALYSTS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_APP_ANALYSTS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_APP_ANALYSTS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_APP_ANALYSTS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_APP_ANALYSTS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_APP_ANALYSTS_IL" ENABLE;
