--------------------------------------------------------
--  DDL for Trigger FEM_CREDIT_STATUS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CREDIT_STATUS_UL" 
instead of update on FEM_CREDIT_STATUS_VL
referencing new as FEM_CREDIT_STATUS_B
for each row
begin
  FEM_CREDIT_STATUS_PKG.UPDATE_ROW(
    X_CREDIT_STATUS_ID => :FEM_CREDIT_STATUS_B.CREDIT_STATUS_ID,
    X_CREDIT_STATUS_DISPLAY_CODE => :FEM_CREDIT_STATUS_B.CREDIT_STATUS_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_CREDIT_STATUS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_CREDIT_STATUS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_CREDIT_STATUS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_CREDIT_STATUS_B.OBJECT_VERSION_NUMBER,
    X_CREDIT_STATUS_NAME => :FEM_CREDIT_STATUS_B.CREDIT_STATUS_NAME,
    X_DESCRIPTION => :FEM_CREDIT_STATUS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_CREDIT_STATUS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_CREDIT_STATUS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_CREDIT_STATUS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CREDIT_STATUS_UL" ENABLE;
