--------------------------------------------------------
--  DDL for Trigger FEM_PLANS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PLANS_IL" 
instead of insert on FEM_PLANS_VL
referencing new as FEM_PLANS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_PLANS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_PLAN_CODE => :FEM_PLANS_B.PLAN_CODE,
    X_ENABLED_FLAG => :FEM_PLANS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PLANS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PLANS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PLANS_B.OBJECT_VERSION_NUMBER,
    X_PLAN_NAME => :FEM_PLANS_B.PLAN_NAME,
    X_DESCRIPTION => :FEM_PLANS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_PLANS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_PLANS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_PLANS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PLANS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PLANS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PLANS_IL" ENABLE;
