--------------------------------------------------------
--  DDL for Trigger FEM_PROJECTS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PROJECTS_IL" 
instead of insert on FEM_PROJECTS_VL
referencing new as FEM_PROJECTS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_PROJECTS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_PROJECT_ID => :FEM_PROJECTS_B.PROJECT_ID,
    X_VALUE_SET_ID => :FEM_PROJECTS_B.VALUE_SET_ID,
    X_PROJECT_DISPLAY_CODE => :FEM_PROJECTS_B.PROJECT_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_PROJECTS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PROJECTS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PROJECTS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PROJECTS_B.OBJECT_VERSION_NUMBER,
    X_DIMENSION_GROUP_ID => :FEM_PROJECTS_B.DIMENSION_GROUP_ID,
    X_PROJECT_NAME => :FEM_PROJECTS_B.PROJECT_NAME,
    X_DESCRIPTION => :FEM_PROJECTS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_PROJECTS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_PROJECTS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_PROJECTS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PROJECTS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PROJECTS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PROJECTS_IL" ENABLE;
