--------------------------------------------------------
--  DDL for Trigger FEM_EXIST_BORWR_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_EXIST_BORWR_IL" 
instead of insert on FEM_EXIST_BORWR_VL
referencing new as FEM_EXIST_BORWR_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_EXIST_BORWR_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_EXIST_BORROWER_ID => :FEM_EXIST_BORWR_B.EXIST_BORROWER_ID,
    X_EXIST_BORROWER_DISPLAY_CODE => :FEM_EXIST_BORWR_B.EXIST_BORROWER_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_EXIST_BORWR_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_EXIST_BORWR_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_EXIST_BORWR_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_EXIST_BORWR_B.OBJECT_VERSION_NUMBER,
    X_EXIST_BORROWER_NAME => :FEM_EXIST_BORWR_B.EXIST_BORROWER_NAME,
    X_DESCRIPTION => :FEM_EXIST_BORWR_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_EXIST_BORWR_B.CREATION_DATE,
    X_CREATED_BY => :FEM_EXIST_BORWR_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_EXIST_BORWR_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_EXIST_BORWR_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_EXIST_BORWR_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_EXIST_BORWR_IL" ENABLE;
