--------------------------------------------------------
--  DDL for Trigger FEM_PRNT_SERVCES_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PRNT_SERVCES_IL" 
instead of insert on FEM_PRNT_SERVCES_VL
referencing new as FEM_PRNT_SERVCES_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_PRNT_SERVCES_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_PARENT_SERVICE_CODE => :FEM_PRNT_SERVCES_B.PARENT_SERVICE_CODE,
    X_ENABLED_FLAG => :FEM_PRNT_SERVCES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PRNT_SERVCES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PRNT_SERVCES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PRNT_SERVCES_B.OBJECT_VERSION_NUMBER,
    X_PARENT_SERVICE_NAME => :FEM_PRNT_SERVCES_B.PARENT_SERVICE_NAME,
    X_DESCRIPTION => :FEM_PRNT_SERVCES_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_PRNT_SERVCES_B.CREATION_DATE,
    X_CREATED_BY => :FEM_PRNT_SERVCES_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_PRNT_SERVCES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PRNT_SERVCES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PRNT_SERVCES_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PRNT_SERVCES_IL" ENABLE;
