--------------------------------------------------------
--  DDL for Trigger FEM_CALENDARS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CALENDARS_UL" 
instead of update on FEM_CALENDARS_VL
referencing new as CALENDAR
for each row
begin
  FEM_CALENDARS_PKG.UPDATE_ROW(
    X_CALENDAR_ID => :CALENDAR.CALENDAR_ID,
    X_READ_ONLY_FLAG => :CALENDAR.READ_ONLY_FLAG,
    X_PERSONAL_FLAG => :CALENDAR.PERSONAL_FLAG,
    X_ENABLED_FLAG => :CALENDAR.ENABLED_FLAG,
    X_CALENDAR_DISPLAY_CODE => :CALENDAR.CALENDAR_DISPLAY_CODE,
    X_OBJECT_VERSION_NUMBER => :CALENDAR.OBJECT_VERSION_NUMBER,
    X_CALENDAR_NAME => :CALENDAR.CALENDAR_NAME,
    X_DESCRIPTION => :CALENDAR.DESCRIPTION,
    X_LAST_UPDATE_DATE => :CALENDAR.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :CALENDAR.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :CALENDAR.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CALENDARS_UL" ENABLE;
