--------------------------------------------------------
--  DDL for Trigger FEM_CORPAGRMNTS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CORPAGRMNTS_IL" 
instead of insert on FEM_CORPAGRMNTS_VL
referencing new as FEM_CORPAGRMNTS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_CORPAGRMNTS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_CORPORATE_AGREEMENT_CODE => :FEM_CORPAGRMNTS_B.CORPORATE_AGREEMENT_CODE,
    X_ENABLED_FLAG => :FEM_CORPAGRMNTS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_CORPAGRMNTS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_CORPAGRMNTS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_CORPAGRMNTS_B.OBJECT_VERSION_NUMBER,
    X_CORPORATE_AGREEMENT_NAME => :FEM_CORPAGRMNTS_B.CORPORATE_AGREEMENT_NAME,
    X_DESCRIPTION => :FEM_CORPAGRMNTS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_CORPAGRMNTS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_CORPAGRMNTS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_CORPAGRMNTS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_CORPAGRMNTS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_CORPAGRMNTS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CORPAGRMNTS_IL" ENABLE;
