--------------------------------------------------------
--  DDL for Trigger FEM_PAY_AHEAD_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PAY_AHEAD_IL" 
instead of insert on FEM_PAY_AHEAD_VL
referencing new as FEM_PAY_AHEAD_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_PAY_AHEAD_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_PAY_AHEAD_CODE => :FEM_PAY_AHEAD_B.PAY_AHEAD_CODE,
    X_ENABLED_FLAG => :FEM_PAY_AHEAD_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PAY_AHEAD_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PAY_AHEAD_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PAY_AHEAD_B.OBJECT_VERSION_NUMBER,
    X_PAY_AHEAD_NAME => :FEM_PAY_AHEAD_B.PAY_AHEAD_NAME,
    X_DESCRIPTION => :FEM_PAY_AHEAD_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_PAY_AHEAD_B.CREATION_DATE,
    X_CREATED_BY => :FEM_PAY_AHEAD_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_PAY_AHEAD_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PAY_AHEAD_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PAY_AHEAD_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PAY_AHEAD_IL" ENABLE;
