--------------------------------------------------------
--  DDL for Trigger FEM_SIC_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_SIC_IL" 
instead of insert on FEM_SIC_VL
referencing new as FEM_SIC_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_SIC_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_SIC_ID => :FEM_SIC_B.SIC_ID,
    X_SIC_DISPLAY_CODE => :FEM_SIC_B.SIC_DISPLAY_CODE,
    X_DIMENSION_GROUP_ID => :FEM_SIC_B.DIMENSION_GROUP_ID,
    X_ENABLED_FLAG => :FEM_SIC_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_SIC_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_SIC_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_SIC_B.OBJECT_VERSION_NUMBER,
    X_SIC_NAME => :FEM_SIC_B.SIC_NAME,
    X_DESCRIPTION => :FEM_SIC_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_SIC_B.CREATION_DATE,
    X_CREATED_BY => :FEM_SIC_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_SIC_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_SIC_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_SIC_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_SIC_IL" ENABLE;
