--------------------------------------------------------
--  DDL for Trigger FEM_VALUE_SETS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_VALUE_SETS_UL" 
instead of update on FEM_VALUE_SETS_VL
referencing new as FEM_VALUE_SETS_B
for each row
begin
  FEM_VALUE_SETS_PKG.UPDATE_ROW(
    X_VALUE_SET_ID => :FEM_VALUE_SETS_B.VALUE_SET_ID,
    X_DEFAULT_LOAD_MEMBER_ID => :FEM_VALUE_SETS_B.DEFAULT_LOAD_MEMBER_ID,
    X_DEFAULT_MEMBER_ID => :FEM_VALUE_SETS_B.DEFAULT_MEMBER_ID,
    X_OBJECT_VERSION_NUMBER => :FEM_VALUE_SETS_B.OBJECT_VERSION_NUMBER,
    X_DEFAULT_HIERARCHY_OBJ_ID => :FEM_VALUE_SETS_B.DEFAULT_HIERARCHY_OBJ_ID,
    X_READ_ONLY_FLAG => :FEM_VALUE_SETS_B.READ_ONLY_FLAG,
    X_VALUE_SET_DISPLAY_CODE => :FEM_VALUE_SETS_B.VALUE_SET_DISPLAY_CODE,
    X_DIMENSION_ID => :FEM_VALUE_SETS_B.DIMENSION_ID,
    X_VALUE_SET_NAME => :FEM_VALUE_SETS_B.VALUE_SET_NAME,
    X_DESCRIPTION => :FEM_VALUE_SETS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_VALUE_SETS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_VALUE_SETS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_VALUE_SETS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_VALUE_SETS_UL" ENABLE;
