--------------------------------------------------------
--  DDL for Trigger FEM_ACCT_GRPS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_ACCT_GRPS_UL" 
instead of update on FEM_ACCT_GRPS_VL
referencing new as FEM_ACCT_GRPS_B
for each row
begin
  FEM_ACCT_GRPS_PKG.UPDATE_ROW(
    X_ACCOUNT_GROUP_ID => :FEM_ACCT_GRPS_B.ACCOUNT_GROUP_ID,
    X_ACCOUNT_GROUP_DISPLAY_CODE => :FEM_ACCT_GRPS_B.ACCOUNT_GROUP_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_ACCT_GRPS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_ACCT_GRPS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_ACCT_GRPS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_ACCT_GRPS_B.OBJECT_VERSION_NUMBER,
    X_ACCOUNT_GROUP_NAME => :FEM_ACCT_GRPS_B.ACCOUNT_GROUP_NAME,
    X_DESCRIPTION => :FEM_ACCT_GRPS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_ACCT_GRPS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_ACCT_GRPS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_ACCT_GRPS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_ACCT_GRPS_UL" ENABLE;
