--------------------------------------------------------
--  DDL for Trigger FEM_PRODUCTS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PRODUCTS_UL" 
instead of update on FEM_PRODUCTS_VL
referencing new as FEM_PRODUCTS_B
for each row
begin
  FEM_PRODUCTS_PKG.UPDATE_ROW(
    X_PRODUCT_ID => :FEM_PRODUCTS_B.PRODUCT_ID,
    X_VALUE_SET_ID => :FEM_PRODUCTS_B.VALUE_SET_ID,
    X_DIMENSION_GROUP_ID => :FEM_PRODUCTS_B.DIMENSION_GROUP_ID,
    X_PRODUCT_DISPLAY_CODE => :FEM_PRODUCTS_B.PRODUCT_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_PRODUCTS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PRODUCTS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PRODUCTS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PRODUCTS_B.OBJECT_VERSION_NUMBER,
    X_PRODUCT_NAME => :FEM_PRODUCTS_B.PRODUCT_NAME,
    X_DESCRIPTION => :FEM_PRODUCTS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_PRODUCTS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PRODUCTS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PRODUCTS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PRODUCTS_UL" ENABLE;
