--------------------------------------------------------
--  DDL for Trigger FEM_CHGOFF_RSN_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_CHGOFF_RSN_IL" 
instead of insert on FEM_CHGOFF_RSN_VL
referencing new as FEM_CHGOFF_RSN_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_CHGOFF_RSN_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_CHARGE_OFF_REASON_CODE => :FEM_CHGOFF_RSN_B.CHARGE_OFF_REASON_CODE,
    X_ENABLED_FLAG => :FEM_CHGOFF_RSN_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_CHGOFF_RSN_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_CHGOFF_RSN_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_CHGOFF_RSN_B.OBJECT_VERSION_NUMBER,
    X_CHARGE_OFF_REASON_NAME => :FEM_CHGOFF_RSN_B.CHARGE_OFF_REASON_NAME,
    X_DESCRIPTION => :FEM_CHGOFF_RSN_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_CHGOFF_RSN_B.CREATION_DATE,
    X_CREATED_BY => :FEM_CHGOFF_RSN_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_CHGOFF_RSN_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_CHGOFF_RSN_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_CHGOFF_RSN_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_CHGOFF_RSN_IL" ENABLE;
