--------------------------------------------------------
--  DDL for Trigger FEM_OCCUPATIONS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_OCCUPATIONS_UL" 
instead of update on FEM_OCCUPATIONS_VL
referencing new as FEM_OCCUPATIONS_B
for each row
begin
  FEM_OCCUPATIONS_PKG.UPDATE_ROW(
    X_OCCUPATION_CODE => :FEM_OCCUPATIONS_B.OCCUPATION_CODE,
    X_ENABLED_FLAG => :FEM_OCCUPATIONS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_OCCUPATIONS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_OCCUPATIONS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_OCCUPATIONS_B.OBJECT_VERSION_NUMBER,
    X_OCCUPATION_NAME => :FEM_OCCUPATIONS_B.OCCUPATION_NAME,
    X_DESCRIPTION => :FEM_OCCUPATIONS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_OCCUPATIONS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_OCCUPATIONS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_OCCUPATIONS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_OCCUPATIONS_UL" ENABLE;
