--------------------------------------------------------
--  DDL for Trigger FEM_FIN_ELEMS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_FIN_ELEMS_UL" 
instead of update on FEM_FIN_ELEMS_VL
referencing new as FEM_FIN_ELEMS_B
for each row
begin
  FEM_FIN_ELEMS_PKG.UPDATE_ROW(
    X_FINANCIAL_ELEM_ID => :FEM_FIN_ELEMS_B.FINANCIAL_ELEM_ID,
    X_VALUE_SET_ID => :FEM_FIN_ELEMS_B.VALUE_SET_ID,
    X_FINANCIAL_ELEM_DISPLAY_CODE => :FEM_FIN_ELEMS_B.FINANCIAL_ELEM_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_FIN_ELEMS_B.ENABLED_FLAG,
    X_READ_ONLY_FLAG => :FEM_FIN_ELEMS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_FIN_ELEMS_B.OBJECT_VERSION_NUMBER,
    X_PERSONAL_FLAG => :FEM_FIN_ELEMS_B.PERSONAL_FLAG,
    X_FINANCIAL_ELEM_NAME => :FEM_FIN_ELEMS_B.FINANCIAL_ELEM_NAME,
    X_DESCRIPTION => :FEM_FIN_ELEMS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_FIN_ELEMS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_FIN_ELEMS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_FIN_ELEMS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_FIN_ELEMS_UL" ENABLE;
