--------------------------------------------------------
--  DDL for Trigger FEM_TABLES_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_TABLES_IL" 
instead of insert on FEM_TABLES_VL
referencing new as FEM_TABLES_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_TABLES_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_TABLE_NAME => :FEM_TABLES_B.TABLE_NAME,
    X_PROC_KEY_INDEX_OWNER => :FEM_TABLES_B.PROC_KEY_INDEX_OWNER,
    X_DI_VIEW_NAME => :FEM_TABLES_B.DI_VIEW_NAME,
    X_REGISTRATION_STATUS_CODE => :FEM_TABLES_B.REGISTRATION_STATUS_CODE,
    X_INTERFACE_TABLE_NAME => :FEM_TABLES_B.INTERFACE_TABLE_NAME,
    X_PROC_KEY_INDEX_NAME => :FEM_TABLES_B.PROC_KEY_INDEX_NAME,
    X_TABLE_OWNER_APPLICATION_ID => :FEM_TABLES_B.TABLE_OWNER_APPLICATION_ID,
    X_TABLE_ID => :FEM_TABLES_B.TABLE_ID,
    X_ENABLED_FLAG => :FEM_TABLES_B.ENABLED_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_TABLES_B.OBJECT_VERSION_NUMBER,
    X_DISPLAY_NAME => :FEM_TABLES_B.DISPLAY_NAME,
    X_DESCRIPTION => :FEM_TABLES_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_TABLES_B.CREATION_DATE,
    X_CREATED_BY => :FEM_TABLES_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_TABLES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_TABLES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_TABLES_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---

/
ALTER TRIGGER "APPS"."FEM_TABLES_IL" ENABLE;
