--------------------------------------------------------
--  DDL for Trigger FEM_BUDGETS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_BUDGETS_UL" 
instead of update on FEM_BUDGETS_VL
referencing new as FEM_BUDGETS_B
for each row
begin
  FEM_BUDGETS_PKG.UPDATE_ROW(
    X_BUDGET_ID => :FEM_BUDGETS_B.BUDGET_ID,
    X_BUDGET_DISPLAY_CODE => :FEM_BUDGETS_B.BUDGET_DISPLAY_CODE,
    X_READ_ONLY_FLAG => :FEM_BUDGETS_B.READ_ONLY_FLAG,
    X_ENABLED_FLAG => :FEM_BUDGETS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_BUDGETS_B.PERSONAL_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_BUDGETS_B.OBJECT_VERSION_NUMBER,
    X_BUDGET_NAME => :FEM_BUDGETS_B.BUDGET_NAME,
    X_DESCRIPTION => :FEM_BUDGETS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_BUDGETS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_BUDGETS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_BUDGETS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_BUDGETS_UL" ENABLE;
