--------------------------------------------------------
--  DDL for Trigger FEM_APPLICATION_GROUPS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_APPLICATION_GROUPS_UL" 
instead of update on FEM_APPLICATION_GROUPS_VL
referencing new as APPLICATION_GROUP
for each row
begin
  FEM_APPLICATION_GROUPS_PKG.UPDATE_ROW(
    X_APPLICATION_GROUP_ID => :APPLICATION_GROUP.APPLICATION_GROUP_ID,
    X_APPLICATION_GROUP_NAME => :APPLICATION_GROUP.APPLICATION_GROUP_NAME,
    X_DESCRIPTION => :APPLICATION_GROUP.DESCRIPTION,
    X_LAST_UPDATE_DATE => :APPLICATION_GROUP.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :APPLICATION_GROUP.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :APPLICATION_GROUP.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_APPLICATION_GROUPS_UL" ENABLE;
