--------------------------------------------------------
--  DDL for Trigger FEM_PERIODTYPES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_PERIODTYPES_UL" 
instead of update on FEM_PERIODTYPES_VL
referencing new as FEM_PERIODTYPES_B
for each row
begin
  FEM_PERIODTYPES_PKG.UPDATE_ROW(
    X_PERIOD_TYPE_CODE => :FEM_PERIODTYPES_B.PERIOD_TYPE_CODE,
    X_ENABLED_FLAG => :FEM_PERIODTYPES_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_PERIODTYPES_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_PERIODTYPES_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_PERIODTYPES_B.OBJECT_VERSION_NUMBER,
    X_PERIOD_TYPE_NAME => :FEM_PERIODTYPES_B.PERIOD_TYPE_NAME,
    X_DESCRIPTION => :FEM_PERIODTYPES_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_PERIODTYPES_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_PERIODTYPES_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_PERIODTYPES_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_PERIODTYPES_UL" ENABLE;
