--------------------------------------------------------
--  DDL for Trigger FEM_FLAGS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_FLAGS_UL" 
instead of update on FEM_FLAGS_VL
referencing new as FEM_FLAGS_B
for each row
begin
  FEM_FLAGS_PKG.UPDATE_ROW(
    X_FLAG_CODE => :FEM_FLAGS_B.FLAG_CODE,
    X_READ_ONLY_FLAG => :FEM_FLAGS_B.READ_ONLY_FLAG,
    X_PERSONAL_FLAG => :FEM_FLAGS_B.PERSONAL_FLAG,
    X_ENABLED_FLAG => :FEM_FLAGS_B.ENABLED_FLAG,
    X_FLAG_NAME => :FEM_FLAGS_B.FLAG_NAME,
    X_DESCRIPTION => :FEM_FLAGS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_FLAGS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_FLAGS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_FLAGS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_FLAGS_UL" ENABLE;
