--------------------------------------------------------
--  DDL for Trigger FEM_BILLMETHDS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_BILLMETHDS_UL" 
instead of update on FEM_BILLMETHDS_VL
referencing new as FEM_BILLMETHDS_B
for each row
begin
  FEM_BILLMETHDS_PKG.UPDATE_ROW(
    X_BILLING_METHOD_CODE => :FEM_BILLMETHDS_B.BILLING_METHOD_CODE,
    X_ENABLED_FLAG => :FEM_BILLMETHDS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_BILLMETHDS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_BILLMETHDS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_BILLMETHDS_B.OBJECT_VERSION_NUMBER,
    X_BILLING_METHOD_NAME => :FEM_BILLMETHDS_B.BILLING_METHOD_NAME,
    X_DESCRIPTION => :FEM_BILLMETHDS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_BILLMETHDS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_BILLMETHDS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_BILLMETHDS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_BILLMETHDS_UL" ENABLE;
