--------------------------------------------------------
--  DDL for Trigger FEM_LN_ITEMS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_LN_ITEMS_UL" 
instead of update on FEM_LN_ITEMS_VL
referencing new as FEM_LN_ITEMS_B
for each row
begin
  FEM_LN_ITEMS_PKG.UPDATE_ROW(
    X_LINE_ITEM_ID => :FEM_LN_ITEMS_B.LINE_ITEM_ID,
    X_VALUE_SET_ID => :FEM_LN_ITEMS_B.VALUE_SET_ID,
    X_READ_ONLY_FLAG => :FEM_LN_ITEMS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_LN_ITEMS_B.OBJECT_VERSION_NUMBER,
    X_DIMENSION_GROUP_ID => :FEM_LN_ITEMS_B.DIMENSION_GROUP_ID,
    X_LINE_ITEM_DISPLAY_CODE => :FEM_LN_ITEMS_B.LINE_ITEM_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_LN_ITEMS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_LN_ITEMS_B.PERSONAL_FLAG,
    X_LINE_ITEM_NAME => :FEM_LN_ITEMS_B.LINE_ITEM_NAME,
    X_DESCRIPTION => :FEM_LN_ITEMS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_LN_ITEMS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_LN_ITEMS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_LN_ITEMS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_LN_ITEMS_UL" ENABLE;
