--------------------------------------------------------
--  DDL for Trigger FEM_LEDGERS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_LEDGERS_IL" 
instead of insert on FEM_LEDGERS_VL
referencing new as FEM_LEDGERS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_LEDGERS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_LEDGER_ID => :FEM_LEDGERS_B.LEDGER_ID,
    X_PERSONAL_FLAG => :FEM_LEDGERS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_LEDGERS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_LEDGERS_B.OBJECT_VERSION_NUMBER,
    X_ENABLED_FLAG => :FEM_LEDGERS_B.ENABLED_FLAG,
    X_LEDGER_DISPLAY_CODE => :FEM_LEDGERS_B.LEDGER_DISPLAY_CODE,
    X_LEDGER_NAME => :FEM_LEDGERS_B.LEDGER_NAME,
    X_DESCRIPTION => :FEM_LEDGERS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_LEDGERS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_LEDGERS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_LEDGERS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_LEDGERS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_LEDGERS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_LEDGERS_IL" ENABLE;
