--------------------------------------------------------
--  DDL for Trigger FEM_TASKS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_TASKS_IL" 
instead of insert on FEM_TASKS_VL
referencing new as FEM_TASKS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_TASKS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_TASK_ID => :FEM_TASKS_B.TASK_ID,
    X_VALUE_SET_ID => :FEM_TASKS_B.VALUE_SET_ID,
    X_DIMENSION_GROUP_ID => :FEM_TASKS_B.DIMENSION_GROUP_ID,
    X_TASK_DISPLAY_CODE => :FEM_TASKS_B.TASK_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_TASKS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_TASKS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_TASKS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_TASKS_B.OBJECT_VERSION_NUMBER,
    X_TASK_NAME => :FEM_TASKS_B.TASK_NAME,
    X_DESCRIPTION => :FEM_TASKS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_TASKS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_TASKS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_TASKS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_TASKS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_TASKS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_TASKS_IL" ENABLE;
