--------------------------------------------------------
--  DDL for Trigger FEM_JOINT_AGRMNTS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_JOINT_AGRMNTS_UL" 
instead of update on FEM_JOINT_AGRMNTS_VL
referencing new as FEM_JOINT_AGRMNTS_B
for each row
begin
  FEM_JOINT_AGRMNTS_PKG.UPDATE_ROW(
    X_JOINT_AGREEMENT_CODE => :FEM_JOINT_AGRMNTS_B.JOINT_AGREEMENT_CODE,
    X_ENABLED_FLAG => :FEM_JOINT_AGRMNTS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_JOINT_AGRMNTS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_JOINT_AGRMNTS_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_JOINT_AGRMNTS_B.OBJECT_VERSION_NUMBER,
    X_JOINT_AGREEMENT_NAME => :FEM_JOINT_AGRMNTS_B.JOINT_AGREEMENT_NAME,
    X_DESCRIPTION => :FEM_JOINT_AGRMNTS_B.DESCRIPTION,
    X_LAST_UPDATE_DATE => :FEM_JOINT_AGRMNTS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_JOINT_AGRMNTS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_JOINT_AGRMNTS_B.LAST_UPDATE_LOGIN);
 ---
end UPDATE_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_JOINT_AGRMNTS_UL" ENABLE;
