--------------------------------------------------------
--  DDL for Trigger FEM_DIR_INDIRECT_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_DIR_INDIRECT_IL" 
instead of insert on FEM_DIR_INDIRECT_VL
referencing new as FEM_DIR_INDIRECT_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_DIR_INDIRECT_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_DIRECT_IND_ID => :FEM_DIR_INDIRECT_B.DIRECT_IND_ID,
    X_DIRECT_IND_DISPLAY_CODE => :FEM_DIR_INDIRECT_B.DIRECT_IND_DISPLAY_CODE,
    X_ENABLED_FLAG => :FEM_DIR_INDIRECT_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_DIR_INDIRECT_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_DIR_INDIRECT_B.READ_ONLY_FLAG,
    X_OBJECT_VERSION_NUMBER => :FEM_DIR_INDIRECT_B.OBJECT_VERSION_NUMBER,
    X_DIRECT_IND_NAME => :FEM_DIR_INDIRECT_B.DIRECT_IND_NAME,
    X_DESCRIPTION => :FEM_DIR_INDIRECT_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_DIR_INDIRECT_B.CREATION_DATE,
    X_CREATED_BY => :FEM_DIR_INDIRECT_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_DIR_INDIRECT_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_DIR_INDIRECT_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_DIR_INDIRECT_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_DIR_INDIRECT_IL" ENABLE;
