--------------------------------------------------------
--  DDL for Trigger FEM_FUNC_DIM_SETS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_FUNC_DIM_SETS_IL" 
instead of insert on FEM_FUNC_DIM_SETS_VL
referencing new as FEM_FUNC_DIM_SETS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_FUNC_DIM_SETS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_FUNC_DIM_SET_ID => :FEM_FUNC_DIM_SETS_B.FUNC_DIM_SET_ID,
    X_FUNC_DIM_SET_OBJ_DEF_ID => :FEM_FUNC_DIM_SETS_B.FUNC_DIM_SET_OBJ_DEF_ID,
    X_DIMENSION_ID => :FEM_FUNC_DIM_SETS_B.DIMENSION_ID,
    X_OBJECT_VERSION_NUMBER => :FEM_FUNC_DIM_SETS_B.OBJECT_VERSION_NUMBER,
    X_FUNC_DIM_SET_NAME => :FEM_FUNC_DIM_SETS_B.FUNC_DIM_SET_NAME,
    X_CREATION_DATE => :FEM_FUNC_DIM_SETS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_FUNC_DIM_SETS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_FUNC_DIM_SETS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_FUNC_DIM_SETS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_FUNC_DIM_SETS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_FUNC_DIM_SETS_IL" ENABLE;
