--------------------------------------------------------
--  DDL for Trigger FEM_FIN_ELEM_PRC_GRPS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_FIN_ELEM_PRC_GRPS_IL" 
instead of insert on FEM_FIN_ELEM_PRC_GRPS_VL
referencing new as FEM_FIN_ELEM_PRC_GRPS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_FIN_ELEM_PRC_GRPS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_FIN_ELEM_PRC_GRP_CODE => :FEM_FIN_ELEM_PRC_GRPS_B.FIN_ELEM_PRC_GRP_CODE,
    X_PERSONAL_FLAG => :FEM_FIN_ELEM_PRC_GRPS_B.PERSONAL_FLAG,
    X_ENABLED_FLAG => :FEM_FIN_ELEM_PRC_GRPS_B.ENABLED_FLAG,
    X_READ_ONLY_FLAG => :FEM_FIN_ELEM_PRC_GRPS_B.READ_ONLY_FLAG,
    X_FIN_ELEM_PRC_GRP_NAME => :FEM_FIN_ELEM_PRC_GRPS_B.FIN_ELEM_PRC_GRP_NAME,
    X_DESCRIPTION => :FEM_FIN_ELEM_PRC_GRPS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_FIN_ELEM_PRC_GRPS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_FIN_ELEM_PRC_GRPS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_FIN_ELEM_PRC_GRPS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_FIN_ELEM_PRC_GRPS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_FIN_ELEM_PRC_GRPS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_FIN_ELEM_PRC_GRPS_IL" ENABLE;
