--------------------------------------------------------
--  DDL for Trigger FEM_MULTIPLIERS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FEM_MULTIPLIERS_IL" 
instead of insert on FEM_MULTIPLIERS_VL
referencing new as FEM_MULTIPLIERS_B
for each row
declare
  row_id rowid;
 ---
begin
  FEM_MULTIPLIERS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_MULTIPLIER_CODE => :FEM_MULTIPLIERS_B.MULTIPLIER_CODE,
    X_ENABLED_FLAG => :FEM_MULTIPLIERS_B.ENABLED_FLAG,
    X_PERSONAL_FLAG => :FEM_MULTIPLIERS_B.PERSONAL_FLAG,
    X_READ_ONLY_FLAG => :FEM_MULTIPLIERS_B.READ_ONLY_FLAG,
    X_MULTIPLIER_NAME => :FEM_MULTIPLIERS_B.MULTIPLIER_NAME,
    X_DESCRIPTION => :FEM_MULTIPLIERS_B.DESCRIPTION,
    X_CREATION_DATE => :FEM_MULTIPLIERS_B.CREATION_DATE,
    X_CREATED_BY => :FEM_MULTIPLIERS_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :FEM_MULTIPLIERS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :FEM_MULTIPLIERS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FEM_MULTIPLIERS_B.LAST_UPDATE_LOGIN);
 ---
end INSERT_ROW;
 ---


/
ALTER TRIGGER "APPS"."FEM_MULTIPLIERS_IL" ENABLE;
