--------------------------------------------------------
--  DDL for Trigger FM_FORM_MST_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FM_FORM_MST_UL" 
/* $Header: gmdfmutg.sql 120.3 2007/02/09 12:22:24 kmotupal ship $ */
instead of update on FM_FORM_MST_VL
referencing new as FM_FORM_MST
for each row
begin
  FM_FORM_MST_MLS.UPDATE_ROW(
    X_FORMULA_ID 		=> :FM_FORM_MST.FORMULA_ID,
    X_OWNER_ORGANIZATION_ID	=> :FM_FORM_MST.OWNER_ORGANIZATION_ID,
    X_TEXT_CODE 		=> :FM_FORM_MST.TEXT_CODE,
    X_DELETE_MARK 		=> :FM_FORM_MST.DELETE_MARK,
    X_TOTAL_INPUT_QTY 	        => :FM_FORM_MST.TOTAL_INPUT_QTY,
    X_PROJECT_ID 		=> NULL,
    X_TOTAL_OUTPUT_QTY 	        => :FM_FORM_MST.TOTAL_OUTPUT_QTY,
    X_YIELD_UOM		        => :FM_FORM_MST.yield_uom,
    X_FORMULA_STATUS 	        => :FM_FORM_MST.FORMULA_STATUS,
    X_OWNER_ID 			=> :FM_FORM_MST.OWNER_ID,
    X_FORMULA_NO 		=> :FM_FORM_MST.FORMULA_NO,
    X_FORMULA_VERS 		=> :FM_FORM_MST.FORMULA_VERS,
    X_FORMULA_TYPE 		=> :FM_FORM_MST.FORMULA_TYPE,
    X_IN_USE 			=> :FM_FORM_MST.IN_USE,
    X_INACTIVE_IND 		=> :FM_FORM_MST.INACTIVE_IND,
    X_SCALE_TYPE 		=> :FM_FORM_MST.SCALE_TYPE,
    X_FORMULA_CLASS 	=> :FM_FORM_MST.FORMULA_CLASS,
    X_FMCONTROL_CLASS 	=> :FM_FORM_MST.FMCONTROL_CLASS,
    X_ATTRIBUTE_CATEGORY => :FM_FORM_MST.ATTRIBUTE_CATEGORY,
    X_ATTRIBUTE1 		=> :FM_FORM_MST.ATTRIBUTE1,
    X_ATTRIBUTE2 		=> :FM_FORM_MST.ATTRIBUTE2,
    X_ATTRIBUTE3 		=> :FM_FORM_MST.ATTRIBUTE3,
    X_ATTRIBUTE4 		=> :FM_FORM_MST.ATTRIBUTE4,
    X_ATTRIBUTE5 		=> :FM_FORM_MST.ATTRIBUTE5,
    X_ATTRIBUTE6 		=> :FM_FORM_MST.ATTRIBUTE6,
    X_ATTRIBUTE7 		=> :FM_FORM_MST.ATTRIBUTE7,
    X_ATTRIBUTE8 		=> :FM_FORM_MST.ATTRIBUTE8,
    X_ATTRIBUTE9 		=> :FM_FORM_MST.ATTRIBUTE9,
    X_ATTRIBUTE10 		=> :FM_FORM_MST.ATTRIBUTE10,
    X_ATTRIBUTE11 		=> :FM_FORM_MST.ATTRIBUTE11,
    X_ATTRIBUTE12 		=> :FM_FORM_MST.ATTRIBUTE12,
    X_ATTRIBUTE13 		=> :FM_FORM_MST.ATTRIBUTE13,
    X_ATTRIBUTE14 		=> :FM_FORM_MST.ATTRIBUTE14,
    X_ATTRIBUTE15 		=> :FM_FORM_MST.ATTRIBUTE15,
    X_ATTRIBUTE16 		=> :FM_FORM_MST.ATTRIBUTE16,
    X_ATTRIBUTE17 		=> :FM_FORM_MST.ATTRIBUTE17,
    X_ATTRIBUTE18 		=> :FM_FORM_MST.ATTRIBUTE18,
    X_ATTRIBUTE19 		=> :FM_FORM_MST.ATTRIBUTE19,
    X_ATTRIBUTE20 		=> :FM_FORM_MST.ATTRIBUTE20,
    X_ATTRIBUTE21 		=> :FM_FORM_MST.ATTRIBUTE21,
    X_ATTRIBUTE22 		=> :FM_FORM_MST.ATTRIBUTE22,
    X_ATTRIBUTE23 		=> :FM_FORM_MST.ATTRIBUTE23,
    X_ATTRIBUTE24 		=> :FM_FORM_MST.ATTRIBUTE24,
    X_ATTRIBUTE25 		=> :FM_FORM_MST.ATTRIBUTE25,
    X_ATTRIBUTE26 		=> :FM_FORM_MST.ATTRIBUTE26,
    X_ATTRIBUTE27 		=> :FM_FORM_MST.ATTRIBUTE27,
    X_ATTRIBUTE28	 	=> :FM_FORM_MST.ATTRIBUTE28,
    X_ATTRIBUTE29 		=> :FM_FORM_MST.ATTRIBUTE29,
    X_ATTRIBUTE30 		=> :FM_FORM_MST.ATTRIBUTE30,
    X_FORMULA_DESC1 	=> :FM_FORM_MST.FORMULA_DESC1,
    X_FORMULA_DESC2 	=> :FM_FORM_MST.FORMULA_DESC2,
    X_LAST_UPDATE_DATE 	=> :FM_FORM_MST.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY 	=> :FM_FORM_MST.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :FM_FORM_MST.LAST_UPDATE_LOGIN,
    X_AUTO_PRODUCT_CALC => :FM_FORM_MST.AUTO_PRODUCT_CALC);

end UPDATE_ROW;

/
ALTER TRIGGER "APPS"."FM_FORM_MST_UL" ENABLE;
