--------------------------------------------------------
--  DDL for Trigger FND_SECURITY_GROUPS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FND_SECURITY_GROUPS_UL" 
instead of update on FND_SECURITY_GROUPS_VL
referencing old as SECURITY_GROUPS
for each row

begin
  FND_SECURITY_GROUPS_PKG.UPDATE_ROW(
    X_SECURITY_GROUP_ID => :SECURITY_GROUPS.SECURITY_GROUP_ID,
    X_SECURITY_GROUP_KEY => :SECURITY_GROUPS.SECURITY_GROUP_KEY,
    X_SECURITY_GROUP_NAME => :SECURITY_GROUPS.SECURITY_GROUP_NAME,
    X_DESCRIPTION => :SECURITY_GROUPS.DESCRIPTION,
    X_LAST_UPDATE_DATE => :SECURITY_GROUPS.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :SECURITY_GROUPS.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :SECURITY_GROUPS.LAST_UPDATE_LOGIN);
end UPDATE_ROW;



/
ALTER TRIGGER "APPS"."FND_SECURITY_GROUPS_UL" ENABLE;
