--------------------------------------------------------
--  DDL for Trigger FND_SECURITY_GROUPS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FND_SECURITY_GROUPS_IL" 
instead of insert on FND_SECURITY_GROUPS_VL
referencing new as SECURITY_GROUPS
for each row

declare
  row_id rowid;
begin
  FND_SECURITY_GROUPS_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_SECURITY_GROUP_ID => :SECURITY_GROUPS.SECURITY_GROUP_ID,
    X_SECURITY_GROUP_KEY => :SECURITY_GROUPS.SECURITY_GROUP_KEY,
    X_SECURITY_GROUP_NAME => :SECURITY_GROUPS.SECURITY_GROUP_NAME,
    X_DESCRIPTION => :SECURITY_GROUPS.DESCRIPTION,
    X_CREATION_DATE => :SECURITY_GROUPS.CREATION_DATE,
    X_CREATED_BY => :SECURITY_GROUPS.CREATED_BY,
    X_LAST_UPDATE_DATE => :SECURITY_GROUPS.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :SECURITY_GROUPS.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :SECURITY_GROUPS.LAST_UPDATE_LOGIN);
end INSERT_ROW;



/
ALTER TRIGGER "APPS"."FND_SECURITY_GROUPS_IL" ENABLE;
