--------------------------------------------------------
--  DDL for Trigger FND_PROFILE_OPTION_VALUE_AT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FND_PROFILE_OPTION_VALUE_AT" BEFORE UPDATE OF APPLICATION_ID,LEVEL_ID,LEVEL_VALUE,LEVEL_VALUE_APPLICATION_ID,PROFILE_OPTION_ID,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,LEVEL_VALUE2,PROFILE_OPTION_VALUE ON "APPLSYS"."FND_PROFILE_OPTION_VALUES" BEGIN IF fnd_global.audit_active THEN fnd_audit_pkg.audit_on := TRUE;ELSE fnd_audit_pkg.audit_on := FALSE;END IF;END;

/
ALTER TRIGGER "APPS"."FND_PROFILE_OPTION_VALUE_AT" ENABLE;
