--------------------------------------------------------
--  DDL for Trigger FND_PROFILE_OPTION_VALUE_AU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FND_PROFILE_OPTION_VALUE_AU" AFTER UPDATE OF APPLICATION_ID,LEVEL_ID,LEVEL_VALUE,LEVEL_VALUE_APPLICATION_ID,PROFILE_OPTION_ID,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,LEVEL_VALUE2,PROFILE_OPTION_VALUE ON "APPLSYS"."FND_PROFILE_OPTION_VALUES" FOR EACH ROW BEGIN IF fnd_audit_pkg.audit_on THEN FND_PROFILE_OPTION_VALUE_AUP(:old.APPLICATION_ID,:old.LEVEL_ID,:old.LEVEL_VALUE,:old.LEVEL_VALUE_APPLICATION_ID,:old.PROFILE_OPTION_ID,:old.CREATED_BY,:old.CREATION_DATE,:old.LAST_UPDATED_BY,:old.LAST_UPDATE_DATE,:old.LAST_UPDATE_LOGIN,:old.LEVEL_VALUE2,:old.PROFILE_OPTION_VALUE,:new.APPLICATION_ID,:new.LEVEL_ID,:new.LEVEL_VALUE,:new.LEVEL_VALUE_APPLICATION_ID,:new.PROFILE_OPTION_ID,:new.CREATED_BY,:new.CREATION_DATE,:new.LAST_UPDATED_BY,:new.LAST_UPDATE_DATE,:new.LAST_UPDATE_LOGIN,:new.LEVEL_VALUE2,:new.PROFILE_OPTION_VALUE);END IF;END;

/
ALTER TRIGGER "APPS"."FND_PROFILE_OPTION_VALUE_AU" ENABLE;
