--------------------------------------------------------
--  DDL for Trigger FV_SYSTEM_PARAMETERS_AT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FV_SYSTEM_PARAMETERS_AT" BEFORE UPDATE OF LAST_UPDATE_DATE,ARAP_OPTION,CREATED_BY,CREATION_DATE,EBD_OPTION,ETC_OPTION,FACTSII_ADVANCE_TYPE_ATTRIBUTE,FACTSII_PUB_LAW_CODE_ATTRIBUTE,FACTSII_TR_DEPT_ID_ATTRIBUTE,FACTSII_TR_MAIN_ACCT_ATTRIBUTE,FACTSI_CUSTOMER_ATTRIBUTE,FACTSI_JOURNAL_ATTRIBUTE,FACTSI_VENDOR_ATTRIBUTE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,PUR_ORDER_DATE_SEG,REC_TRXN_DATE_SEG,REP_2209_ATTRIBUTE,REQ_DATE_SEG,SF224_ACCOMPLISH_DATE ON "FV"."FV_SYSTEM_PARAMETERS" BEGIN IF fnd_global.audit_active THEN fnd_audit_pkg.audit_on := TRUE;ELSE fnd_audit_pkg.audit_on := FALSE;END IF;END;

/
ALTER TRIGGER "APPS"."FV_SYSTEM_PARAMETERS_AT" ENABLE;
