--------------------------------------------------------
--  DDL for Trigger FV_SYSTEM_PARAMETERS_AD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FV_SYSTEM_PARAMETERS_AD" AFTER DELETE ON "FV"."FV_SYSTEM_PARAMETERS" FOR EACH ROW BEGIN IF fnd_audit_pkg.audit_on THEN FV_SYSTEM_PARAMETERS_ADP(:old.LAST_UPDATE_DATE,:old.ARAP_OPTION,:old.CREATED_BY,:old.CREATION_DATE,:old.EBD_OPTION,:old.ETC_OPTION,:old.FACTSII_ADVANCE_TYPE_ATTRIBUTE,:old.FACTSII_PUB_LAW_CODE_ATTRIBUTE,:old.FACTSII_TR_DEPT_ID_ATTRIBUTE,:old.FACTSII_TR_MAIN_ACCT_ATTRIBUTE,:old.FACTSI_CUSTOMER_ATTRIBUTE,:old.FACTSI_JOURNAL_ATTRIBUTE,:old.FACTSI_VENDOR_ATTRIBUTE,:old.LAST_UPDATED_BY,:old.LAST_UPDATE_LOGIN,:old.PUR_ORDER_DATE_SEG,:old.REC_TRXN_DATE_SEG,:old.REP_2209_ATTRIBUTE,:old.REQ_DATE_SEG,:old.SF224_ACCOMPLISH_DATE,:new.LAST_UPDATE_DATE,:new.ARAP_OPTION,:new.CREATED_BY,:new.CREATION_DATE,:new.EBD_OPTION,:new.ETC_OPTION,:new.FACTSII_ADVANCE_TYPE_ATTRIBUTE,:new.FACTSII_PUB_LAW_CODE_ATTRIBUTE,:new.FACTSII_TR_DEPT_ID_ATTRIBUTE,:new.FACTSII_TR_MAIN_ACCT_ATTRIBUTE,:new.FACTSI_CUSTOMER_ATTRIBUTE,:new.FACTSI_JOURNAL_ATTRIBUTE,:new.FACTSI_VENDOR_ATTRIBUTE,:new.LAST_UPDATED_BY,:new.LAST_UPDATE_LOGIN,:new.PUR_ORDER_DATE_SEG,:new.REC_TRXN_DATE_SEG,:new.REP_2209_ATTRIBUTE,:new.REQ_DATE_SEG,:new.SF224_ACCOMPLISH_DATE);END IF;END;

/
ALTER TRIGGER "APPS"."FV_SYSTEM_PARAMETERS_AD" ENABLE;
