--------------------------------------------------------
--  DDL for Trigger GL_JOURNAL_REPORTS_ITF_V_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GL_JOURNAL_REPORTS_ITF_V_ID" 
INSTEAD OF DELETE
ON GL_JOURNAL_REPORTS_ITF_V
BEGIN
	DELETE FROM GL_JOURNAL_REPORTS_ITF ITF WHERE :OLD.ROW_ID = ITF.ROWID;
END;


/
ALTER TRIGGER "APPS"."GL_JOURNAL_REPORTS_ITF_V_ID" ENABLE;
