--------------------------------------------------------
--  DDL for Trigger GMA_PO_TEXT_TBL_T2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMA_PO_TEXT_TBL_T2" 
instead of update on PO_TEXT_TBL_VL
referencing old as PO_TEXT_TBL
for each row
begin
  GMA_PO_TEXT_TBL_PKG.UPDATE_ROW(
    X_ROW_ID => :PO_TEXT_TBL.ROW_ID,
-- Bug #1806284 (JKB)
    X_TEXT_CODE => :PO_TEXT_TBL.TEXT_CODE,
    X_LANG_CODE => :PO_TEXT_TBL.LANG_CODE,
    X_PARAGRAPH_CODE => :PO_TEXT_TBL.PARAGRAPH_CODE,
    X_SUB_PARACODE => :PO_TEXT_TBL.SUB_PARACODE,
    X_LINE_NO => :PO_TEXT_TBL.LINE_NO,
    X_TEXT => :PO_TEXT_TBL.TEXT,
    X_LAST_UPDATE_DATE => :PO_TEXT_TBL.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :PO_TEXT_TBL.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :PO_TEXT_TBL.LAST_UPDATE_LOGIN);
end UPDATE_ROW;


/
ALTER TRIGGER "APPS"."GMA_PO_TEXT_TBL_T2" ENABLE;
