--------------------------------------------------------
--  DDL for Trigger GMA_SY_PARA_CDS_T2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMA_SY_PARA_CDS_T2" 
instead of update on SY_PARA_CDS_VL
referencing old as SY_PARA_CDS
for each row
begin
  GMA_SY_PARA_CDS_PKG.UPDATE_ROW(
    X_TABLE_NAME => :SY_PARA_CDS.TABLE_NAME,
    X_LANG_CODE => :SY_PARA_CDS.LANG_CODE,
    X_PARAGRAPH_CODE => :SY_PARA_CDS.PARAGRAPH_CODE,
    X_SUB_PARACODE => :SY_PARA_CDS.SUB_PARACODE,
    X_NONPRINTABLE_IND => :SY_PARA_CDS.NONPRINTABLE_IND,
    X_PARA_DESC => :SY_PARA_CDS.PARA_DESC,
    X_LAST_UPDATE_DATE => :SY_PARA_CDS.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :SY_PARA_CDS.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :SY_PARA_CDS.LAST_UPDATE_LOGIN);
end UPDATE_ROW;


/
ALTER TRIGGER "APPS"."GMA_SY_PARA_CDS_T2" ENABLE;
