--------------------------------------------------------
--  DDL for Trigger GMA_GME_TEXT_TBL_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMA_GME_TEXT_TBL_T1" 
instead of insert on GME_TEXT_TABLE_VL
referencing new as GME_TEXT_TABLE
for each row
declare
  row_id rowid;
begin
  GMA_GME_TEXT_TBL_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_TEXT_CODE => :GME_TEXT_TABLE.TEXT_CODE,
    X_LANG_CODE => :GME_TEXT_TABLE.LANG_CODE,
    X_PARAGRAPH_CODE => :GME_TEXT_TABLE.PARAGRAPH_CODE,
    X_SUB_PARACODE => :GME_TEXT_TABLE.SUB_PARACODE,
    X_LINE_NO => :GME_TEXT_TABLE.LINE_NO,
    X_TEXT => :GME_TEXT_TABLE.TEXT,
    X_CREATION_DATE => :GME_TEXT_TABLE.CREATION_DATE,
    X_CREATED_BY => :GME_TEXT_TABLE.CREATED_BY,
    X_LAST_UPDATE_DATE => :GME_TEXT_TABLE.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :GME_TEXT_TABLE.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :GME_TEXT_TABLE.LAST_UPDATE_LOGIN);
end INSERT_ROW;


/
ALTER TRIGGER "APPS"."GMA_GME_TEXT_TBL_T1" ENABLE;
