--------------------------------------------------------
--  DDL for Trigger GMA_GME_TEXT_TBL_T2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMA_GME_TEXT_TBL_T2" 
instead of update on GME_TEXT_TABLE_VL
referencing old as GME_TEXT_TABLE
for each row
begin
  GMA_GME_TEXT_TBL_PKG.UPDATE_ROW(
    X_ROW_ID => :GME_TEXT_TABLE.ROW_ID,
-- Bug #1806284 (JKB)
    X_TEXT_CODE => :GME_TEXT_TABLE.TEXT_CODE,
    X_LANG_CODE => :GME_TEXT_TABLE.LANG_CODE,
    X_PARAGRAPH_CODE => :GME_TEXT_TABLE.PARAGRAPH_CODE,
    X_SUB_PARACODE => :GME_TEXT_TABLE.SUB_PARACODE,
    X_LINE_NO => :GME_TEXT_TABLE.LINE_NO,
    X_TEXT => :GME_TEXT_TABLE.TEXT,
    X_LAST_UPDATE_DATE => :GME_TEXT_TABLE.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :GME_TEXT_TABLE.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :GME_TEXT_TABLE.LAST_UPDATE_LOGIN);
end UPDATE_ROW;


/
ALTER TRIGGER "APPS"."GMA_GME_TEXT_TBL_T2" ENABLE;
