--------------------------------------------------------
--  DDL for Trigger GMD_OPERATIONS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMD_OPERATIONS_UL" 
/* $Header: gmdoputg.sql 120.2 2005/08/26 11:50:06 txdaniel noship $ */
instead of update on GMD_OPERATIONS_VL
referencing new as GMD_OPERATIONS
for each row
begin
  GMD_OPERATIONS_PKG.UPDATE_ROW(
    X_OPRN_ID => :GMD_OPERATIONS.OPRN_ID,
    X_ATTRIBUTE30 => :GMD_OPERATIONS.ATTRIBUTE30,
    X_ATTRIBUTE_CATEGORY => :GMD_OPERATIONS.ATTRIBUTE_CATEGORY,
    X_ATTRIBUTE25 => :GMD_OPERATIONS.ATTRIBUTE25,
    X_ATTRIBUTE26 => :GMD_OPERATIONS.ATTRIBUTE26,
    X_ATTRIBUTE27 => :GMD_OPERATIONS.ATTRIBUTE27,
    X_ATTRIBUTE28 => :GMD_OPERATIONS.ATTRIBUTE28,
    X_ATTRIBUTE29 => :GMD_OPERATIONS.ATTRIBUTE29,
    X_ATTRIBUTE22 => :GMD_OPERATIONS.ATTRIBUTE22,
    X_ATTRIBUTE23 => :GMD_OPERATIONS.ATTRIBUTE23,
    X_ATTRIBUTE24 => :GMD_OPERATIONS.ATTRIBUTE24,
    X_OPRN_NO => :GMD_OPERATIONS.OPRN_NO,
    X_OPRN_VERS => :GMD_OPERATIONS.OPRN_VERS,
    X_PROCESS_QTY_UOM => :GMD_OPERATIONS.PROCESS_QTY_UOM,
    X_OPRN_CLASS => :GMD_OPERATIONS.OPRN_CLASS,
    X_INACTIVE_IND => :GMD_OPERATIONS.INACTIVE_IND,
    X_EFFECTIVE_START_DATE => :GMD_OPERATIONS.EFFECTIVE_START_DATE,
    X_EFFECTIVE_END_DATE => :GMD_OPERATIONS.EFFECTIVE_END_DATE,
    X_DELETE_MARK => :GMD_OPERATIONS.DELETE_MARK,
    X_TEXT_CODE => :GMD_OPERATIONS.TEXT_CODE,
    X_ATTRIBUTE1 => :GMD_OPERATIONS.ATTRIBUTE1,
    X_ATTRIBUTE2 => :GMD_OPERATIONS.ATTRIBUTE2,
    X_ATTRIBUTE3 => :GMD_OPERATIONS.ATTRIBUTE3,
    X_ATTRIBUTE4 => :GMD_OPERATIONS.ATTRIBUTE4,
    X_ATTRIBUTE5 => :GMD_OPERATIONS.ATTRIBUTE5,
    X_ATTRIBUTE6 => :GMD_OPERATIONS.ATTRIBUTE6,
    X_ATTRIBUTE7 => :GMD_OPERATIONS.ATTRIBUTE7,
    X_ATTRIBUTE8 => :GMD_OPERATIONS.ATTRIBUTE8,
    X_ATTRIBUTE9 => :GMD_OPERATIONS.ATTRIBUTE9,
    X_ATTRIBUTE10 => :GMD_OPERATIONS.ATTRIBUTE10,
    X_ATTRIBUTE11 => :GMD_OPERATIONS.ATTRIBUTE11,
    X_ATTRIBUTE12 => :GMD_OPERATIONS.ATTRIBUTE12,
    X_ATTRIBUTE13 => :GMD_OPERATIONS.ATTRIBUTE13,
    X_ATTRIBUTE14 => :GMD_OPERATIONS.ATTRIBUTE14,
    X_ATTRIBUTE15 => :GMD_OPERATIONS.ATTRIBUTE15,
    X_ATTRIBUTE16 => :GMD_OPERATIONS.ATTRIBUTE16,
    X_ATTRIBUTE17 => :GMD_OPERATIONS.ATTRIBUTE17,
    X_ATTRIBUTE18 => :GMD_OPERATIONS.ATTRIBUTE18,
    X_ATTRIBUTE19 => :GMD_OPERATIONS.ATTRIBUTE19,
    X_ATTRIBUTE20 => :GMD_OPERATIONS.ATTRIBUTE20,
    X_ATTRIBUTE21 => :GMD_OPERATIONS.ATTRIBUTE21,
    X_OPERATION_STATUS => :GMD_OPERATIONS.OPERATION_STATUS,
    X_OWNER_ORGANIZATION_ID => :GMD_OPERATIONS.OWNER_ORGANIZATION_ID,
    X_OPRN_DESC => :GMD_OPERATIONS.OPRN_DESC,
    X_LAST_UPDATE_DATE => :GMD_OPERATIONS.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :GMD_OPERATIONS.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :GMD_OPERATIONS.LAST_UPDATE_LOGIN);
end UPDATE_ROW;


/
ALTER TRIGGER "APPS"."GMD_OPERATIONS_UL" ENABLE;
