--------------------------------------------------------
--  DDL for Trigger GMD_SPEC_TESTS_B_AI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMD_SPEC_TESTS_B_AI" AFTER INSERT ON "GMD"."GMD_SPEC_TESTS_B" FOR EACH ROW BEGIN IF fnd_audit_pkg.audit_on THEN GMD_SPEC_TESTS_B_AIP(:old.SPEC_ID,:old.TEST_ID,:old.ABOVE_MAX_ACTION_CODE,:old.ABOVE_MIN_ACTION_CODE,:old.ABOVE_SPEC_MAX,:old.ABOVE_SPEC_MIN,:old.BELOW_MAX_ACTION_CODE,:old.BELOW_MIN_ACTION_CODE,:old.BELOW_SPEC_MAX,:old.BELOW_SPEC_MIN,:old.MAX_VALUE_CHAR,:old.MAX_VALUE_NUM,:old.MIN_VALUE_CHAR,:old.MIN_VALUE_NUM,:old.OUT_OF_SPEC_ACTION,:old.TARGET_VALUE_CHAR,:old.TARGET_VALUE_NUM,:old.TEST_METHOD_ID,:new.SPEC_ID,:new.TEST_ID,:new.ABOVE_MAX_ACTION_CODE,:new.ABOVE_MIN_ACTION_CODE,:new.ABOVE_SPEC_MAX,:new.ABOVE_SPEC_MIN,:new.BELOW_MAX_ACTION_CODE,:new.BELOW_MIN_ACTION_CODE,:new.BELOW_SPEC_MAX,:new.BELOW_SPEC_MIN,:new.MAX_VALUE_CHAR,:new.MAX_VALUE_NUM,:new.MIN_VALUE_CHAR,:new.MIN_VALUE_NUM,:new.OUT_OF_SPEC_ACTION,:new.TARGET_VALUE_CHAR,:new.TARGET_VALUE_NUM,:new.TEST_METHOD_ID);END IF;END;

/
ALTER TRIGGER "APPS"."GMD_SPEC_TESTS_B_AI" ENABLE;
