--------------------------------------------------------
--  DDL for Trigger GMD_ROUTINGS_B_AI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMD_ROUTINGS_B_AI" AFTER INSERT ON "GMD"."GMD_ROUTINGS_B" FOR EACH ROW BEGIN IF fnd_audit_pkg.audit_on THEN GMD_ROUTINGS_B_AIP(:old.ROUTING_ID,:old.DELETE_MARK,:old.EFFECTIVE_END_DATE,:old.EFFECTIVE_START_DATE,:old.ITEM_UM,:old.OWNER_ID,:old.OWNER_ORGN_CODE,:old.PROCESS_LOSS,:old.ROUTING_CLASS,:old.ROUTING_NO,:old.ROUTING_QTY,:old.ROUTING_STATUS,:old.ROUTING_VERS,:new.ROUTING_ID,:new.DELETE_MARK,:new.EFFECTIVE_END_DATE,:new.EFFECTIVE_START_DATE,:new.ITEM_UM,:new.OWNER_ID,:new.OWNER_ORGN_CODE,:new.PROCESS_LOSS,:new.ROUTING_CLASS,:new.ROUTING_NO,:new.ROUTING_QTY,:new.ROUTING_STATUS,:new.ROUTING_VERS);END IF;END;

/
ALTER TRIGGER "APPS"."GMD_ROUTINGS_B_AI" ENABLE;
