--------------------------------------------------------
--  DDL for Trigger GMD_ROUTINGS_B_AT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMD_ROUTINGS_B_AT" BEFORE UPDATE OF ROUTING_ID,DELETE_MARK,EFFECTIVE_END_DATE,EFFECTIVE_START_DATE,ITEM_UM,OWNER_ID,OWNER_ORGN_CODE,PROCESS_LOSS,ROUTING_CLASS,ROUTING_NO,ROUTING_QTY,ROUTING_STATUS,ROUTING_VERS ON "GMD"."GMD_ROUTINGS_B" BEGIN IF fnd_global.audit_active THEN fnd_audit_pkg.audit_on := TRUE;ELSE fnd_audit_pkg.audit_on := FALSE;END IF;END;

/
ALTER TRIGGER "APPS"."GMD_ROUTINGS_B_AT" ENABLE;
