--------------------------------------------------------
--  DDL for Trigger GME_MATERIAL_DETAILS_AU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GME_MATERIAL_DETAILS_AU" AFTER UPDATE OF MATERIAL_DETAIL_ID,ACTUAL_QTY,BATCH_ID,ITEM_UM,LINE_NO,LINE_TYPE,ORIGINAL_QTY,PLAN_QTY,WIP_PLAN_QTY ON "GME"."GME_MATERIAL_DETAILS" FOR EACH ROW BEGIN IF fnd_audit_pkg.audit_on THEN GME_MATERIAL_DETAILS_AUP(:old.MATERIAL_DETAIL_ID,:old.ACTUAL_QTY,:old.BATCH_ID,:old.ITEM_UM,:old.LINE_NO,:old.LINE_TYPE,:old.ORIGINAL_QTY,:old.PLAN_QTY,:old.WIP_PLAN_QTY,:new.MATERIAL_DETAIL_ID,:new.ACTUAL_QTY,:new.BATCH_ID,:new.ITEM_UM,:new.LINE_NO,:new.LINE_TYPE,:new.ORIGINAL_QTY,:new.PLAN_QTY,:new.WIP_PLAN_QTY);END IF;END;

/
ALTER TRIGGER "APPS"."GME_MATERIAL_DETAILS_AU" ENABLE;
