--------------------------------------------------------
--  DDL for Trigger GML_OP_PRSL_TYP_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GML_OP_PRSL_TYP_T1" 
/* $Header: GMLPRSLT.sql 115.1 99/07/16 06:17:57 porting ship  $ */
instead of insert on OP_PRSL_TYP_VL
referencing new as OP_PRSL_TYP
for each row

declare
  row_id rowid;
begin
  GML_OP_PRSL_TYP_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_PRESALES_ORD_TYPE => :OP_PRSL_TYP.PRESALES_ORD_TYPE,
    X_LANG_CODE => :OP_PRSL_TYP.LANG_CODE,
    X_RELEASE_SCHED_REQD => :OP_PRSL_TYP.RELEASE_SCHED_REQD,
    X_PRICELIST_IND => :OP_PRSL_TYP.PRICELIST_IND,
    X_TRANS_CNT => :OP_PRSL_TYP.TRANS_CNT,
    X_TEXT_CODE => :OP_PRSL_TYP.TEXT_CODE,
    X_DELETE_MARK => :OP_PRSL_TYP.DELETE_MARK,
    X_PRESALES_ORD_CODE => :OP_PRSL_TYP.PRESALES_ORD_CODE,
    X_PRESALES_ORD_DESC => :OP_PRSL_TYP.PRESALES_ORD_DESC,
    X_CREATION_DATE => :OP_PRSL_TYP.CREATION_DATE,
    X_CREATED_BY => :OP_PRSL_TYP.CREATED_BY,
    X_LAST_UPDATE_DATE => :OP_PRSL_TYP.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :OP_PRSL_TYP.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :OP_PRSL_TYP.LAST_UPDATE_LOGIN);
end INSERT_ROW;



/
ALTER TRIGGER "APPS"."GML_OP_PRSL_TYP_T1" ENABLE;
