--------------------------------------------------------
--  DDL for Trigger GML_OP_ORDR_TYP_T2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GML_OP_ORDR_TYP_T2" 
instead of update on OP_ORDR_TYP_VL
referencing old as OP_ORDR_TYP
for each row

begin
  GML_OP_ORDR_TYP_PKG.UPDATE_ROW(
    X_ORDER_TYPE => :OP_ORDR_TYP.ORDER_TYPE,
    X_LANG_CODE => :OP_ORDR_TYP.LANG_CODE,
    X_INVEN_TRANS_TYPE => :OP_ORDR_TYP.INVEN_TRANS_TYPE,
    X_SHIPMENT_IND => :OP_ORDR_TYP.SHIPMENT_IND,
    X_INVOICE_IND => :OP_ORDR_TYP.INVOICE_IND,
    X_PICKINGLST_IND => :OP_ORDR_TYP.PICKINGLST_IND,
    X_EXPORTDOC_IND => :OP_ORDR_TYP.EXPORTDOC_IND,
    X_TOTALORD_IND => :OP_ORDR_TYP.TOTALORD_IND,
    X_UPDATE_SALESHIST => :OP_ORDR_TYP.UPDATE_SALESHIST,
    X_CREDITCHK_TYPE => :OP_ORDR_TYP.CREDITCHK_TYPE,
    X_PRICE_ORDER => :OP_ORDR_TYP.PRICE_ORDER,
    X_CALC_COMM_IND => :OP_ORDR_TYP.CALC_COMM_IND,
    X_CALC_TAX_IND => :OP_ORDR_TYP.CALC_TAX_IND,
    X_PRODORDR_IND => :OP_ORDR_TYP.PRODORDR_IND,
    X_SHIPTO_REQUIRED => :OP_ORDR_TYP.SHIPTO_REQUIRED,
    X_UPDATE_AUDITTRAIL => :OP_ORDR_TYP.UPDATE_AUDITTRAIL,
    X_ORDER_LEADTIME => :OP_ORDR_TYP.ORDER_LEADTIME,
    X_TRANS_CNT => :OP_ORDR_TYP.TRANS_CNT,
    X_TEXT_CODE => :OP_ORDR_TYP.TEXT_CODE,
    X_DELETE_MARK => :OP_ORDR_TYP.DELETE_MARK,
    X_ORDER_TYPE_CODE => :OP_ORDR_TYP.ORDER_TYPE_CODE,
    X_ORDER_TYPE_DESC => :OP_ORDR_TYP.ORDER_TYPE_DESC,
    X_LAST_UPDATE_DATE => :OP_ORDR_TYP.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :OP_ORDR_TYP.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :OP_ORDR_TYP.LAST_UPDATE_LOGIN);
end UPDATE_ROW;



/
ALTER TRIGGER "APPS"."GML_OP_ORDR_TYP_T2" ENABLE;
