--------------------------------------------------------
--  DDL for Trigger GMO_INSTR_SET_DEFN_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMO_INSTR_SET_DEFN_UL" 
/* $Header: GMOINSUT.sql 120.0 2005/06/29 04:21 shthakke noship $ */

instead of update on GMO_INSTR_SET_DEFN_VL
referencing new as GMO_INSTR_SET_DEFN
for each row
begin
  GMO_INSTR_SET_DEFN_PKG.UPDATE_ROW(
    X_INSTRUCTION_SET_ID => :GMO_INSTR_SET_DEFN.INSTRUCTION_SET_ID,
    X_INSTRUCTION_TYPE => :GMO_INSTR_SET_DEFN.INSTRUCTION_TYPE,
    X_INSTR_SET_NAME => :GMO_INSTR_SET_DEFN.INSTR_SET_NAME,
    X_ENTITY_NAME => :GMO_INSTR_SET_DEFN.ENTITY_NAME,
    X_ENTITY_KEY => :GMO_INSTR_SET_DEFN.ENTITY_KEY,
    X_ACKN_STATUS => :GMO_INSTR_SET_DEFN.ACKN_STATUS,
    X_ORIG_SOURCE => :GMO_INSTR_SET_DEFN.ORIG_SOURCE,
    X_ORIG_SOURCE_ID => :GMO_INSTR_SET_DEFN.ORIG_SOURCE_ID,
    X_INSTR_SET_DESC => :GMO_INSTR_SET_DEFN.INSTR_SET_DESC,
    X_LAST_UPDATE_DATE => :GMO_INSTR_SET_DEFN.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :GMO_INSTR_SET_DEFN.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :GMO_INSTR_SET_DEFN.LAST_UPDATE_LOGIN);
end UPDATE_ROW;


/
ALTER TRIGGER "APPS"."GMO_INSTR_SET_DEFN_UL" ENABLE;
