--------------------------------------------------------
--  DDL for Trigger GMO_INSTR_DEFN_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMO_INSTR_DEFN_IL" 
/* $Header: GMOINDIT.sql 120.0 2005/06/29 04:22 shthakke noship $ */

instead of insert on GMO_INSTR_DEFN_VL
referencing new as GMO_INSTR_DEFN_B
for each row
declare
  row_id rowid;
begin
  GMO_INSTR_DEFN_PKG.INSERT_ROW(
    X_ROWID => ROW_ID,
    X_INSTRUCTION_ID => :GMO_INSTR_DEFN_B.INSTRUCTION_ID,
    X_INSTRUCTION_SET_ID => :GMO_INSTR_DEFN_B.INSTRUCTION_SET_ID,
    X_INSTR_SEQ => :GMO_INSTR_DEFN_B.INSTR_SEQ,
    X_TASK_ID => :GMO_INSTR_DEFN_B.TASK_ID,
    X_TASK_ATTRIBUTE_ID => :GMO_INSTR_DEFN_B.TASK_ATTRIBUTE_ID,
    X_TASK_ATTRIBUTE => :GMO_INSTR_DEFN_B.TASK_ATTRIBUTE,
    X_INSTR_ACKN_TYPE => :GMO_INSTR_DEFN_B.INSTR_ACKN_TYPE,
    X_INSTR_NUMBER => :GMO_INSTR_DEFN_B.INSTR_NUMBER,
    X_INSTRUCTION_TEXT => :GMO_INSTR_DEFN_B.INSTRUCTION_TEXT,
    X_TASK_LABEL => :GMO_INSTR_DEFN_B.TASK_LABEL,
    X_CREATION_DATE => :GMO_INSTR_DEFN_B.CREATION_DATE,
    X_CREATED_BY => :GMO_INSTR_DEFN_B.CREATED_BY,
    X_LAST_UPDATE_DATE => :GMO_INSTR_DEFN_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :GMO_INSTR_DEFN_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :GMO_INSTR_DEFN_B.LAST_UPDATE_LOGIN);
end INSERT_ROW;


/
ALTER TRIGGER "APPS"."GMO_INSTR_DEFN_IL" ENABLE;
