--------------------------------------------------------
--  DDL for Trigger GMO_INSTR_TASK_ATTR_COLS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMO_INSTR_TASK_ATTR_COLS_UL" 
/* $Header: GMOTSAUT.sql 120.0 2005/06/29 04:25 shthakke noship $ */

instead of update on GMO_INSTR_TASK_ATTR_COLS_VL
referencing new as GMO_INSTR_TASK_ATTR_COLS_B
for each row
begin
  GMO_INSTR_TASK_ATTR_COLS_PKG.UPDATE_ROW(
    X_ATTR_COL_SEQ => :GMO_INSTR_TASK_ATTR_COLS_B.ATTR_COL_SEQ,
    X_TASK_NAME => :GMO_INSTR_TASK_ATTR_COLS_B.TASK_NAME,
    X_COLUMN_NO => :GMO_INSTR_TASK_ATTR_COLS_B.COLUMN_NO,
    X_ENTITY_NAME => :GMO_INSTR_TASK_ATTR_COLS_B.ENTITY_NAME,
    X_COLUMN_HEADING => :GMO_INSTR_TASK_ATTR_COLS_B.COLUMN_HEADING,
    X_LAST_UPDATE_DATE => :GMO_INSTR_TASK_ATTR_COLS_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :GMO_INSTR_TASK_ATTR_COLS_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :GMO_INSTR_TASK_ATTR_COLS_B.LAST_UPDATE_LOGIN);
end UPDATE_ROW;


/
ALTER TRIGGER "APPS"."GMO_INSTR_TASK_ATTR_COLS_UL" ENABLE;
