--------------------------------------------------------
--  DDL for Trigger GMO_INSTR_INSTANCE_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."GMO_INSTR_INSTANCE_UL" 
/* $Header: GMOINIUT.sql 120.0 2005/06/29 04:24 shthakke noship $ */

instead of update on GMO_INSTR_INSTANCE_VL
referencing new as GMO_INSTR_INSTANCE_B
for each row
begin
  GMO_INSTR_INSTANCE_PKG.UPDATE_ROW(
    X_INSTRUCTION_ID => :GMO_INSTR_INSTANCE_B.INSTRUCTION_ID,
    X_OPERATOR_ACKN => :GMO_INSTR_INSTANCE_B.OPERATOR_ACKN,
    X_TASK_ATTRIBUTE => :GMO_INSTR_INSTANCE_B.TASK_ATTRIBUTE,
    X_TASK_ATTRIBUTE_ID => :GMO_INSTR_INSTANCE_B.TASK_ATTRIBUTE_ID,
    X_INSTRUCTION_SET_ID => :GMO_INSTR_INSTANCE_B.INSTRUCTION_SET_ID,
    X_INSTR_NUMBER => :GMO_INSTR_INSTANCE_B.INSTR_NUMBER,
    X_INSTR_STATUS => :GMO_INSTR_INSTANCE_B.INSTR_STATUS,
    X_TASK_ID => :GMO_INSTR_INSTANCE_B.TASK_ID,
    X_TASK_ACKN_DATE => :GMO_INSTR_INSTANCE_B.TASK_ACKN_DATE,
    X_TASK_ACKN_STATUS => :GMO_INSTR_INSTANCE_B.TASK_ACKN_STATUS,
    X_INSTR_SEQ => :GMO_INSTR_INSTANCE_B.INSTR_SEQ,
    X_INSTR_ACKN_TYPE => :GMO_INSTR_INSTANCE_B.INSTR_ACKN_TYPE,
    X_INSTRUCTION_TEXT => :GMO_INSTR_INSTANCE_B.INSTRUCTION_TEXT,
    X_COMMENTS => :GMO_INSTR_INSTANCE_B.COMMENTS,
    X_TASK_LABEL => :GMO_INSTR_INSTANCE_B.TASK_LABEL,
    X_LAST_UPDATE_DATE => :GMO_INSTR_INSTANCE_B.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :GMO_INSTR_INSTANCE_B.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :GMO_INSTR_INSTANCE_B.LAST_UPDATE_LOGIN);
end UPDATE_ROW;


/
ALTER TRIGGER "APPS"."GMO_INSTR_INSTANCE_UL" ENABLE;
