--------------------------------------------------------
--  DDL for Trigger IBY_ACCOUNT_OWNERS_AI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IBY_ACCOUNT_OWNERS_AI" AFTER INSERT ON "IBY"."IBY_ACCOUNT_OWNERS" FOR EACH ROW BEGIN IF fnd_audit_pkg.audit_on THEN IBY_ACCOUNT_OWNERS_AIP(:old.ACCOUNT_OWNER_ID,:old.ACCOUNT_OWNER_PARTY_ID,:old.END_DATE,:old.EXT_BANK_ACCOUNT_ID,:new.ACCOUNT_OWNER_ID,:new.ACCOUNT_OWNER_PARTY_ID,:new.END_DATE,:new.EXT_BANK_ACCOUNT_ID);END IF;END;

/
ALTER TRIGGER "APPS"."IBY_ACCOUNT_OWNERS_AI" ENABLE;
