--------------------------------------------------------
--  DDL for Trigger IBY_EXT_BANK_ACCOUNTS_AU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IBY_EXT_BANK_ACCOUNTS_AU" AFTER UPDATE OF EXT_BANK_ACCOUNT_ID,BANK_ACCOUNT_NUM,END_DATE,IBAN,START_DATE ON "IBY"."IBY_EXT_BANK_ACCOUNTS" FOR EACH ROW BEGIN IF fnd_audit_pkg.audit_on THEN IBY_EXT_BANK_ACCOUNTS_AUP(:old.EXT_BANK_ACCOUNT_ID,:old.BANK_ACCOUNT_NUM,:old.END_DATE,:old.IBAN,:old.START_DATE,:new.EXT_BANK_ACCOUNT_ID,:new.BANK_ACCOUNT_NUM,:new.END_DATE,:new.IBAN,:new.START_DATE);END IF;END;

/
ALTER TRIGGER "APPS"."IBY_EXT_BANK_ACCOUNTS_AU" ENABLE;
