--------------------------------------------------------
--  DDL for Trigger IC_ITEM_MST_B_AU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IC_ITEM_MST_B_AU" AFTER UPDATE OF ITEM_ID,DELETE_MARK,EXPERIMENTAL_IND,INACTIVE_IND,ITEM_NO,LOT_STATUS,QC_GRADE,RETEST_INTERVAL,SHELF_LIFE ON "GMI"."IC_ITEM_MST_B" FOR EACH ROW BEGIN IF fnd_audit_pkg.audit_on THEN IC_ITEM_MST_B_AUP(:old.ITEM_ID,:old.DELETE_MARK,:old.EXPERIMENTAL_IND,:old.INACTIVE_IND,:old.ITEM_NO,:old.LOT_STATUS,:old.QC_GRADE,:old.RETEST_INTERVAL,:old.SHELF_LIFE,:new.ITEM_ID,:new.DELETE_MARK,:new.EXPERIMENTAL_IND,:new.INACTIVE_IND,:new.ITEM_NO,:new.LOT_STATUS,:new.QC_GRADE,:new.RETEST_INTERVAL,:new.SHELF_LIFE);END IF;END;

/
ALTER TRIGGER "APPS"."IC_ITEM_MST_B_AU" ENABLE;
