--------------------------------------------------------
--  DDL for Trigger IEB_SERVICE_PLANS_ALERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IEB_SERVICE_PLANS_ALERT" 
 AFTER INSERT OR UPDATE OF SVCPLN_ID, DIRECTION, TREATMENT, SERVICE_PLAN_NAME
 ON "IEB"."IEB_SERVICE_PLANS"
 FOR EACH ROW
BEGIN
DBMS_ALERT.SIGNAL('IEB_SERVICE_PLANS_ALERT', TO_CHAR(:new.SVCPLN_ID));
END IEB_SERVICE_PLANS_ALERT;



/
ALTER TRIGGER "APPS"."IEB_SERVICE_PLANS_ALERT" ENABLE;
