--------------------------------------------------------
--  DDL for Trigger IEB_WBST_WBSCR_ALERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IEB_WBST_WBSCR_ALERT" 
 AFTER INSERT OR UPDATE OF WBSKTR_WBSKTR_ID, WBSCRULE_WBSCRULE_ID
 ON "IEB"."IEB_WBST_WB_SC_RULES"
 FOR EACH ROW
BEGIN
DBMS_ALERT.SIGNAL('IEB_WBST_WBSCR_ALERT', CONCAT(TO_CHAR(:new.WBSKTR_WBSKTR_ID), CONCAT(':', TO_CHAR(:new.WBSCRULE_WBSCRULE_ID))));
END IEB_WBST_WBSCR_ALERT;



/
ALTER TRIGGER "APPS"."IEB_WBST_WBSCR_ALERT" ENABLE;
