--------------------------------------------------------
--  DDL for Trigger IEB_SVC_PLAN_DELETE_ALERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IEB_SVC_PLAN_DELETE_ALERT" 
 AFTER DELETE
 ON "IEB"."IEB_SERVICE_PLANS"
 FOR EACH ROW
BEGIN
DBMS_ALERT.SIGNAL('IEB_SVC_PLAN_DELETE_ALERT', TO_CHAR(:old.SVCPLN_ID));
END IEB_SVC_PLAN_DELETE_ALERT;



/
ALTER TRIGGER "APPS"."IEB_SVC_PLAN_DELETE_ALERT" ENABLE;
