--------------------------------------------------------
--  DDL for Trigger IEB_OUTB_SVC_COVERAGES_ALERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IEB_OUTB_SVC_COVERAGES_ALERT" 
 AFTER DELETE OR INSERT OR UPDATE OF BEGIN_TIME_HHMM, END_TIME_HHMM, MIN_AGENT, QUOTA, SVCPLN_SVCPLN_ID, OSVCCOV_ID, SCHEDULE_TYPE, REGULAR_SCHD_DAY, SPEC_SCHD_DATE
 ON "IEB"."IEB_OUTB_SVC_COVERAGES"
BEGIN
DBMS_ALERT.SIGNAL('IEB_OUTB_SVC_COVERAGES_ALERT', 'IEB_OUTB_SVC_COVERAGES_ALERT');
END IEB_OUTB_SVC_COVERAGES_ALERT;



/
ALTER TRIGGER "APPS"."IEB_OUTB_SVC_COVERAGES_ALERT" ENABLE;
