--------------------------------------------------------
--  DDL for Trigger IEB_WB_SC_RULES_ALERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IEB_WB_SC_RULES_ALERT" 
 AFTER INSERT OR UPDATE OF WBSC_WBSC_ID, CLASSIFICATION, WBSCRULE_ID, ARRIVAL_ADDRESS, RULE_TYPE, SKILL_INCLUDED_Y_N
 ON "IEB"."IEB_WB_SVC_CAT_RULES"
 FOR EACH ROW
BEGIN
DBMS_ALERT.SIGNAL('IEB_WB_SC_RULES_ALERT',TO_CHAR(:new.WBSCRULE_ID));
END IEB_WB_SC_RULES_ALERT;



/
ALTER TRIGGER "APPS"."IEB_WB_SC_RULES_ALERT" ENABLE;
