--------------------------------------------------------
--  DDL for Trigger IEB_WB_SKLTRN_DELETE_ALERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IEB_WB_SKLTRN_DELETE_ALERT" 
 AFTER DELETE
 ON "IEB"."IEB_WB_SKILL_TRANS"
 FOR EACH ROW
BEGIN
DBMS_ALERT.SIGNAL('IEB_WB_SKLTRN_DELETE_ALERT', TO_CHAR(:old.WBSKTR_ID));
END IEB_WB_SKLTRN_DELETE_ALERT;



/
ALTER TRIGGER "APPS"."IEB_WB_SKLTRN_DELETE_ALERT" ENABLE;
