--------------------------------------------------------
--  DDL for Trigger IEB_WB_SVC_CATS_ALERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IEB_WB_SVC_CATS_ALERT" 
 AFTER INSERT OR UPDATE OF CAMPAIGN_NAME, CAMPAIGN_SERVER_NAME, PRIORITY, DEPTH, WBSVR_WBSVR_ID, PARENT_ID, SVCPLN_SVCPLN_ID, WBSC_ID, SERVICE_CATEGORY_NAME, ACTIVE_Y_N, MEDIA_TYPE
 ON "IEB"."IEB_WB_SVC_CATS"
 FOR EACH ROW
BEGIN
DBMS_ALERT.SIGNAL('IEB_WB_SVC_CATS_ALERT', TO_CHAR(:new.WBSC_ID));
END IEB_WB_SVC_CATS_ALERT;



/
ALTER TRIGGER "APPS"."IEB_WB_SVC_CATS_ALERT" ENABLE;
