--------------------------------------------------------
--  DDL for Trigger IGI_BUD_JOURNAL_LINES_T2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IGI_BUD_JOURNAL_LINES_T2" 
AFTER UPDATE ON "IGI"."IGI_BUD_JOURNAL_LINES"
FOR EACH ROW
  WHEN (NEW.RECORD_TYPE = 'B') BEGIN

    IF IGI_GEN.IS_REQ_INSTALLED('BUD') THEN

	DELETE	IGI_BUD_JOURNAL_PERIODS
	WHERE	BE_HEADER_ID = :OLD.BE_HEADER_ID
	AND	BE_LINE_NUM = :OLD.BE_LINE_NUM;

	DELETE	GL_INTERFACE
	WHERE	REFERENCE22 = to_char(:OLD.BE_BATCH_ID)
	AND	REFERENCE29 = to_char(:OLD.BE_HEADER_ID)
	AND	REFERENCE30 = to_char(:OLD.BE_LINE_NUM);

	IGI_BUD.bud_profile_insert
			( :NEW.SET_OF_BOOKS_ID
			, :NEW.BE_BATCH_ID
			, :NEW.BE_HEADER_ID
			, :NEW.BE_LINE_NUM
			, :NEW.CODE_COMBINATION_ID
			, :NEW.PROFILE_CODE
			, :NEW.START_PERIOD
			, :NEW.ENTERED_DR
			, :NEW.ENTERED_CR
			, :NEW.DESCRIPTION
			, :NEW.REASON_CODE
			, :NEW.RECURRING_ENTRY
			, :NEW.FYE_PYE_ENTRY
			, :NEW.NEXT_YEAR_BUDGET
			);
     END IF; -- is req installed check
END;

/
ALTER TRIGGER "APPS"."IGI_BUD_JOURNAL_LINES_T2" ENABLE;
