--------------------------------------------------------
--  DDL for Trigger IGI_DOS_TRX_HEADERS_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IGI_DOS_TRX_HEADERS_T1" 
BEFORE UPDATE
  OF trx_status
ON "IGI"."IGI_DOS_TRX_HEADERS"
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
declare
x_history_trx_id number;

Begin

--
-- Bug 2897525 Start(1)
--
--       select   igi_dos_trx_history_s.nextval
       SELECT   igi_dos_trx_headers_hist_s.NEXTVAL
--
-- Bug 2897525 End(1)
--
       into     x_history_trx_id
       from     dual;

        insert into igi_dos_trx_headers_hist
                 (
                  sob_id                     ,
                  trx_id                     ,
                  dossier_name               ,
                  trx_number                 ,
                  packet_id                  ,
                  trx_status                 ,
                  dossier_id                 ,
 		  dossier_transaction_name   ,
                  funds_status               ,
                  description                ,
                  attribute_category         ,
                  attribute1                 ,
                  attribute2                 ,
                  attribute3                 ,
                  attribute4                 ,
                  attribute5                 ,
                  attribute6                 ,
                  attribute7                 ,
                  attribute8                 ,
                  attribute9                 ,
                  attribute10                ,
                  history_trx_id             ,
                  last_update_date           ,
                  last_updated_by            ,
                  created_by                 ,
                  creation_date              ,
                  last_update_login          ,
                  parent_trx_id              ,
                  parent_trx_number          ,
                  attribute11                ,
                  attribute12                ,
                  attribute13                ,
                  attribute14                ,
                  attribute15                ,
                  attribute16                ,
                  attribute17                ,
                  attribute18                ,
                  attribute19                ,
                  attribute20                ,
                  attribute21                ,
                  attribute22                ,
                  attribute23                ,
                  attribute24                ,
                  attribute25                ,
                  attribute26                ,
                  attribute27                ,
                  attribute28                ,
                  attribute29                ,
                  attribute30
                   )
                   values (
                    :new.sob_id                     ,
                    :new.trx_id                     ,
                    :new.dossier_name               ,
                    :new.trx_number                 ,
                    :new.packet_id                  ,
                    :new.trx_status                 ,
                    :new.dossier_id                 ,
                    :new.dossier_transaction_name   ,
                    :new.funds_status               ,
                    :new.description                ,
                    :new.attribute_category         ,
                    :new.attribute1                 ,
                    :new.attribute2                 ,
                    :new.attribute3                 ,
                    :new.attribute4                 ,
                    :new.attribute5                 ,
                    :new.attribute6                 ,
                    :new.attribute7                 ,
                    :new.attribute8                 ,
                    :new.attribute9                 ,
                    :new.attribute10                ,
                    x_history_trx_id                ,
                    :new.last_update_date           ,
                    :new.last_updated_by            ,
                    :new.created_by                 ,
                    :new.creation_date              ,
                    :new.last_update_login          ,
                    :new.parent_trx_id              ,
                    :new.parent_trx_number          ,
                    :new.attribute11                ,
                    :new.attribute12                ,
                    :new.attribute13                ,
                    :new.attribute14                ,
                    :new.attribute15                ,
                    :new.attribute16                ,
                    :new.attribute17                ,
                    :new.attribute18                ,
                    :new.attribute19                ,
                    :new.attribute20                ,
                    :new.attribute21                ,
                    :new.attribute22                ,
                    :new.attribute23                ,
                    :new.attribute24                ,
                    :new.attribute25                ,
                    :new.attribute26                ,
                    :new.attribute27                ,
                    :new.attribute28                ,
                    :new.attribute29                ,
                    :new.attribute30
                  );



INSERT INTO igi_dos_trx_sources_hist
 (
  sob_id                  ,
  trx_id                  ,
  source_trx_id           ,
  source_id               ,
  code_combination_id     ,
  profile_code            ,
  budget_org_id           ,
  budget_entity_id        ,
  budget_amount           ,
  funds_available         ,
  new_balance             ,
  currency_code           ,
  visible_segments        ,
  actual_segments         ,
  mrc_budget_amount       ,
  mrc_budget_amt_exch_rate      ,
  mrc_budget_amt_exch_rate_type  ,
  mrc_budget_amt_exch_date   ,
  mrc_budget_amt_exch_status  ,
  mrc_funds_avail            ,
  mrc_funds_avail_exch_rate  ,
  mrc_funds_avail_exch_rate_type  ,
  mrc_funds_avail_exch_date  ,
  mrc_funds_avail_exch_status  ,
  mrc_new_balance            ,
  mrc_new_balance_exch_rate  ,
  mrc_new_balance_exch_rate_type  ,
  mrc_new_balance_exch_date  ,
  mrc_new_balance_exch_status  ,
  budget_name                ,
  dossier_id                 ,
  budget_version_id          ,
  period_name                ,
  status                     ,
  group_id                   ,
  quarter_num                ,
  period_year                ,
  period_num                 ,
  history_trx_id             ,
  last_update_date           ,
  last_updated_by            ,
  created_by                 ,
  creation_date              ,
  last_update_login          ,
  line_num                   ,
  segment1                   ,
  segment2                   ,
  segment3                   ,
  segment4                   ,
  segment5                   ,
  segment6                   ,
  segment7                   ,
  segment8                   ,
  segment9                   ,
  segment10                  ,
  segment11                  ,
  segment12                  ,
  segment13                  ,
  segment14                  ,
  segment15                  ,
  segment16                  ,
  segment17                  ,
  segment18                  ,
  segment19                  ,
  segment20                  ,
  segment21                  ,
  segment22                  ,
  segment23                  ,
  segment24                  ,
  segment25                  ,
  segment26                  ,
  segment27                  ,
  segment28                  ,
  segment29                  ,
  segment30
)
  SELECT
  sob_id                  ,
  trx_id                  ,
  source_trx_id           ,
  source_id               ,
  code_combination_id     ,
  profile_code            ,
  budget_org_id           ,
  budget_entity_id        ,
  budget_amount           ,
  funds_available         ,
  new_balance             ,
  currency_code           ,
  visible_segments        ,
  actual_segments         ,
  mrc_budget_amount       ,
  mrc_budget_amt_exch_rate      ,
  mrc_budget_amt_exch_rate_type  ,
  mrc_budget_amt_exch_date   ,
  mrc_budget_amt_exch_status  ,
  mrc_funds_avail            ,
  mrc_funds_avail_exch_rate  ,
  mrc_funds_avail_exch_rate_type  ,
  mrc_funds_avail_exch_date  ,
  mrc_funds_avail_exch_status  ,
  mrc_new_balance            ,
  mrc_new_balance_exch_rate  ,
  mrc_new_balance_exch_rate_type  ,
  mrc_new_balance_exch_date  ,
  mrc_new_balance_exch_status  ,
  budget_name                ,
  dossier_id                 ,
  budget_version_id          ,
  period_name                ,
  status                     ,
  group_id                   ,
  quarter_num                ,
  period_year                ,
  period_num                 ,
  x_history_trx_id           ,
  last_update_date           ,
  last_updated_by            ,
  created_by                 ,
  creation_date              ,
  last_update_login          ,
  line_num                   ,
  segment1                   ,
  segment2                   ,
  segment3                   ,
  segment4                   ,
  segment5                   ,
  segment6                   ,
  segment7                   ,
  segment8                   ,
  segment9                   ,
  segment10                  ,
  segment11                  ,
  segment12                  ,
  segment13                  ,
  segment14                  ,
  segment15                  ,
  segment16                  ,
  segment17                  ,
  segment18                  ,
  segment19                  ,
  segment20                  ,
  segment21                  ,
  segment22                  ,
  segment23                  ,
  segment24                  ,
  segment25                  ,
  segment26                  ,
  segment27                  ,
  segment28                  ,
  segment29                  ,
  segment30
  from igi_dos_trx_sources
  where trx_id = :new.trx_id;

  insert into igi_dos_trx_dest_hist
 (
  sob_id                     ,
  trx_id                     ,
  dest_trx_id                ,
  source_id                  ,
  destination_id             ,
  code_combination_id        ,
  profile_code               ,
  budget_name                ,
  budget_entity_id           ,
  budget_amount              ,
  funds_available            ,
  new_balance                ,
  currency_code              ,
  visible_segments           ,
  actual_segments            ,
  mrc_budget_amount          ,
  mrc_budget_amt_exch_rate   ,
  mrc_budget_amt_exch_rate_type  ,
  mrc_budget_amt_exch_date   ,
  mrc_budget_amt_exch_status  ,
  mrc_funds_avail            ,
  mrc_funds_avail_exch_rate  ,
  mrc_funds_avail_exch_rate_type  ,
  mrc_funds_avail_exch_date  ,
  mrc_funds_avail_exch_status  ,
  mrc_new_balance            ,
  mrc_new_balance_exch_rate  ,
  mrc_new_balance_exch_rate_type  ,
  mrc_new_balance_exch_date  ,
  mrc_new_balance_exch_status  ,
  dossier_id                 ,
  budget_version_id          ,
  period_name                ,
  percentage                 ,
  status                     ,
  group_id                   ,
  quarter_num                ,
  period_year                ,
  period_num                 ,
  history_trx_id             ,
  last_update_date           ,
  last_updated_by            ,
  created_by                 ,
  creation_date              ,
  last_update_login          ,
  source_trx_id              ,
  line_num                   ,
  segment1                   ,
  segment2                   ,
  segment3                   ,
  segment4                   ,
  segment5                   ,
  segment6                   ,
  segment7                   ,
  segment8                   ,
  segment9                   ,
  segment10                  ,
  segment11                  ,
  segment12                  ,
  segment13                  ,
  segment14                  ,
  segment15                  ,
  segment16                  ,
  segment17                  ,
  segment18                  ,
  segment19                  ,
  segment20                  ,
  segment21                  ,
  segment22                  ,
  segment23                  ,
  segment24                  ,
  segment25                  ,
  segment26                  ,
  segment27                  ,
  segment28                  ,
  segment29                  ,
  segment30
 )
 select
  sob_id                     ,
  trx_id                     ,
  dest_trx_id                ,
  source_id                  ,
  destination_id             ,
  code_combination_id        ,
  profile_code               ,
  budget_name                ,
  budget_entity_id           ,
  budget_amount              ,
  funds_available            ,
  new_balance                ,
  currency_code              ,
  visible_segments           ,
  actual_segments            ,
  mrc_budget_amount          ,
  mrc_budget_amt_exch_rate   ,
  mrc_budget_amt_exch_rate_type  ,
  mrc_budget_amt_exch_date   ,
  mrc_budget_amt_exch_status  ,
  mrc_funds_avail            ,
  mrc_funds_avail_exch_rate  ,
  mrc_funds_avail_exch_rate_type  ,
  mrc_funds_avail_exch_date  ,
  mrc_funds_avail_exch_status  ,
  mrc_new_balance            ,
  mrc_new_balance_exch_rate  ,
  mrc_new_balance_exch_rate_type  ,
  mrc_new_balance_exch_date  ,
  mrc_new_balance_exch_status  ,
  dossier_id                 ,
  budget_version_id          ,
  period_name                ,
  percentage                 ,
  status                     ,
  group_id                   ,
  quarter_num                ,
  period_year                ,
  period_num                 ,
  x_history_trx_id           ,
  last_update_date           ,
  last_updated_by            ,
  created_by                 ,
  creation_date              ,
  last_update_login          ,
  source_trx_id              ,
  line_num                   ,
  segment1                   ,
  segment2                   ,
  segment3                   ,
  segment4                   ,
  segment5                   ,
  segment6                   ,
  segment7                   ,
  segment8                   ,
  segment9                   ,
  segment10                  ,
  segment11                  ,
  segment12                  ,
  segment13                  ,
  segment14                  ,
  segment15                  ,
  segment16                  ,
  segment17                  ,
  segment18                  ,
  segment19                  ,
  segment20                  ,
  segment21                  ,
  segment22                  ,
  segment23                  ,
  segment24                  ,
  segment25                  ,
  segment26                  ,
  segment27                  ,
  segment28                  ,
  segment29                  ,
  segment30
 from igi_dos_trx_dest
 where trx_id = :NEW.trx_id;

end;


/
ALTER TRIGGER "APPS"."IGI_DOS_TRX_HEADERS_T1" ENABLE;
