--------------------------------------------------------
--  DDL for Trigger IGI_BUD_JOURNAL_LINES_T3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."IGI_BUD_JOURNAL_LINES_T3" 
AFTER DELETE ON "IGI"."IGI_BUD_JOURNAL_LINES"
FOR EACH ROW
BEGIN

   IF IGI_GEN.IS_REQ_INSTALLED('BUD') THEN

	DELETE	IGI_BUD_JOURNAL_PERIODS
	WHERE	BE_HEADER_ID = :OLD.BE_HEADER_ID
	AND	BE_LINE_NUM = :OLD.BE_LINE_NUM;

	DELETE	GL_INTERFACE
	WHERE	REFERENCE22 = to_char(:OLD.BE_BATCH_ID)
	AND	REFERENCE29 = to_char(:OLD.BE_HEADER_ID)
	AND	REFERENCE30 = to_char(:OLD.BE_LINE_NUM);

   END IF; -- is req installed check
END;

/
ALTER TRIGGER "APPS"."IGI_BUD_JOURNAL_LINES_T3" ENABLE;
