--------------------------------------------------------
--  DDL for Trigger JTF_DAC_ROLE_PERMS_TR2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."JTF_DAC_ROLE_PERMS_TR2" 
AFTER DELETE ON JTF.JTF_DAC_ROLE_PERMS
FOR EACH ROW
BEGIN
DELETE FROM JTF_DAC_CRITERIA
  WHERE ROLE_PERM_ID = :old.ROLE_PERM_ID ;
DELETE FROM JTF_DAC_ROLE_PERM_CRIT
  WHERE ROLE_PERM_ID = :old.ROLE_PERM_ID ;

END ;


/
ALTER TRIGGER "APPS"."JTF_DAC_ROLE_PERMS_TR2" ENABLE;
