--------------------------------------------------------
--  DDL for Trigger JTF_AUTH_DOMAINS_B_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."JTF_AUTH_DOMAINS_B_T1" 
AFTER DELETE ON JTF.JTF_AUTH_DOMAINS_B
FOR EACH ROW
BEGIN
DELETE FROM JTF_AUTH_PRINCIPAL_MAPS
  WHERE JTF_AUTH_PRINCIPAL_MAPS.JTF_AUTH_DOMAIN_ID = :old.JTF_AUTH_DOMAIN_ID ;
DELETE FROM JTF_AUTH_DOMAINS_TL
  WHERE JTF_AUTH_DOMAINS_TL.DOMAIN_DESC_ID = :old.JTF_AUTH_DOMAIN_ID;
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL ;
END ;


/
ALTER TRIGGER "APPS"."JTF_AUTH_DOMAINS_B_T1" ENABLE;
