--------------------------------------------------------
--  DDL for Trigger JTF_AUTH_PRINCIPALS_B_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."JTF_AUTH_PRINCIPALS_B_T1" 
AFTER DELETE ON JTF.JTF_AUTH_PRINCIPALS_B
FOR EACH ROW
BEGIN
IF :old.IS_USER_FLAG=1 THEN
  DELETE FROM JTF_AUTH_PRINCIPAL_MAPS
    WHERE JTF_AUTH_PRINCIPAL_MAPS.JTF_AUTH_PRINCIPAL_ID = :old.JTF_AUTH_PRINCIPAL_ID ;
ELSE
  DELETE FROM JTF_AUTH_PRINCIPAL_MAPS
    WHERE JTF_AUTH_PRINCIPAL_MAPS.JTF_AUTH_PARENT_PRINCIPAL_ID = :old.JTF_AUTH_PRINCIPAL_ID;
  DELETE FROM JTF_AUTH_ROLE_PERMS
    WHERE JTF_AUTH_ROLE_PERMS.JTF_AUTH_PRINCIPAL_ID = :old.JTF_AUTH_PRINCIPAL_ID;
END IF;
DELETE FROM JTF_AUTH_PRINCIPALS_TL
  WHERE JTF_AUTH_PRINCIPALS_TL.PRINCIPAL_DESC_ID = :old.JTF_AUTH_PRINCIPAL_ID ;
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL ;
END ;


/
ALTER TRIGGER "APPS"."JTF_AUTH_PRINCIPALS_B_T1" ENABLE;
