--------------------------------------------------------
--  DDL for Trigger JTF_AUTH_PERMISSIONS_B_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."JTF_AUTH_PERMISSIONS_B_T1" 
AFTER DELETE ON JTF.JTF_AUTH_PERMISSIONS_B
FOR EACH ROW
BEGIN
DELETE FROM JTF_AUTH_ROLE_PERMS
  WHERE JTF_AUTH_ROLE_PERMS.JTF_AUTH_PERMISSION_ID = :old.JTF_AUTH_PERMISSION_ID ;
DELETE FROM JTF_AUTH_PERMISSIONS_TL
  WHERE JTF_AUTH_PERMISSIONS_TL.PERMISSION_DESC_ID = :old.JTF_AUTH_PERMISSION_ID ;
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL ;
END ;


/
ALTER TRIGGER "APPS"."JTF_AUTH_PERMISSIONS_B_T1" ENABLE;
