--------------------------------------------------------
--  DDL for Trigger JTF_DAC_ROLE_PERMS_TR1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."JTF_DAC_ROLE_PERMS_TR1" 
AFTER INSERT ON JTF.JTF_DAC_ROLE_PERMS
FOR EACH ROW
DECLARE
    PRINCIPAL_NAME VARCHAR2(255) ;
    PERMISSION_NAME VARCHAR2(255) ;
BEGIN

SELECT PERMISSION_NAME INTO PERMISSION_NAME FROM JTF_AUTH_PERMISSIONS_B WHERE
  JTF_AUTH_PERMISSION_ID = :new.PERMISSION_ID;

SELECT PRINCIPAL_NAME INTO PRINCIPAL_NAME FROM JTF_AUTH_PRINCIPALS_B WHERE
  JTF_AUTH_PRINCIPAL_ID = :new.ROLE_ID;

INSERT INTO JTF_DAC_ROLE_PERM_CRIT(ROLE_PERM_CRIT_ID,ROLE_PERM_ID,CRITERIA_ID,JTF_AUTH_PRINCIPAL_ID,
   JTF_AUTH_PERMISSION_ID,PRINCIPAL_NAME,PERMISSION_NAME,BASE_OBJECT,BASE_OBJECT_TYPE,START_ACTIVE_DATE,
   END_ACTIVE_DATE,PROPERTY_NAME, OPERATOR, PROPERTY_VALUE, PROPERTY_VALUE_TYPE, CREATION_DATE,
   CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,OBJECT_VERSION_NUMBER)
   values (JTF_DAC_ROLE_PERM_CRIT_S1.nextVal, :new.ROLE_PERM_ID, -1,:new.ROLE_ID,:new.PERMISSION_ID,
   PRINCIPAL_NAME, PERMISSION_NAME, :new.BASE_OBJECT, :new.BASE_OBJECT_TYPE,:new.START_ACTIVE_DATE,
   :new.END_ACTIVE_DATE,' ',' ',' ',' ',SYSDATE,:new.created_by,SYSDATE, :new.LAST_UPDATED_BY,:new.last_update_login,
   :new.object_version_number);
END ;


/
ALTER TRIGGER "APPS"."JTF_DAC_ROLE_PERMS_TR1" ENABLE;
