--------------------------------------------------------
--  DDL for Trigger MTL_CC_ENTRIES_INTERFACE_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."MTL_CC_ENTRIES_INTERFACE_T1" 
BEFORE UPDATE
OF ACCOUNT_SEGMENT1
,  ACCOUNT_SEGMENT10
,  ACCOUNT_SEGMENT11
,  ACCOUNT_SEGMENT12
,  ACCOUNT_SEGMENT13
,  ACCOUNT_SEGMENT14
,  ACCOUNT_SEGMENT15
,  ACCOUNT_SEGMENT16
,  ACCOUNT_SEGMENT17
,  ACCOUNT_SEGMENT18
,  ACCOUNT_SEGMENT19
,  ACCOUNT_SEGMENT2
,  ACCOUNT_SEGMENT20
,  ACCOUNT_SEGMENT21
,  ACCOUNT_SEGMENT22
,  ACCOUNT_SEGMENT23
,  ACCOUNT_SEGMENT24
,  ACCOUNT_SEGMENT25
,  ACCOUNT_SEGMENT26
,  ACCOUNT_SEGMENT27
,  ACCOUNT_SEGMENT28
,  ACCOUNT_SEGMENT29
,  ACCOUNT_SEGMENT3
,  ACCOUNT_SEGMENT30
,  ACCOUNT_SEGMENT4
,  ACCOUNT_SEGMENT5
,  ACCOUNT_SEGMENT6
,  ACCOUNT_SEGMENT7
,  ACCOUNT_SEGMENT8
,  ACCOUNT_SEGMENT9
,  ADJUSTMENT_ACCOUNT_ID
,  ATTRIBUTE1
,  ATTRIBUTE10
,  ATTRIBUTE11
,  ATTRIBUTE12
,  ATTRIBUTE13
,  ATTRIBUTE14
,  ATTRIBUTE15
,  ATTRIBUTE2
,  ATTRIBUTE3
,  ATTRIBUTE4
,  ATTRIBUTE5
,  ATTRIBUTE6
,  ATTRIBUTE7
,  ATTRIBUTE8
,  ATTRIBUTE9
,  ATTRIBUTE_CATEGORY
,  CC_ENTRY_INTERFACE_ID
,  CYCLE_COUNT_ENTRY_ID
,  CYCLE_COUNT_HEADER_ID
,  CYCLE_COUNT_HEADER_NAME
,  INVENTORY_ITEM_ID
,  ITEM_SEGMENT1
,  ITEM_SEGMENT10
,  ITEM_SEGMENT11
,  ITEM_SEGMENT12
,  ITEM_SEGMENT13
,  ITEM_SEGMENT14
,  ITEM_SEGMENT15
,  ITEM_SEGMENT16
,  ITEM_SEGMENT17
,  ITEM_SEGMENT18
,  ITEM_SEGMENT19
,  ITEM_SEGMENT2
,  ITEM_SEGMENT20
,  ITEM_SEGMENT3
,  ITEM_SEGMENT4
,  ITEM_SEGMENT5
,  ITEM_SEGMENT6
,  ITEM_SEGMENT7
,  ITEM_SEGMENT8
,  ITEM_SEGMENT9
,  LOCATOR_ID
,  LOCATOR_SEGMENT1
,  LOCATOR_SEGMENT10
,  LOCATOR_SEGMENT11
,  LOCATOR_SEGMENT12
,  LOCATOR_SEGMENT13
,  LOCATOR_SEGMENT14
,  LOCATOR_SEGMENT15
,  LOCATOR_SEGMENT16
,  LOCATOR_SEGMENT17
,  LOCATOR_SEGMENT18
,  LOCATOR_SEGMENT19
,  LOCATOR_SEGMENT2
,  LOCATOR_SEGMENT20
,  LOCATOR_SEGMENT3
,  LOCATOR_SEGMENT4
,  LOCATOR_SEGMENT5
,  LOCATOR_SEGMENT6
,  LOCATOR_SEGMENT7
,  LOCATOR_SEGMENT8
,  LOCATOR_SEGMENT9
,  LOT_NUMBER
,  ORGANIZATION_ID
,  REVISION
,  SERIAL_NUMBER
,  SUBINVENTORY
ON "INV"."MTL_CC_ENTRIES_INTERFACE"
FOR EACH ROW

DECLARE
BEGIN
  BEGIN
     if :old.cycle_count_entry_id is not null then
       FND_MESSAGE.SET_NAME('INV',
        'INV_CCEOI_EXPCOL_LOCKED');
       APP_EXCEPTION.RAISE_EXCEPTION;
     end if;
  END;
END;



/
ALTER TRIGGER "APPS"."MTL_CC_ENTRIES_INTERFACE_T1" ENABLE;
