--------------------------------------------------------
--  DDL for Trigger OP_PRSL_TYP_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."OP_PRSL_TYP_UL" 
/* $Header: GMLPR2TG.sql 120.1 2005/08/15 11:17:20 rakulkar noship $ */
instead of update on OP_PRSL_TYP_VL
referencing old as OP_PRSL_TYP
for each row
begin
  GML_OP_PRSL_TYP_PKG.UPDATE_ROW(
    X_PRESALES_ORD_TYPE => :OP_PRSL_TYP.PRESALES_ORD_TYPE,
    X_LANG_CODE => :OP_PRSL_TYP.LANG_CODE,
    X_RELEASE_SCHED_REQD => :OP_PRSL_TYP.RELEASE_SCHED_REQD,
    X_PRICELIST_IND => :OP_PRSL_TYP.PRICELIST_IND,
    X_TRANS_CNT => :OP_PRSL_TYP.TRANS_CNT,
    X_TEXT_CODE => :OP_PRSL_TYP.TEXT_CODE,
    X_DELETE_MARK => :OP_PRSL_TYP.DELETE_MARK,
    X_PRESALES_ORD_CODE => :OP_PRSL_TYP.PRESALES_ORD_CODE,
    X_PRESALES_ORD_DESC => :OP_PRSL_TYP.PRESALES_ORD_DESC,
    X_LAST_UPDATE_DATE => :OP_PRSL_TYP.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :OP_PRSL_TYP.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :OP_PRSL_TYP.LAST_UPDATE_LOGIN);
end UPDATE_ROW;


/
ALTER TRIGGER "APPS"."OP_PRSL_TYP_UL" ENABLE;
