--------------------------------------------------------
--  DDL for Trigger SY_REAS_CDS_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."SY_REAS_CDS_UL" 
instead of update on SY_REAS_CDS_VL
referencing new as SY_REAS_CDS
for each row
begin
  SY_REAS_CDS_PKG.UPDATE_ROW(
    X_REASON_CODE => :SY_REAS_CDS.REASON_CODE,
    X_REASON_DESC2 => :SY_REAS_CDS.REASON_DESC2,
    X_REASON_TYPE => :SY_REAS_CDS.REASON_TYPE,
    X_FLOW_TYPE => :SY_REAS_CDS.FLOW_TYPE,
    X_AUTH_STRING => :SY_REAS_CDS.AUTH_STRING,
    X_DELETE_MARK => :SY_REAS_CDS.DELETE_MARK,
    X_TEXT_CODE => :SY_REAS_CDS.TEXT_CODE,
    X_TRANS_CNT => :SY_REAS_CDS.TRANS_CNT,
    X_REASON_DESC1 => :SY_REAS_CDS.REASON_DESC1,
    X_LAST_UPDATE_DATE => :SY_REAS_CDS.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :SY_REAS_CDS.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :SY_REAS_CDS.LAST_UPDATE_LOGIN);
end UPDATE_ROW;


/
ALTER TRIGGER "APPS"."SY_REAS_CDS_UL" ENABLE;
