--------------------------------------------------------
--  DDL for Trigger XDO_DS_DEFINITIONS_IL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."XDO_DS_DEFINITIONS_IL" 
instead of insert on XDO_DS_DEFINITIONS_VL
referencing new as XDO_DS_DEFINITION_TH
for each row
declare
  row_id rowid;
begin
  XDO_DS_DEFINITIONS_PKG.INSERT_ROW(
      X_ROWID                 => row_id,
      X_APPLICATION_SHORT_NAME        => :XDO_DS_DEFINITION_TH.APPLICATION_SHORT_NAME,
      X_DATA_SOURCE_CODE        => :XDO_DS_DEFINITION_TH.DATA_SOURCE_CODE,
      X_DATA_SOURCE_STATUS      => :XDO_DS_DEFINITION_TH.DATA_SOURCE_STATUS,
      X_START_DATE            => :XDO_DS_DEFINITION_TH.START_DATE,
      X_END_DATE              => :XDO_DS_DEFINITION_TH.END_DATE,
      X_OBJECT_VERSION_NUMBER => :XDO_DS_DEFINITION_TH.OBJECT_VERSION_NUMBER,
      X_ATTRIBUTE_CATEGORY    => :XDO_DS_DEFINITION_TH.ATTRIBUTE_CATEGORY,
      X_ATTRIBUTE1            => :XDO_DS_DEFINITION_TH.ATTRIBUTE1,
      X_ATTRIBUTE2            => :XDO_DS_DEFINITION_TH.ATTRIBUTE2,
      X_ATTRIBUTE3            => :XDO_DS_DEFINITION_TH.ATTRIBUTE3,
      X_ATTRIBUTE4            => :XDO_DS_DEFINITION_TH.ATTRIBUTE4,
      X_ATTRIBUTE5            => :XDO_DS_DEFINITION_TH.ATTRIBUTE5,
      X_ATTRIBUTE6            => :XDO_DS_DEFINITION_TH.ATTRIBUTE6,
      X_ATTRIBUTE7            => :XDO_DS_DEFINITION_TH.ATTRIBUTE7,
      X_ATTRIBUTE8            => :XDO_DS_DEFINITION_TH.ATTRIBUTE8,
      X_ATTRIBUTE9            => :XDO_DS_DEFINITION_TH.ATTRIBUTE9,
      X_ATTRIBUTE10           => :XDO_DS_DEFINITION_TH.ATTRIBUTE10,
      X_ATTRIBUTE11           => :XDO_DS_DEFINITION_TH.ATTRIBUTE11,
      X_ATTRIBUTE12           => :XDO_DS_DEFINITION_TH.ATTRIBUTE12,
      X_ATTRIBUTE13           => :XDO_DS_DEFINITION_TH.ATTRIBUTE13,
      X_ATTRIBUTE14           => :XDO_DS_DEFINITION_TH.ATTRIBUTE14,
      X_ATTRIBUTE15           => :XDO_DS_DEFINITION_TH.ATTRIBUTE15,
      X_DATA_SOURCE_NAME      => :XDO_DS_DEFINITION_TH.DATA_SOURCE_NAME,
      X_DESCRIPTION           => :XDO_DS_DEFINITION_TH.DESCRIPTION,
      X_CREATION_DATE         => :XDO_DS_DEFINITION_TH.CREATION_DATE,
      X_CREATED_BY            => :XDO_DS_DEFINITION_TH.CREATED_BY,
      X_LAST_UPDATE_DATE      => :XDO_DS_DEFINITION_TH.LAST_UPDATE_DATE,
      X_LAST_UPDATED_BY       => :XDO_DS_DEFINITION_TH.LAST_UPDATED_BY,
      X_LAST_UPDATE_LOGIN     => :XDO_DS_DEFINITION_TH.LAST_UPDATE_LOGIN
);
end INSERT_ROW;


/
ALTER TRIGGER "APPS"."XDO_DS_DEFINITIONS_IL" ENABLE;
