--------------------------------------------------------
--  DDL for Trigger XDO_TEMPLATES_UL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."XDO_TEMPLATES_UL" 
instead of update on XDO_TEMPLATES_VL
referencing new as XDO_TEMPLATES_TABLE_HANDLER
for each row
begin
  XDO_TEMPLATES_PKG.UPDATE_ROW(
    X_APPLICATION_SHORT_NAME => :XDO_TEMPLATES_TABLE_HANDLER.APPLICATION_SHORT_NAME,
    X_TEMPLATE_CODE => :XDO_TEMPLATES_TABLE_HANDLER.TEMPLATE_CODE,
    X_ATTRIBUTE6 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE6,
    X_ATTRIBUTE7 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE7,
    X_ATTRIBUTE8 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE8,
    X_ATTRIBUTE9 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE9,
    X_TEMPLATE_ID => :XDO_TEMPLATES_TABLE_HANDLER.TEMPLATE_ID,
    X_APPLICATION_ID => :XDO_TEMPLATES_TABLE_HANDLER.APPLICATION_ID,
    X_DS_APP_SHORT_NAME => :XDO_TEMPLATES_TABLE_HANDLER.DS_APP_SHORT_NAME,
    X_DATA_SOURCE_CODE => :XDO_TEMPLATES_TABLE_HANDLER.DATA_SOURCE_CODE,
    X_TEMPLATE_TYPE_CODE => :XDO_TEMPLATES_TABLE_HANDLER.TEMPLATE_TYPE_CODE,
    X_DEFAULT_LANGUAGE => :XDO_TEMPLATES_TABLE_HANDLER.DEFAULT_LANGUAGE,
    X_DEFAULT_TERRITORY => :XDO_TEMPLATES_TABLE_HANDLER.DEFAULT_TERRITORY,
    X_DEFAULT_OUTPUT_TYPE => :XDO_TEMPLATES_TABLE_HANDLER.DEFAULT_OUTPUT_TYPE,
    X_MLS_LANGUAGE => :XDO_TEMPLATES_TABLE_HANDLER.MLS_LANGUAGE,
    X_MLS_TERRITORY => :XDO_TEMPLATES_TABLE_HANDLER.MLS_TERRITORY,
    X_TEMPLATE_STATUS => :XDO_TEMPLATES_TABLE_HANDLER.TEMPLATE_STATUS,
    X_USE_ALIAS_TABLE => :XDO_TEMPLATES_TABLE_HANDLER.USE_ALIAS_TABLE,
    X_START_DATE => :XDO_TEMPLATES_TABLE_HANDLER.START_DATE,
    X_END_DATE => :XDO_TEMPLATES_TABLE_HANDLER.END_DATE,
    X_DEPENDENCY_FLAG => :XDO_TEMPLATES_TABLE_HANDLER.DEPENDENCY_FLAG,
    X_OBJECT_VERSION_NUMBER => :XDO_TEMPLATES_TABLE_HANDLER.OBJECT_VERSION_NUMBER,
    X_ATTRIBUTE_CATEGORY => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE_CATEGORY,
    X_ATTRIBUTE1 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE1,
    X_ATTRIBUTE2 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE2,
    X_ATTRIBUTE3 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE3,
    X_ATTRIBUTE4 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE4,
    X_ATTRIBUTE5 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE5,
    X_ATTRIBUTE10 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE10,
    X_ATTRIBUTE11 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE11,
    X_ATTRIBUTE12 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE12,
    X_ATTRIBUTE13 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE13,
    X_ATTRIBUTE14 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE14,
    X_ATTRIBUTE15 => :XDO_TEMPLATES_TABLE_HANDLER.ATTRIBUTE15,
    X_TEMPLATE_NAME => :XDO_TEMPLATES_TABLE_HANDLER.TEMPLATE_NAME,
    X_DESCRIPTION => :XDO_TEMPLATES_TABLE_HANDLER.DESCRIPTION,
    X_LAST_UPDATE_DATE => :XDO_TEMPLATES_TABLE_HANDLER.LAST_UPDATE_DATE,
    X_LAST_UPDATED_BY => :XDO_TEMPLATES_TABLE_HANDLER.LAST_UPDATED_BY,
    X_LAST_UPDATE_LOGIN => :XDO_TEMPLATES_TABLE_HANDLER.LAST_UPDATE_LOGIN);
end UPDATE_ROW;

/
ALTER TRIGGER "APPS"."XDO_TEMPLATES_UL" ENABLE;
