--------------------------------------------------------
--  DDL for Trigger XTR_AU_BANK_ACCOUNTS_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."XTR_AU_BANK_ACCOUNTS_T" 
 AFTER UPDATE on "XTR"."XTR_BANK_ACCOUNTS"
 FOR EACH ROW
declare
 cursor CHK_AUDIT is
  select nvl(AUDIT_YN,'N')
   from XTR_SETUP_AUDIT_REQMTS
   where rtrim(EVENT) = 'BANK A/C SETUP';
 --
 l_val VARCHAR2(1);
 --
begin
 -- Check that Audit on this table has been specified
 open CHK_AUDIT;
  fetch CHK_AUDIT INTO l_val;
 if CHK_AUDIT%NOTFOUND then
  l_val := 'N';
 end if;
 close CHK_AUDIT;

 -- Copy to Audit Table the Pre-Updated row
 if nvl(upper(l_val),'N') = 'Y' then
   INSERT INTO XTR_A_BANK_ACCOUNTS(
      ACCOUNT_NUMBER, AUDIT_DATE_STORED, AUDIT_INDICATOR, AUTHORISED,
      BANK_CODE, BANK_NAME, BANK_SHORT_CODE, CASHFLOWS_TO_CURRENT_DATE,
      CREATED_BY, CREATED_ON, CURRENCY, CURRENT_CASHFLOW_DATE, DEFAULT_ACCT,
      DIRECT_DEBIT_AUTHORITY, EFT_SCRIPT_NAME, EFT_SCRIPT_OUTPUT_PATH,
      CODE_COMBINATION_ID, GL_COMPANY_CODE, INTEREST_CALCULATION_BASIS,
      INTEREST_RATE, INTERNAL_PTY, LOCATION, LIMIT_CODE, OPENING_BALANCE,
      OPENING_BAL_HCE, PARTY_CODE, PARTY_TYPE, PORTFOLIO_CODE,
      PRIMARY_SETTLEMENT_METHOD, PARTY_PRIN_CCID, PARTY_INT_CCID,
      PROJECTED_BALANCE, PROJECTED_BALANCE_DATE, PROJECTED_BALANCE_UPDATED_ON,
      SETOFF, SETOFF_ACCOUNT_YN, SETOFF_COMPANY, STATEMENT_DATE, STREET,
      SUB_ACCOUNT_AT, SUB_ACCOUNT_NUMBER, UPDATED_BY, UPDATED_ON,
      DOMICILED_CURRENCY, YEAR_CALC_TYPE
      ) VALUES (
      :OLD.ACCOUNT_NUMBER, SYSDATE, :OLD.AUDIT_INDICATOR, :OLD.AUTHORISED,
      :OLD.BANK_CODE, :OLD.BANK_NAME, :OLD.BANK_SHORT_CODE,
      :OLD.CASHFLOWS_TO_CURRENT_DATE, :OLD.CREATED_BY, :OLD.CREATED_ON,
      :OLD.CURRENCY, :OLD.CURRENT_CASHFLOW_DATE, :OLD.DEFAULT_ACCT,
      :OLD.DIRECT_DEBIT_AUTHORITY, :OLD.EFT_SCRIPT_NAME,
      :OLD.EFT_SCRIPT_OUTPUT_PATH, :OLD.CODE_COMBINATION_ID,
      :OLD.GL_COMPANY_CODE, :OLD.INTEREST_CALCULATION_BASIS, :OLD.INTEREST_RATE,
      :OLD.INTERNAL_PTY, :OLD.LOCATION, :OLD.LIMIT_CODE, :OLD.OPENING_BALANCE,
      :OLD.OPENING_BAL_HCE, :OLD.PARTY_CODE, :OLD.PARTY_TYPE, :OLD.PORTFOLIO_CODE,
      :OLD.PRIMARY_SETTLEMENT_METHOD, :OLD.PARTY_PRIN_CCID, :OLD.PARTY_INT_CCID,
      :OLD.PROJECTED_BALANCE, :OLD.PROJECTED_BALANCE_DATE,
      :OLD.PROJECTED_BALANCE_UPDATED_ON, :OLD.SETOFF, :OLD.SETOFF_ACCOUNT_YN,
      :OLD.SETOFF_COMPANY, :OLD.STATEMENT_DATE, :OLD.STREET, :OLD.SUB_ACCOUNT_AT,
      :OLD.SUB_ACCOUNT_NUMBER, :OLD.UPDATED_BY, :OLD.UPDATED_ON,
      :OLD.DOMICILED_CURRENCY, :OLD.YEAR_CALC_TYPE);
 end if;
end;
/
ALTER TRIGGER "APPS"."XTR_AU_BANK_ACCOUNTS_T" ENABLE;
