--------------------------------------------------------
--  DDL for Trigger XTR_AU_REVALUATION_DETAILS_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."XTR_AU_REVALUATION_DETAILS_T" 
 AFTER UPDATE on "XTR"."XTR_REVALUATION_DETAILS"
 FOR EACH ROW
declare
 cursor CHK_AUDIT is
  select nvl(AUDIT_YN,'N')
   from XTR_SETUP_AUDIT_REQMTS
   where rtrim(EVENT) = 'REVALUATION DETAIL';
 --
 l_val VARCHAR2(1);
 --
begin
 -- Check that Audit on this table has been specified
 open CHK_AUDIT;
  fetch CHK_AUDIT INTO l_val;
 if CHK_AUDIT%NOTFOUND then
  l_val := 'N';
 end if;
 close CHK_AUDIT;
 -- Copy to Audit Table the Pre-Updated row
 if nvl(upper(l_val),'N') = 'Y' then
   INSERT INTO XTR_A_REVALUATION_DETAILS(
      UNIQUE_REF_NUM, COMPANY_CODE, PERIOD_FROM,
      PERIOD_TO, DEAL_TYPE, DEAL_SUBTYPE, PRODUCT_TYPE,
      CURRENCYA, TRANSACTION_PERIOD, FACE_VALUE,
      ENTERED_ON, ENTERED_BY, DEAL_NO, TRANSACTION_NO,
      TRANSACTION_RATE, EFFECTIVE_DATE, EFFECTIVE_DAYS,
      CURRENCY_INDICATOR, CURRENCYB, PORTFOLIO_CODE,
      CONTRACT_CODE, REVAL_RATE, REVAL_VALUE,
      REALISED_PL, UNREALISED_PL, RATE_ERROR,
      FX_REVAL_PRINCIPAL_BAL, FXO_SELL_REF_AMOUNT,
      UPDATED_BY, UPDATED_ON, AUDIT_INDICATOR, AUDIT_DATE_STORED,
      CREATED_ON, CREATED_BY,
      BATCH_ID, revaluation_details_id, SWAP_REF, COMPLETE_FLAG, OVERWRITE_TYPE,
      OVERWRITE_VALUE, OVERWRITE_REASON, FAIR_VALUE, REALIZED_FLAG, ACCOUNT_NO,
      CUMM_GAIN_LOSS_AMOUNT, CURR_GAIN_LOSS_AMOUNT, SOB_FV_GAIN_LOSS_AMOUNT,
      SOB_FAIR_VALUE_AMOUNT, REVAL_CURR_FV_AMOUNT, CTR_CURR_SOB_CURR_FWD_RATE,
      EXCHANGE_RATE_ONE, EXCHANGE_RATE_TWO, NI_DISC_AMOUNT, AMOUNT_TYPE
      ) VALUES (
      :old.UNIQUE_REF_NUM, :old.COMPANY_CODE, :old.PERIOD_FROM,
      :old.PERIOD_TO, :old.DEAL_TYPE, :old.DEAL_SUBTYPE, :old.PRODUCT_TYPE,
      :old.CURRENCYA, :old.TRANSACTION_PERIOD, :old.FACE_VALUE,
      :old.ENTERED_ON, :old.ENTERED_BY, :old.DEAL_NO, :old.TRANSACTION_NO,
      :old.TRANSACTION_RATE, :old.EFFECTIVE_DATE, :old.EFFECTIVE_DAYS,
      :old.CURRENCY_INDICATOR, :old.CURRENCYB, :old.PORTFOLIO_CODE,
      :old.CONTRACT_CODE, :old.REVAL_RATE, :old.REVAL_VALUE,
      :old.REALISED_PL, :old.UNREALISED_PL, :old.RATE_ERROR,
      :old.FX_REVAL_PRINCIPAL_BAL, :old.FXO_SELL_REF_AMOUNT,
      :old.UPDATED_BY, sysdate,
      :old.AUDIT_INDICATOR,sysdate, :old.CREATED_ON, :old.CREATED_BY,
      :old.BATCH_ID, :old.revaluation_details_id, :old.SWAP_REF, :old.COMPLETE_FLAG, :old.OVERWRITE_TYPE,
      :old.OVERWRITE_VALUE, :old.OVERWRITE_REASON, :old.FAIR_VALUE, :old.REALIZED_FLAG, :old.ACCOUNT_NO,
      :old.CUMM_GAIN_LOSS_AMOUNT, :old.CURR_GAIN_LOSS_AMOUNT, :old.SOB_FV_GAIN_LOSS_AMOUNT,
      :old.SOB_FAIR_VALUE_AMOUNT, :old.REVAL_CURR_FV_AMOUNT, :old.CTR_CURR_SOB_CURR_FWD_RATE,
      :old.EXCHANGE_RATE_ONE, :old.EXCHANGE_RATE_TWO, :old.NI_DISC_AMOUNT, :old.AMOUNT_TYPE
      );
 end if;
end;
/
ALTER TRIGGER "APPS"."XTR_AU_REVALUATION_DETAILS_T" ENABLE;
