--------------------------------------------------------
--  DDL for Trigger XTR_AU_BOND_ISSUES_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."XTR_AU_BOND_ISSUES_T" 
 AFTER UPDATE on "XTR"."XTR_BOND_ISSUES"
 FOR EACH ROW
declare
 cursor CHK_AUDIT is
  select nvl(AUDIT_YN,'N')
   from XTR_SETUP_AUDIT_REQMTS
   where rtrim(EVENT) = 'BOND ISSUES SETUP';
 --
 l_val VARCHAR2(1);
 --
begin
 -- Check that Audit on this table has been specified
 open CHK_AUDIT;
  fetch CHK_AUDIT INTO l_val;
 if CHK_AUDIT%NOTFOUND then
  l_val := 'N';
 end if;
 close CHK_AUDIT;
 -- Copy to Audit Table the Pre-Updated row
 if nvl(upper(l_val),'N') = 'Y' then
   INSERT INTO XTR_A_BOND_ISSUES(
      ISSUER, BOND_ISSUE_CODE, FIRST_COUPON_DATE,
      MATURITY_DATE, NO_OF_COUPONS_PER_YEAR, COUPON_RATE,
      CURRENCY, CREATED_BY, CREATED_ON, AUTHORISED,
      YEAR_BASIS, RISK_GROUP, COUPON_TYPE,
      DESCRIPTION, UPDATED_BY,
      UPDATED_ON, AUDIT_INDICATOR, CALC_TYPE, AUDIT_DATE_STORED,
      PRICE_ROUND_TYPE,YIELD_ROUND_TYPE,CALC_ROUNDING,
      PRICE_ROUNDING, YIELD_ROUNDING, PRICING_MODEL, MARKET_DATA_SET, MARGIN,
      ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4,
      ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10,
      ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15
      ) VALUES (
      :old.ISSUER, :old.BOND_ISSUE_CODE, :old.FIRST_COUPON_DATE,
      :old.MATURITY_DATE, :old.NO_OF_COUPONS_PER_YEAR, :old.COUPON_RATE,
      :old.CURRENCY, :old.CREATED_BY, :old.CREATED_ON, :old.AUTHORISED,
      :old.YEAR_BASIS, :old.RISK_GROUP, :old.COUPON_TYPE,
      :old.DESCRIPTION, :old.UPDATED_BY,
      sysdate, :old.AUDIT_INDICATOR, :old.CALC_TYPE,
      sysdate,:old.PRICE_ROUND_TYPE,:old.YIELD_ROUND_TYPE,:old.CALC_ROUNDING,
      :old.PRICE_ROUNDING, :old.YIELD_ROUNDING, :old.PRICING_MODEL, :old.MARKET_DATA_SET, :old.MARGIN,
      :old.ATTRIBUTE_CATEGORY, :old.ATTRIBUTE1, :old.ATTRIBUTE2, :old.ATTRIBUTE3, :old.ATTRIBUTE4,
      :old.ATTRIBUTE5, :old.ATTRIBUTE6, :old.ATTRIBUTE7, :old.ATTRIBUTE8, :old.ATTRIBUTE9, :old.ATTRIBUTE10,
      :old.ATTRIBUTE11, :old.ATTRIBUTE12, :old.ATTRIBUTE13, :old.ATTRIBUTE14, :old.ATTRIBUTE15
);
 end if;
end;
/
ALTER TRIGGER "APPS"."XTR_AU_BOND_ISSUES_T" ENABLE;
