--------------------------------------------------------
--  DDL for Trigger ZX_PRODUCT_OPTIONS_ALL_AT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."ZX_PRODUCT_OPTIONS_ALL_AT" BEFORE UPDATE OF APPLICATION_ID,EVENT_CLASS_MAPPING_ID,ORG_ID,PRODUCT_OPTIONS_ID,ALLOW_TAX_ROUNDING_OVRD_FLAG,CREATED_BY,CREATION_DATE,INCLUSIVE_TAX_USED_FLAG,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,TAX_ALLOW_COMPOUND_FLAG,TAX_CLASSIFICATION_CODE,TAX_METHOD_CODE,TAX_MINIMUM_ACCOUNTABLE_UNIT,TAX_PRECISION,TAX_ROUNDING_RULE,TAX_USE_CUSTOMER_EXEMPT_FLAG,TAX_USE_LOC_EXC_RATE_FLAG,TAX_USE_PRODUCT_EXEMPT_FLAG ON "ZX"."ZX_PRODUCT_OPTIONS_ALL" BEGIN IF fnd_global.audit_active THEN fnd_audit_pkg.audit_on := TRUE;ELSE fnd_audit_pkg.audit_on := FALSE;END IF;END;

/
ALTER TRIGGER "APPS"."ZX_PRODUCT_OPTIONS_ALL_AT" ENABLE;
